### ISSUE TITLE
Grupo de Proyecto

### ISSUE THREAD

**Issue by veneguitas** [IIC2413/Syllabus-2020-1#1]
Hola! Ya tengo grupo, pero no sé si soy un grupo con número par o impar, ¿dónde se puede ver?

**Comment by nivek0o0** [comment]
Hola

Los grupos ya conformados se publicarán en esta [planilla](https://docs.google.com/spreadsheets/d/1VYqNk12FWtImfWbflR8hmHLP16-OVhrNqcGZ6vyOBkA/), la que se irá actualizando 1 vez al día a medida que vayan llegando las inscripciones.

Los alumnos que aparecen en el formulario también se actualizarán 1 vez al día, a medida que se vayan inscribiendo en el curso.

**Comment by nivek0o0** [comment]
Si quieren ser grupo con alguien que aún **no tiene inscrito el curso**, no podrán inscribirse en el formulario hasta cuando él lo tenga. Por lo que, si desean **empezar a trabajar esta semana** en la Entrega 1, inscríbanse solos para obtener un n° de grupo y me avisan para no asignarles un compañero.

**Comment by pedrobihan** [comment]
Hola Kevin! me acaban de inscribir en el curso y quería ver si me podías inscribir de forma manual como pareja con un compañero que todavía no tiene el curso inscrito

**Comment by nivek0o0** [comment]
Hola Pedro, 
¿Puedes inscribirte en el formulario para que se te asigne un n° de grupo? 
Cuando tu compañero tenga el curso lo pongo contigo, debes decirme su nombre.

**Comment by pedrobihan** [comment]
Donde está el link del formulario para inscribirme? En la planilla de arriba no puedo anotarme así que supongo que no es esa.
A mi compañero ya le dieron el ramo porsiacaso.
gracias

**Comment by nivek0o0** [comment]
[Formulario de Inscripción](https://forms.gle/SBkHGqDcq6RM2PZQ7)
[Planilla de Grupos](https://docs.google.com/spreadsheets/d/1VYqNk12FWtImfWbflR8hmHLP16-OVhrNqcGZ6vyOBkA/edit?usp=sharing)

**Comment by jerrymendoza** [comment]
Hola! @pedrobihan, el link se envío por correo, de igual forma lo dejo acá: [https://forms.gle/zr8C5Q5ThFodKrwf9](https://forms.gle/zr8C5Q5ThFodKrwf9)

**Comment by pedrobihan** [comment]
Gracias
Todavía no aparece mi nombre ni el de mi compañero dentro de las opciones para elegir, supongo que habrá que esperar un poco que se actualice el sistema?
Y se puede pedir que se me asigne un grupo par?

**Comment by nivek0o0** [comment]
Si no aparecen en el formulario es porque aún no aparecen en el SIDING, en cuyo caso hay que esperar.

Si quieres empezar a trabajar, puedes hacerlo con el enunciado par y luego yo me encargo de que quedes en un grupo par.

**Comment by pedrobihan** [comment]
Buenísimo gracias

**Comment by DiegoEmilio01** [comment]
Alguna pareja que se quiera cambiar de número par a impar (yo soy impar).
