### ISSUE TITLE
Tablas en Modelo y Esquema

### ISSUE THREAD

**Issue by TamaraErdmann** [IIC2413/Syllabus-2020-1#100]
Hola,
haciendo el modelo y el esquema, nos dimos cuenta de que no estamos seguros de qué tablas poner en el esquema. Sabemos que en el modelo debemos poner las relaciones que hay, con el fin de agrupar los id de cada entidad. Sin embargo, al hacer el modelo, ¿hay que hacer una tabla para cada entidad y para cada relación, por separado? 
Nos confundimos, ya que encontramos estos links en los que nos basamos para hacer el esquema: 
-	https://www.youtube.com/watch?v=LpeX-JVDaPM
-	http://ict.udlap.mx/people/carlos/is341/bases03.html
Además, al momento de programar, debemos dejar como archivos .csv las tablas de relaciones? Por ejemplo, una tabla que sólo contenga id de países e id de ciudades.

Gracias desde ya!

**Comment by fjlopez7** [comment]
La respuesta a tus preguntas es afirmativa, deben crear una tabla para cada una de las entidades y relaciones.
Para cada una de las tablas deberían tener un archivo .csv para cargar los datos.

**Comment by nivek0o0** [comment]
Pero ojo, no toda relación se convierte en una tabla intermedia, solo aquellas cuya cardinalidad es N:M. En aquellas relaciones que son 1:N o 1:1 simplemente la llave primaria de una entidad _viaja_ y se coloca como llave foránea en la otra entidad. Esto último indica que la 2da entidad _pertenece_ o se _relaciona_ con la otra.

Hay una excepción a la regla anterior, que es cuando en una relación 1:N el valor de N podría llegar a ser 0 o bien podrías tener un caso 1:0, es decir, una tupla de esa entidad no se relaciona con ninguna otra. Para evitar tener un NULL como llave foránea se implementa una tabla intermedia. De esta forma la tupla que no se relaciona simplemente no aparece en la tabla intermedia.

**Comment by perezpefaur** [comment]
Me pasa que con esa lógica para los grupos impares por lo menos no habrían tablas intermedias en el diagrama E/R. Ya que:

**Un ticket**: Siempre va a estar asociado a un usuario y destino. Es decir, relación, 1:N con N != 0.
**Una reserva**: Siempre va a estar asociado a un usuario y hotel. Es decir, relación, 1:N con N != 0.
**Un hotel**: Siempre va a estar asociado a una ciudad. Es decir, relación, 1:N con N != 0.
**Una ciudad**: Siempre va a estar asociado a un país. Es decir, relación, 1:N con N != 0.

**Comment by nivek0o0** [comment]
No hay problema con que no existan tablas intermedias.

**Comment by F-arellano** [comment]
pero, si una relación tiene algunos atributos (por ejemplo las reservas), estos también tendria que subirlos en un archivo .csv aparte, ¿o no?

**Comment by nivek0o0** [comment]
No entiendo tu pregunta. 

Tienen que hacer un archivo csv para cada tabla que vayan a crear en la base de datos. En la base de datos como que se pierde la división entre _entidades_ y _relaciones_, ya que se tratan todas como tablas nomás. El significado lo sabes tu.
