### ISSUE TITLE
Filas con ausencias de datos en los csv

### ISSUE THREAD

**Issue by JuaniAndres** [IIC2413/Syllabus-2020-1#101]
Hola en caso de que una fila de los csv entregados le falten datos la eliminamos?. Me refiero en especifico a la fila 5 de artistas-obras-lugares que tiene menos de la mitad de los datos.
Gracias de antemano

**Comment by fjlopez7** [comment]
No debería eliminarse esa fila, ya que nos dice que es un  artista que no tiene una obra en la base de datos actual.

**Comment by JuaniAndres** [comment]
tienes razón no me di cuenta gracias

**Comment by tomasalvarez13** [comment]
Osea que por ejemplo,(en el caso de los impares) si tengo un hotel que no tiene ciudad, debo considerarlo igual?

**Comment by nivek0o0** [comment]
¿Cuál hotel no tiene ciudad?

**Comment by tomasalvarez13** [comment]
Me confundí, mi problema era que los usuarios nuevos que agregaron algunos no tenian reservas,lo que me generaban hoteles vacios. Pero ya lo solucioné, gracias.
