### ISSUE TITLE
Usuarios faltantes 

### ISSUE THREAD

**Issue by yerkko** [IIC2413/Syllabus-2020-1#102]
hola, estábamos importando los datos con mi compañero. nos dimos cuenta que al importar los tickets hay de usuarios con uid 7, 19, 21, 28, 42. Sin embargo, estos no están en el CSV original.
![image](https://user-images.githubusercontent.com/48332955/78462678-c3d11980-76aa-11ea-9591-adb83e627df8.png)
![image](https://user-images.githubusercontent.com/48332955/78462692-f2e78b00-76aa-11ea-94c0-a0d95a7f837b.png)
Hay que ver estas incongruencias al hacer el pre-process o hay un error en los archivos?
@ShescBlank

**Comment by nivek0o0** [comment]
Es un error de los datos :cry: 
Lo vamos a solucionar lo antes posible y los subiremos nuevamente.

**Comment by yerkko** [comment]
Entiendo. Muchas gracias por responder tan pronto :)

**Comment by nivek0o0** [comment]
Los datos fueron actualizados ya que justamente faltaba la ciudad a la que pertenece cada hotel.
Además faltaban algunos usuarios.

Lo sentimos! :disappointed:
