### ISSUE TITLE
Cuándo Viajes/Destinos son distintos

### ISSUE THREAD

**Issue by elisafdz** [IIC2413/Syllabus-2020-1#103]
Hola!

¿Un viaje es considerado como distinto al otro si cualquiera de sus atributos es distinto? por ejemplo si hay un viaje desde Florencia a Roma con capacidad para 50 personas y otro desde Florencia a Roma con capacidad para 40 personas, debo considerarlos como distintos? (al minuto de asignar un id a cada viaje).

Gracias!!

**Comment by nivek0o0** [comment]
Así es, dos viajes corresponden a la misma fila si coinciden en **todos** sus atributos.
