### ISSUE TITLE
Feedback aplicar "foreign key"

### ISSUE THREAD

**Issue by nhorellana** [IIC2413/Syllabus-2020-1#104]
Hola! Para la E1 deberíamos haber sabido/aplicado lo que es una "foreign key"?

**Comment by fjlopez7** [comment]
No deberían haber sabido ese contenido, pero si tienes problemas con tú nota por algún descuento que encuentras injustificado de recomiendo [recorregir](https://forms.gle/qBEZkXzwMXrKC2sR8) la entrega.
