### ISSUE TITLE
Relación Ciudad-Hotel

### ISSUE THREAD

**Issue by elisafdz** [IIC2413/Syllabus-2020-1#105]
Hola!
Estaba revisando los datos que se nos entregan y quería saber si hay una forma de saber en qué ciudad se encuentra cada hotel.

Gracias!

**Comment by nivek0o0** [comment]
Hola, 
los datos fueron actualizados ya que justamente faltaba la ciudad a la que pertenece cada hotel.
Además faltaban algunos usuarios.

Lo sentimos! :disappointed:

**Comment by elisafdz** [comment]
Ok, gracias!
