### ISSUE TITLE
Entidad destinos y relacion con ciudades

### ISSUE THREAD

**Issue by perezpefaur** [IIC2413/Syllabus-2020-1#106]
Hay una relación destinos con ciudades? Si es que la hay cómo se podrían relacionar?. Mi pregunta nace porque en destinos hay dos atributos, que son la ciudad de origen y la ciudad de destino, entonces una nose como una relación (si es que lo hay) podría recibir las dos llaves de ciudad de origen y destino. 
Yo lo que habia pensado es tener el id de origen y id de llegada como atributo, no se me ocurre nada mejor.

**Comment by arpincheira** [comment]
Hola, lamento la demora,
recuerda que al momento de modelar tu proyecto debes preguntarte: "¿cómo voy a acceder a la información después?". Con respecto a la relación que pretendes poner (los ids de las ciudades de origen y destino dentro de la tabla de destino como atributos), debes aplicar este mismo criterio. Hay que mencionar que tu solución efectivamente permitiría conectar de manera eficiente las tablas. 

Espero que esto aclare tu duda.

**Comment by Tomas-Ira** [comment]
Hola, a mí no me queda claro. No entiendo como debiese relacionar el viaje con las ciudades. 

Cada viaje tiene 2 ciudades (origen y destino). Se puede en un diagrama hacer dos entidades llamadas ciudades y relacionarlas ambas con un mismo viaje?

**Comment by nivek0o0** [comment]
En el diagrama E/R podrías modelarlo como 2 relaciones/rombos distintos: "origen" y "destino"

**Comment by jitorcas** [comment]
Hola! @nivek0o0 con respecto a tu ultimo comentario, al poner destino como relación entre ticket y ciudad perdería el id y en consecuencia el registro viaje que pide el enunciado, o no?
o te refieres a "destino" como llegada y no como la entidad que posee hora de salida y duración (ademas de cid_origen y cid_destino)?

**Comment by nivek0o0** [comment]
me referia a la llegada: una relación llamada **origen** y otra **llegada** entre Ciudad y Destinos/Viajes

**Comment by tamaralues** [comment]
Hola! es que tengo una duda con esa solución. En el caso de definir dos relaciones (origen, destino),  dado que destinos tiene el nombre de la ciudad, en la relación  se debería definir una tabla que contengas eso dos atributos? o dado que la relación es 1:1 se podría enviar el nombre directamente, sin embargo, ¿eso requeriría que el nombre sea un llave primaria?

**Comment by nivek0o0** [comment]
Dado que la relación es N:1 (pq un viaje tiene una única ciudad de origen pero una ciudad puede ser origen de múltiples destinos), te puedes evitar la tabla intermedia y solo ocupar una llave foránea.

Una llaves foránea siempre debe ser llave primaria en la tabla original. 

Por otra parte, sugerimos el uso de IDs numéricos como llaves primarias.

**Comment by tamaralues** [comment]
Pero ahi entonces deberíamos modificar el csv de destinos no no? para que en vez de tener los nombres tenga los cid?

**Comment by nivek0o0** [comment]
Claro, la idea es que le agreguen un ID a todas las entidades (excepto usuarios) y luego donde haya que referenciar una entidad se reemplaza por su ID.
