### ISSUE TITLE
Problema de referencia con CREATE VIEW

### ISSUE THREAD

**Issue by ChayoPerez** [IIC2413/Syllabus-2020-1#107]
Hola! He estado estudiando SQL y tuve un problema con views. Mi código dice algo así:

> CREATE VIEW Iglesias_seleccionadas AS SELECT id_lugar  FROM ...

La cosa es que después, aunque:

>SELECT` * FROM Iglesias_seleccionadas;`
>SELECT id_lugar FROM Iglesias_seleccionadas;

funciona bien (imprime los id_lugar de forma correcta), no sé cómo referirme a la columna que creé para por ejemplo hacer:

>Lugares.id_lugar = Iglesias_seleccionadas.id_lugar

Me dice error:

>Error: no such column: Iglesias_seleccionadas.id_lugar

Se puede hacer de alguna forma? 
Agradecería mucho ayuda! Gracias de antemano

**Comment by nivek0o0** [comment]
A mi me funciona perfecto la referencia a la columna de la vista.
Si quieres puedes pegar aquí todos los comandos que conducen al error para que los reproduzca en tu BD.

**Comment by ChayoPerez** [comment]
Logré que funcionara, gracias! No sé qué es lo que no corría bien x'D
