### ISSUE TITLE
Comando \COPY

### ISSUE THREAD

**Issue by jfernandez7** [IIC2413/Syllabus-2020-1#108]
Hola! Estaba siguiendo al pie de la letra los pasos de la wiki para subir los csv a las tablas de psql y no me dejó hacerlo porque no era superuser. Qué debo cambiar? No quiero probar con cualquier cosa de internet porque no me manejo mucho y no quiero enredar más las cosas

**Comment by benjastraub** [comment]
En la consola de psql puedes usar `ALTER USER <nombre_usuario> WITH SUPERUSER;`

**Comment by jfernandez7** [comment]
Me dice 
ERROR:  must be superuser to alter superusers

**Comment by nivek0o0** [comment]
Puedes intentar ahora?

**Comment by jfernandez7** [comment]
Me sigue saliendo lo mismo!!

**Comment by nivek0o0** [comment]
Hola! Ya tengo la solución.

1. Estás usando `COPY` en vez de `\COPY`. Por eso te reclama por los permisos.

2. Hice una prueba importando los usuarios en una tabla llamada `usuarios2` y funcionó pefecto. Cuando uses el comando de la wiki para importar usuarios tendrás un error del tipo `extra data after last expected column`. Esto ocurre porque en el csv está la columna `uid` pero en la tabla no. 

3. Por favor c**ambia la contraseña** de tu usuario de postgres! Es su responsabilidad evitar que alguien se meta a su BD a hacer cambios no deseados. Este repositorio es **público** y la BD está **expuesta**, cualquier hacker ruso podría dejarles la embarrada.

**Comment by jfernandez7** [comment]
Ahi si funciono! Muchas gracias!! Y si teniamos la columna de uid asique no tuvimos más errores
