### ISSUE TITLE
¿"Reserva" es entidad o relación?

### ISSUE THREAD

**Issue by juanpacl111** [IIC2413/Syllabus-2020-1#109]
No me queda claro si es que "reserva" corresponde a una entidad o una relación. Yo pensaría que es una relación, ya que asocia el usuario con el hotel. Es relevante de que manera se define?

**Comment by nivek0o0** [comment]
Sí, es muy relevante.

Recuerda que la llave primaria de una relación se compone de las llaves primarias de las entidades que relaciona. Si consideras `Reservas` como una relación, su llave primaria sería (id_usuario, id_hotel). Esto implica directamente que no vas a poder repetir esa tupla en toda la tabla.

¿Es ese el comportamiento deseado? ¿Queremos limitar a que 1 usuario pueda reservar el mismo hotel una única vez en la vida?

Si la respuesta anterior es negativa, entonces conviene que `Reservas` sea una entidad que tenga su propio ID. De esta forma desaparece la limitación anterior.

**Comment by maribeiro97** [comment]
No se podria considerar Reservas como una relacion y simplemente agregarle una llave id_reserva para solucionar esto? Me hace mas sentido que Reservas sea una relacion y no una entidad.

**Comment by nivek0o0** [comment]
Estamos hablando del diagrama E/R o del esquema relacional y posterior implementación?

**Comment by maribeiro97** [comment]
Del diagrama, mientras lo estaba dibujando encontre que era mas simple tener algo como [Usuario] -> < Reserva > -> [Hotel] en vez de [Usuario] <relacion_1> [Reserva] <relacion_2> [Hotel]. Pero para usar lo primero necesito otra llave aparte de id_usuario e id_hotel para que funcione cuando lo implemente.

**Comment by nivek0o0** [comment]
En el diagrama E/R, **por definición** una relación/rombo tiene como llave primaria ambas llaves primarias de las entidades que relaciona, que en este caso sería `(uid, hid)`. 

Por lo tanto, no puedes simplemente añadirle un id propio. Si lo haces se convierte en entidad.

**Comment by maribeiro97** [comment]
Ah, entiendo, gracias :)

**Comment by tamaralues** [comment]
Hola! una pregunta, en el caso de se 1-1 la relación, es necesario definir una tabla para esa relación?

**Comment by nivek0o0** [comment]
Depende. Si es estrictamente 1:1 entonces no se necesita tabla intermedia, ya que solo se pone una llave foránea en alguna de las tablas.

**Pero**, si puedes llegar a tener un caso 0:1 o 1:0 (dependiendo de cuál llave viajó) entonces si necesitarías tabla intermedia para evitar dejar un null como llave foránea.
