### ISSUE TITLE
Tipo de dato para horarios

### ISSUE THREAD

**Issue by bahidalgo** [IIC2413/Syllabus-2020-1#11]
Hola,
¿Existe un tipo de dato para una variable del tipo "_hr:mn:sg_" (por ejemplo, 21:04:42)? Intenté utilizarlo en forma de _date_ para crear el esquema en **RelaX** y no resultó. Mi otra opción es trabajar los horarios en forma de segundos o minutos para poder filtrar según horarios mayores o menores, pero esto provocaría que en la base de datos aparecería una tupla como:

**id_a |   horario(minutos)**        
  1        720

y no

**id_a |   horario**        
  1        12:00

Y así poder comparar horarios, pero se ve feo. ¿Pueden ayudarme?

**Comment by jmndoza** [comment]
Hola @bahidalgo !
Para la hora puedes ocupar el formato 'HH:MM:SS' en string. 
Hice un ejemplo acá, abajo esta la consulta  [-> RelaX](https://dbis-uibk.github.io/relax/calc.htm?data=gist:507a52e8a18ca2f132a2d285fb315204)

esa es la idea?

**Comment by bahidalgo** [comment]
Si! Es muy extraño que funcione str > str, nunca lo consideré. Pero muchas gracias, era lo que necesitaba.
