### ISSUE TITLE
¿Cuándo las Obras de Arte son distintas?

### ISSUE THREAD

**Issue by fcartoni** [IIC2413/Syllabus-2020-1#111]
Hola! Tengo una pregunta de los archivos csv. El archivo que tiene los artistas, obras y lugares, tiene obras de arte con el mismo nombre pero que tienen diferentes fechas, artista, lugar, etc. 
Puedo asumir entonces que una obra de arte siempre estará hecha por un solo artista? Porque inicialmente pensé que podían estar hechas por más de uno (dado que obras con el mismo nombre tenían a más de un artista), pero como tienen los otros atributos distintos como que me confundí

**Comment by arpincheira** [comment]
Hola,
efectivamente se puede dar que hayan dos obras de arte con el mismo nombre pero que sean hechas por el mismo artista, esto se da por diversos motivos como las reinterpretaciones de un relato, un intento de homenaje a la obra de un artista, etc... . Es por esto que dentro del dataset entregado en los. archivos csv se trata de mostrar un poco esto. 

Para resumir, efectivamente se puede considerar que dos obras son distintas si es que están hechas por otros artistas y en otras épocas, aunque también pueden estar hechas por más de un artista, como es el caso de la pitufiescultura. 

Espero haberte sido de ayuda.

P.D. : Si quieres saber un poco más al respecto, existe una cuneta de Instagram llamada rinastudio.art que el 19 de Marzo subió un ejemplo con los nacimientos de Venus, en los que se puede apreciar que son obras distintas pese a tener el mismo nombre.

**Comment by nivek0o0** [comment]
Y para complementar la respuesta de Andrés, en este caso se cumple la misma regla que se mencionó en la issue #103: 2 obras serán la misma entidad si coinciden en **todos** sus atributos, sin importar los artistas.

Por lo tanto, si hay 2 obras con el mismo nombre pero distintos atributos, se trata de entidades distintas que tienen un alcance de nombre nomás.
