### ISSUE TITLE
Ruby Gemfile : diferencia de versiones

### ISSUE THREAD

**Issue by ChayoPerez** [IIC2413/Syllabus-2020-1#112]
Hola!
Mi grupo de trabajo tiene el archivo .erb con su Gemfile con ruby '2.6.5' y mi Ruby 2.6.6 no puede correrlo. Sale el error:

`Your Ruby version is 2.6.6, but your Gemfile specified 2.6.5`

Es posible hacerlo compatible o tengo que bajarme la versión exacta?

Gracias!

**Comment by fjlopez7** [comment]
Si no me equivoco esta duda es de ingeniería de Software, pero te recomiendo coordinar con tus compañeros la versión de ruby. Si van a ocupar la versión 2.6.5, para cambiar tu versión puedes ocupar el comando `rvm install version -v 2.6.5`. 

Luego para cambiar la versión por default ejecutas  `rvm --default use 2.6.5` y para comprobar usa el comando `ruby -v`.
