### ISSUE TITLE
Conectar la carpeta Sites a Github

### ISSUE THREAD

**Issue by VicenteEspinosa** [IIC2413/Syllabus-2020-1#113]
Hola, hay alguna forma de conectar la carpeta Sites que esta en nuestra base de datos a un repositorio en github??

**Comment by nivek0o0** [comment]
Sí, en la wiki está explicado el paso a paso para que su carpeta de usuario `grupoXX` se conecte a un repositorio remoto.

Solo deben replicarlo dentro de la carpeta Sites. 

En resumen es: `git init`, `git remote add origin <urlRepoRemoto`>

**Comment by VicenteEspinosa** [comment]
ya gracias, pero se puede conectar al mismo repositorio que usamos para conectarnos a la carpeta `grupoXX` o tenemos que crear otro repositorio para `Sites`?

**Comment by nivek0o0** [comment]
Ahh, si ya tienen un repositorio para grupoXX entonces usen ese. 

Crean la carpeta Sites en github y hacen git pull en el servidor.
Si ya tienes algo avanzado en el servidor, commiteas lo que esté dentro de Sites en el servidor y haces git push.
