### ISSUE TITLE
Foreing Key entre Artistas y Obras

### ISSUE THREAD

**Issue by itplanella** [IIC2413/Syllabus-2020-1#114]
Hola! En la entrega 2 estaba pensando que si no existe un artista, tampoco sus obras por lo que en ese caso debería ser una foreing key. Sin embargo, al tener una relación y la posibilidad de tener mas de un artista por obra quería saber como se podría aplicar en este caso o si se puede o debe dejar sin llave foránea. Para que se entienda mejor tengo las entidades Artistas, Obras y la relación HechaPor. Muchas gracias de antemano.

**Comment by nivek0o0** [comment]
Hola,

cuando mencionas _si no existe un artista, tampoco sus obras_, estás mencionando una regla de negocio. Por ejemplo, la empresa dueña de esta aplicación podría querer mantener las obras con autor desconocido si el artista es eliminado de la BD, así como también podria querer borrar en cadena todas su obras. 

**Pero** en este proyecto no vamos a eliminar ninguna entidad de su BD, así que no deben preocuparse de qué pasaría con las demás entidades relacionadas.

Dado que este caso entre Artistas y Obras es de cardinalidad N:M, es necesaria una tabla intermedia. Cuando pasa esto, ya no hay llaves foráneas en la tabla Artistas ni tampoco en Obras. Las llaves foráneas se las lleva la tabla intermedia. En tu caso sería `HechaPor(aid: int FK, oid: int FK)`

**Comment by mrrebolledo** [comment]
Hola! Tengo la misma tabla de HechaPor pero no me queda claro si es que estas dos llaves, además de ser foráneas, también son llaves primarias? Igual de todas maneras sé que no se pueden poner dos llaves primarias en psql pero me gustaría saber si lo tengo que poner igual o no en el esquema.

**Comment by FloValdes** [comment]
Hola @mrrebolledo, el par (oid, aid) es la llave primaria de tu tabla, ya que ninguna por sí sola es única. Es verdad que no se puede tener más de una llave primaria, pero eso se refiere a que no puedes tener oid y aid como llaves primarias por si solas, pero el par (oid, aid) es una llave primaria válida (y la correcta).

**Comment by nivek0o0** [comment]
Y para definirlas se ocupa la sintaxis `CREATE TABLE Tabla(oid: int, aid: int, PRIMARY KEY(oid, aid))`.

Recuerda especificar también que aid y oid son llaves foráneas.

**Comment by mrrebolledo** [comment]
gracias!!
