### ISSUE TITLE
Tickets comprados y su fecha a considerar 

### ISSUE THREAD

**Issue by ShescBlank** [IIC2413/Syllabus-2020-1#115]
En la consulta del dinero gastado por un usuario en todos los tickets que ha comprado, considero los tickets con fechas de compra que todavía no ocurren? Ej: Hay una fecha de compra 2020-12-19.
Dentro de la misma idea, si en la consulta 6 se ponen fechas futuras, debo considerar el gasto de esas fechas de compra?

Muchas gracias :D

**Comment by nivek0o0** [comment]
Hola!

Los tickets con fecha de compra del futuro **no deben ser considerados** en la consulta 4. La consulta 4 pide el dinero **gastado**, es decir en el pasado. 
Una explicación para esos tickets es que surgen a partir de convenios con distintas empresas, donde estamos seguros que en esa fecha exacta serán comprados.

En la consulta 6 **si se deben considerar** esos tickets. Si te pedimos los tickets entre 2020-06-01 y 2020-12-31 debes entregarnos la suma de dinero en tickets para cada usuario de la BD.

**Comment by aalmuna** [comment]
Muchas gracias por responder tan rápido! Y perdón, escribí la issue en un momento con muchas cosas y se me olvidó saludar :c
Gracias por la ayuda :D

**Comment by StroveLight** [comment]
Entonces para la 4 se necesita obtener la fecha en la que se está realizando la consulta? (es decir, que depende de la fecha del computador o algo similar)

**Comment by nivek0o0** [comment]
Claro. Postgres tiene una función para obtener el timestamp actual.
