### ISSUE TITLE
Formato de Fecha de fallecimiento Artistas

### ISSUE THREAD

**Issue by pelao97** [IIC2413/Syllabus-2020-1#116]
En el archivo artistas-lugares-obras.csv ha y dos artistas que parecieran estar vivos u otra cosa, porque coincide que las fechas están en orden inverso y me indica el año 2100, esto es intencional, o es un error de la base de datos??

![image](https://user-images.githubusercontent.com/42186906/78850537-770c7c00-79e5-11ea-8b01-ab6ef8ed2f63.png)

**Comment by nivek0o0** [comment]
Hola, es intencional por 2 motivos: 
- Queremos que experimenten con distintos tipos de formato de fechas. ¿Es Postgres capaz de interpretarla correctamente? ¿Debe toda la columna tener el mismo formato?
- Esa fecha de muerte está **claramente mal modelada**. La persona que creó ese registro quería decir que el artista aún estaba vivo pero el sistema no le permitía dejar un null. Ustedes tienen que modelarlo correctamente porque una fecha del futuro no tiene sentido.

**Comment by fcartoni** [comment]
Hola! No me queda claro. Esperan que entonces dejemos esa tupla con fecha de fallecimiento con valor null ?? O que??

**Comment by nivek0o0** [comment]
No, la idea es evitar a toda costa los nulls. Para ellos deben pensar en una forma de asociar fechas de fallecimiento a los artistas que corresponda.

Y respecto a la fecha al revés, pueden arreglarla manualmente y filo.

**Comment by mrrebolledo** [comment]
Traté de arreglarlo a mano directo en el excel y también por python pero igual se me dan vuelta las dos fechas y no me deja ponerlo como año/mes/dia. Qué puedo hacer?

**Comment by nivek0o0** [comment]
Probaste importarlo en Postgres nomás para ver si las lee correctamente?

**Comment by mrrebolledo** [comment]
Siii, ese es el problema. Ahí me tira un error de este tipo y sin esas tablas no puedo seguir avanzando con la entrega.
![error](https://user-images.githubusercontent.com/53914076/78954567-83a6d800-7aaa-11ea-8290-4501697d3537.PNG)

que puedo hacer?

**Comment by nivek0o0** [comment]
Tal vez sea alguna maña de excel. Te sugiero editar el archivo con el bloc de notas o bien desde la terminal. Alli es imposible que la fecha se de vuelta

**Comment by mrrebolledo** [comment]
Ya lo hice y sigue pasando lo mismo
![image](https://user-images.githubusercontent.com/53914076/78963119-7991d300-7ac4-11ea-9cf8-44c27af6a7ce.png)
![image](https://user-images.githubusercontent.com/53914076/78963169-a8a84480-7ac4-11ea-95b3-c44e96908fa8.png)
Como se ve en las fotos, en el bloc de notas me sale la fecha como quiero (porque lo cambié) pero en excel sigue estando igual aunque lo abra después.

**Comment by nivek0o0** [comment]
Puede que esa celda esté en formato de fecha dd-mm-aaaa y por eso Excel la lee y te la muestra así. Es posible cambiarlo a formato de fecha aaaa-mm-dd. (Así como excel tiene formato general, number, currency, etc)

Pero insisto, filo el Excel, si con el bloc de notas lo ves bien, entonces súbelo al servidor e impórtalo en postgres.

**Comment by mrrebolledo** [comment]
Ya me salió, gracias!
