### ISSUE TITLE
Dependencias Funcionales y Llave Primaria Destino

### ISSUE THREAD

**Issue by F-arellano** [IIC2413/Syllabus-2020-1#118]
tengo la duda de que cosas me bastan para determinar el precio de un viaje. Algunos servicios de transporte tienen precios diferentes segun el dia, hora y tipo de asiento (lo cual podría ir en el número de este), pero otros solo dependen del origen y el destino, entonces, ¿es (fechaviaje, horasalida, ciudadorigen, ciudaddestino, medio, asiento) una llave minimal?

**Comment by nivek0o0** [comment]
Tal como dices, no es claro qué atributos determinan el precio del viaje. 

Lo que se suele hacer es agregar un ID úniconque identifique a la entidad, de esa forma todos los atributos quedan determinados únicamente por el ID si en realidad pertecen al destino.

**Comment by F-arellano** [comment]
pero definir un ID no quita las dependencias del precio con otros atributos (si el precio dependiese solo de la ciudad de origen, destino y medio de transporte, y mi llave es el ID entonces la tabla no estaría en 3NF) ¿puedo escribir en el pdf que asumi algunas dependencias para dejarlo en BCNF o 3NF?

**Comment by nivek0o0** [comment]
Definir un ID sí quita la dependencia del precio, porque ahora es posible tener:

ID | origen | destino | medio | hora_salida | precio
|-|-|-|-|-|-|
1 | roma | parís | tren | 10:00 | $5.000
2 | roma | parís | tren | 10:00 | $10.000

Lo podría representar que tengo una tarifa estándar y una tarifa premium para el mismo viaje. En este caso el precio es determinado únicamente por el ID. 

>  ¿puedo escribir en el pdf que asumi algunas dependencias para dejarlo en BCNF o 3NF?

Sí, pueden escribir los supuestos que adoptaron para definir las dependencias funcionales. Lo importante es que ellos no contradigan el enunciado ni las respuestas que hemos dado en estas issues.
