### ISSUE TITLE
Duda esquema entrega 2

### ISSUE THREAD

**Issue by oscars810** [IIC2413/Syllabus-2020-1#119]
Hola!
Tengo la duda si al hacer el esquema es necesario poner las relaciones, por ejemplo:
Persona(id, ...)
Ciudad(id, ...)
Persona_pertenece(id_ciudad, id_persona)
Y así con cada relación....
¿O tal vez solo poner las tablas intermediarias que son estrictamente necesarias en relaciones n a n?
Porque hicimos relaciones para todas las entidades independiente de sus relaciones.

**Comment by nivek0o0** [comment]
Hola,
La verdad es que da lo mismo si creas tablas intermedias aunque se trate de una relación 1:1 o 1:N, estará correcto igual. El tema está en que eso no es necesario y tampoco es eficiente porque te agrega JOINs a las consultas. Además es trabajo extra para uds.

Por esa razón se simplifica y se sugiere creae solo las tablas intermedias necesarias para las relaciones n:m

**Comment by oscars810** [comment]
¿Entonces en el esquema incluyo mis tablas intermedias?

**Comment by nivek0o0** [comment]
Sí, en el esquema se incluye toda tabla que vayas a crear después en la base de datos.
