### ISSUE TITLE
Ejercicio propuesto 3.4

### ISSUE THREAD

**Issue by matioprts** [IIC2413/Syllabus-2020-1#12]
Hola!
Resolviendo el ejercicio me surgió una duda, en el caso de que me pidan un ejercicio parecido pero ahora buscar actores que hayan actuado en 3 o más películas, es posible realizarlo de la misma forma pero cambiando el doble producto cruz por el triple producto cruz de Actuó_En consigo misma? o se vuelve un problema más complejo? De antemano muchas gracias!

**Comment by arpincheira** [comment]
Hola, 
efectivamente puedes realizar un triple producto cruz como una alternativa para poder responder la consulta, aunque dependiendo de los datos pueden llegar a existir métodos más sencillos. 

Con respecto a lo de la complejidad, efectivamente resulta más complejo al momento de realizar y ejecutar un algoritmo de este estilo, especialmente si tu base de datos es grande, aunque de todos modos se puede lograr a partir de esto llegar a un resultado correcto, como mencioné anteriormente.

Saludos
