### ISSUE TITLE
Consistencia entre tablas psql y diagrama 

### ISSUE THREAD

**Issue by mrrebolledo** [IIC2413/Syllabus-2020-1#120]
Hola! No me queda claro si mi diagrama entidad-relación tiene que reflejar literalmente lo que hice en psql (y en las tablas) o no. 

Por ejemplo,si  tengo dos entidades relacionadas por algo, pero yo no hice tabla para esta relación, igual pongo en el diagrama el rombo con la relación?  

Otro caso es que aunque psql no me deje poner dos llaves primarias, igual pongo ambas como primarias en los esquemas?

**Comment by FloValdes** [comment]
Hola
1. SIempre debes relacionar dos entidades con un rombo. Puede que este rombo se convierta en tabla o no, pero siempre debes ponerlo.
2. Nunca debes tener dos o más llaves primarias, siempre es una. Pero puedes tener una llave primaria con varios atributos. Por ejemplo, puedes tener el par (id1, id2) como llave primaria. Es solo una pero tiene dos atributos (y ninguno de estos atributos es una llave primaria por si solo).

**Comment by mrrebolledo** [comment]
Gracias! Otra pregunta, estoy editando los códigos de php con visual studio code, pero cuando quiero que el usuario me de un horario o una fecha necesito pasar ese dato a tipo time o date (porque así lo tengo en mis tablas de psql). Busqué en google pero solo me salen las que son mezcla entre fecha y hora pero no por separado.
