### ISSUE TITLE
Duda base de datos entrega 2

### ISSUE THREAD

**Issue by gachondoj** [IIC2413/Syllabus-2020-1#121]
Hola, no entiendo bien como entrar a la base de datos para la entrega 2. trate con ssh grupo1e2@codd.ing.puc pero no se cual es la clave para eso

**Comment by FloValdes** [comment]
Hola, para entrar al servidor siempre debes ocupar
`ssh grupo<numero de grupo>@codd.ing.puc.cl`
No cambia para cada entrega. Lo que cambia es a qué carpeta dentro del servidor debes subir las cosas. Está todo especificado en el enunciado, pero por ejemplo debes subir el reporte a:
`/home/grupoX/Entrega2`
La cual es una nueva carpeta llamada `Entrega2` que debes crear tal como creaste una carpeta para tu entrega 1.

**Comment by nivek0o0** [comment]
Hola,
para complementar, lo que se llama `grupoXe2` es la **base de datos** para esta entrega. Para acceder a ella debes hacer entrar a Postgres con `psql` y luego hacer `\c grupoXe2`
