### ISSUE TITLE
Relación entre Lugares y Ciudades

### ISSUE THREAD

**Issue by fnberrios** [IIC2413/Syllabus-2020-1#123]
Hola, estoy generando el esquemas solicitado para la entrega 2 y, como es de esperar, el enunciado solicita guiarse por los requerimientos de la entrega 1. Sucede que el enunciado de la entrega 1 pide que, para grupos pares, la tabla de Lugares contenga el nombre de la cuidad a la que pertenece. Cito:
"Todos estos lugares tienen un nombre y se debe guardar el nombre de la ciudad en que se encuentran, que son ciudades donde la agencia tiene presencia"
¿Es necesario cumplir este requerimiento para la entrega 2? Lo pregunto porque me parece redundante almacenar el nombre de la cuidad en la tabla Lugares.
Gracias de antemano.

**Comment by nivek0o0** [comment]
Hola, no es necesario guardar **exactamente** el nombre, pero sí una referencia a la ciudad donde pertenece el lugar. Dependerá de cómo modelaste la tabla ciudades: si les agregaste un ID o tomaste como supuesto nombre único y por lo tanto nombre es PK.

**Comment by fnberrios** [comment]
Gracias!
