### ISSUE TITLE
Error de encoding \COPY

### ISSUE THREAD

**Issue by agustin-rios** [IIC2413/Syllabus-2020-1#124]
Me pasa que tratando de pasar los datos en csv a tablas en psql me sale el siguiente mensaje: ERROR:  invalid byte sequence for encoding "UTF8": 0xed 0x73 0x22, y nose como arreglarlo (agregando el comando ENCODING no me funciono bien)

**Comment by nivek0o0** [comment]
Intenta agregar `encoding 'latin1'` al comando cuando importas los datos. A veces sucede que Windows agrega caracteres extraños al inicio o final de los archivos que manipula.

Por otra parte, estuve mirando tu DB y están creando las tablas en la base de datos `grupo21`. El enunciado dice que deben crearlas en `grupo21e2`, asi que ojo ahí

**Comment by agustin-rios** [comment]
Muchas gracias! En este caso grupo21e2 es la carpeta Entrega2 en grupo21 o es otra diferente?

**Comment by nivek0o0** [comment]
`grupo21e2` es una **base de datos** dentro de la aplicación Postgres, a la cual accedes con el comando `psql` en el servidor. La idea es ocupar una distinta para cada entrega. Postgres tiene los siguientes niveles de abstracción: clusters > databases > schemas > tablas. 

Las carpetas del **servidor**  donde suben los reportes se deben llamar `Entrega1, Entrega2, etc`, mientras que los archivos de código php deben estar en la carpeta `Sites`.

**Comment by rociomartineza** [comment]
Hola, estoy tratando de ejecutar el comando  

\COPY artistas from 'Entrega2/Artistas.csv' DELIMITER ',' CSV HEADER

para poblar la tabla de artistas. Me sale este error

ERROR:  missing data for column "nombre"
CONTEXT:  COPY artistas, line 2: ""

El archivo si tiene la informacion de todos los nombres y no se como solucionarlo

**Comment by ariela1** [comment]
Al usar el comando /COPY tenemos este error:
ERROR:  unquoted carriage return found in data
HINT:  Use quoted CSV field to represent carriage return.
CONTEXT:  COPY usuario, line 2

En internet sale que se puede arreglar con combiar el encoding a UTF-8, pero lo probamos y no  funcionó, tambien probamos con agregar encoding 'latin1' al comando al importar los datos pero tampoco

**Comment by nivek0o0** [comment]
The file you linked doesn't appear to have CR-LF line endings, however I suspect that could potentially be an issue since you're coming from a Windows host. You might try removing carriage returns using sed:
`sed -i 's/\r//' usuarios.csv`

Lo probé con tus usuarios, y pude importar correctamente el archivo usuarios2.csv.
