### ISSUE TITLE
Esquema relacional

### ISSUE THREAD

**Issue by veneguitas** [IIC2413/Syllabus-2020-1#125]
Hola! Estoy algo confundida con lo del esquema relacional de la parte 2.1 de la segunda entrega del proyecto. ¿Qué debo hacer específicamente al pasar del modelo relacional al esquema relacional? Entiendo lo que es el modelo, pero el esquema no.

**Comment by ridiazcampos** [comment]
¡Holaaaa! El esquema relacional que se pide para esta entrega puede ser realizado a partir de su Modelo Entidad Relación :D 

* ¿Qué es igual? Se incluyen las **entidades** del modelo y sus **relaciones** (incluyendo los _IsA_ que indican las **subtablas** :D).

* ¿Qué es distinto? En este esquema la idea es agregar los **tipos de atributo (_datatypes_)**, mostrar explícitamente cuáles atributos son **llaves foráneas (_FK_)** y/o **primarias (_PK_)**. Este se puede realizar a partir de "cuadros" que representen a **cada tabla** de su base de datos por ejemplo, incluyendo aquellas que correspondan a relaciones entre dos entidades (teniendo cuidado en solo incluir aquellas que efectivamente necesiten una tabla separada, pueden revisar la issue #100 para más información 😄).

Hay varios diseños de esquemas relacionales que pueden encontrar! Lo importante es que incluyan los requisitos especificados en el enunciado :D

¡Saludos! Y cualquier cosa nos comentan!

**Comment by Paldana99** [comment]
Consulta, en el esquema como se representan las llaves foraneas? Porque las primary key es surlineando, pero aca hay que decirle igual de cual depende no?

**Comment by nivek0o0** [comment]
> en el esquema como se representan las llaves foraneas? Porque las primary key es surlineando, pero aca hay que decirle igual de cual depende no?

Si el nombre de ese atributo que ocuparás es único en la BD, entonces simplemente ocupas el mismo nombre y agregas FK en el esquema. Por ejemplo: `Ciudades(cid int PK, nombre varchar(255), pid: int FK)`. Por lo que sabremos inmediatamente en qué tabla está `pid`.

Ahora, si utilizas el mismo atributo en varias tablas, por ejemplo "id", podrías hacer esto: `Ciudades(id int PK, nombre varchar(255), pid: int FK(Paises.id))`

La notación da un poco lo mismo, lo importante es que se entienda.
