### ISSUE TITLE
Duda SubClases Modelo E/R

### ISSUE THREAD

**Issue by mscuturrufo** [IIC2413/Syllabus-2020-1#126]
Si tengo una entidad "Alimentos" y tengo dos tipos "Perecible" y "No Perecible", en donde el ultimo tiene como atributo adicional la fecha de vencimiento, ¿Es correcto crear dos subclases con los nombres "AlimentosPerecible" y "AlimentosNoPerecible" en donde solo el ultimo grupo tenga el atributo adicional vencimiento. Esto para que algunas consultas sean más fáciles de realizar, como por ejemplo, seleccionar solo los alimentos perecibles.

Adjunto un ejemplo de lo que intento explicar.
![ejemplobases](https://user-images.githubusercontent.com/48365013/79033051-1b72f780-7b79-11ea-95a0-173fef5f58b3.PNG)

**Comment by nbnavarro** [comment]
Hola!

Lo que planteas es correcto! aunque también lo sería si es que solo creas la subclase de los no perecibles. Lo importante es que, al momento de hacer las consultas, tengas presente tu modelación y seas consistente con ella. 

Éxito!
