### ISSUE TITLE
Duda parte entrega 2.2 proyecto

### ISSUE THREAD

**Issue by amaiajuanchuto** [IIC2413/Syllabus-2020-1#128]
Para justificar el modelo simplemente tengo que pasar mis tablas creadas al estilo de dependencia funcional así:
llave de mi tabla --> otros atributos de mi tabla
O tengo que hacer otro análisis para justificar que mi modelo está en BCNF o 3NF? No me quedó claro cómo puedo demostrar que mis tablas cumplen con eso. Muchas gracias!! 😄

**Comment by nivek0o0** [comment]
Hola,

además de escribir las dependencias funcionales de cada taba, debes justificar por qué crees que esa es la dependencia correcta en base a supuestos sobre el problema.

Por ejemplo: _Suponemos que se pueden tener 2 destinos entre las mismas ciudades a la misma hora y en el mismo medio de transporte, pero con precios distintos. Por lo tanto, el precio no depende transitivamente de esos atributos y solo depende del ID_

**Comment by amaiajuanchuto** [comment]
Ya entendí, muchas gracias!
