### ISSUE TITLE
Bases de Datos a usar en la E2!!

### ISSUE THREAD

**Issue by fnberrios** [IIC2413/Syllabus-2020-1#129]
Hola! Me gustaría saber si ¿es necesario crear una bases de datos diferente para la entrega 2? y ¿esta base de datos estaría dentro de la bases de datos grupoXX? me confunde un poco eso. Tendría que ejecutar en la terminal algo como: CREATE DATABASE entrega2; y en esa nueva bases crear las tablas de mi modelo ¿no? Esto con la finalidad de que puedan revisar las entregas sin que las modifiquemos ¿no?
![data](https://user-images.githubusercontent.com/34272957/79052410-5110f280-7c04-11ea-9ee7-aa7c701e77dd.PNG)
En el caso de la imagen anterior, si soy del grupo 30, ¿debería crear las tablas en la base de datos llamada grupo30e2?

**Comment by ridiazcampos** [comment]
¡Holaaaaaa! Para esta entrega al menos no sería necesario crear una base de datos nueva 😄 En este caso la idea sería trabajar en _grupoXXe2_ que fue creada para cada grupito.

Para ingresar a esta base de datos especial de la entrega, una vez dentro del servidor pueden utilizar el comando:
`psql grupoXXe2`

Entonces ahí mismo podrían crear las tablas que corresponden para esta parte del proyecto sin necesidad de crear una nueva :D Y efectivamente eso será súper útil para "congelar" estas bases de datos y que se pueda seguir avanzando en entregas futuras (':

¡Esooo! Estaremos antent-s a cualquier dudaaaa.

Salu2 cordiales😊

**Comment by nivek0o0** [comment]
Para complementar, una vez dentro de la consola de psql puedes usar `\c grupoXXe2` para cambiarte de database.

Esto podría ser útil si ya tienes todo hecho en una base de datos incorrecta y deseas copiar las tablas de un lado a otro.
