### ISSUE TITLE
Git y Servidor

### ISSUE THREAD

**Issue by tomasalvarez13** [IIC2413/Syllabus-2020-1#13]
Hola, cuando hago git pull desde el servidor, a veces me se me abre nano pidiendo que escriba un mensaje para el 'merge'. Queria preguntar que es el merge y si esta bien que me aparezca.
Gracias

**Comment by jmndoza** [comment]
Hola @tomasalvarez13 ,
sera [este](https://stackoverflow.com/questions/32969967/merge-branch-master-cant-git-pull) tu problema?

**Comment by tomasalvarez13** [comment]
Si, eso mismo. Pero esta bien que aparezca? Porque en la ayudantia, nunca apareció.

**Comment by nivek0o0** [comment]
Lo que te pasó no es un problema, es la forma que tiene git de resolver una situación particular, que consiste en que tienes cambios sin commitear en el repo local y estas haciendo `git pull` para traer cambios del repositorio remoto.

Si no has creado nada en el repositorio local (servidor) entonces podrían ser los archivos ocultos del servidor que están molestando. Te sugiero agregarlos al `.gitignore` como puse en el Tutorial de la wiki.

Si quieres que no vuelva a ocurrir, debes asegurarte que no tienes ningún archivo sin commitear (es decir, ningún archivo en rojo al hacer `git status`) y luego hacer `git pull` de forma limpia. Si te vuelve a suceder, basta con escribir el mensaje del merge (Ctrl+O) y luego `git push`.

**Comment by tomasalvarez13** [comment]
Ok muchas gracias
