### ISSUE TITLE
Datatype entrega 2: ¿varchar o text?

### ISSUE THREAD

**Issue by VicenteElCyrano** [IIC2413/Syllabus-2020-1#132]
importa si el datatype de algún atributo es Varchar o string?
Afecta en la evaluación?

**Comment by nivek0o0** [comment]
Voy a suponer que te refieres a TEXT, porque STRING no existe en Postgres. 

La respuesta es **no**, no se evaluará si los textos son VARCHAR o TEXT, pero sí que las fechas, horas y momentos tengan el datatype adecuado.
