### ISSUE TITLE
Destinos y nulls

### ISSUE THREAD

**Issue by agustin-rios** [IIC2413/Syllabus-2020-1#133]
Hola! Me gustaria saber que se puede hacer con aqullas filas donde aparecen null en la columna de tipo Date o primary key ya que estos no permiten que se les ingrese un null. Se pueden eliminar o yo les doy un valor aleatorio?

**Comment by agustin-rios** [comment]
Un ejemplo de esto es alfinal de la tabla de destinos donde aparecen en la columna de fechaviaje donde no hay nada

**Comment by nivek0o0** [comment]
Hola

Sus tablas **no pueden quedar con NULLs**. El problema debe estar correctamente modelado para evitarlos.

Respecto a los destinos que mencionas, son simplemente destinos que no tienen tickets asociados, pero que de todas formas deben considerar.

**Comment by JupaOlivares** [comment]
A que se refieren con que hay que considerarlos?
