### ISSUE TITLE
Copiar bases de datos

### ISSUE THREAD

**Issue by fjcroquevielle** [IIC2413/Syllabus-2020-1#134]
Hola, tengo una duda respecto dos temas. En primer  lugar me equivoque y cree mis tablas en la bases de datos principal, es decir en grupo20, envés de crear una nueva base de datos grupo20e2, ¿podría cambiar el nombre de mi base de datos y solucionarlo?.
En según lugar, al tratar de importar mis datos desde mi tablas .csv (las que yo modifique de las entregadas) me tira un error en cada intento por importar cada tabla, este es: "ERROR: invalid byte sáquense for encoding "UTF8": 0x93", ¿saben a que se debe y como podría solucionarlo?.

**Comment by nivek0o0** [comment]
Hola, no puedes cambiar el nombre de la DB. Lo que sí puedes hacer es utilizar el comando **pg_dump** para descargar la base `grupo20` y cargarla en `grupo20e2`. Este comando se utiliza en la terminar del servidor (ubuntu). En la documentación aparece cómo utilizarlo.

Respecto al error, este ya se respondió en la issue #124. 

Les pido que por favor lean las issues antiguas antes de publicar dudas. De lo contrario solo se genera spam y luego dificultan la búsqueda de información de sus compañeros.
