### ISSUE TITLE
2.1 Entrega 2

### ISSUE THREAD

**Issue by Tomas-Ira** [IIC2413/Syllabus-2020-1#135]
Hola, tengo un problema. No entiendo que tengo que hacer en la parte 2.1. 

¿Hay que "repetir" el modelo de la entrega 1? En ese caso, a que se refiere con ilustrar entidades, asociaciones y cardinalidades?

Y después, dibujar el esquema relacional? En ese caso, ¿cómo se representan las llaves foráneas y las restricciones? (¿Adentro del círculo amarillo?) O se refiere a que tengo que escribir el código que crea las tablas?

![image](https://user-images.githubusercontent.com/42189004/79077019-24c0a900-7ccc-11ea-8065-88fbff33bdb9.png)

**Comment by nivek0o0** [comment]
Hola, primero te recomiendo leer las issues anteriores donde se ha explicado lo que se debe hacer en este apartado.

En resumen, queremos que hagan un diagrama E/R como el de la diapositiva n° 10 de la clase 07, sin olvidar las Subclases (IsA) que aparecen más abajo en esa misma clase (de ser necesario en su enunciado). [Aquí](https://es.wikipedia.org/wiki/Modelo_entidad-relaci%C3%B3n) se explica lo de las cardinalidades.

Luego, que transformen ese diagrama a un esquema relacional, que corresponde al conjunto de tablas que se crearán finalmente en la BD. Deben agregar nombre+atributos+datatypes+PKs+FKs de las tablas. La forma de hacer este modelo relacional depende de ustedes, pueden usar el típico diagrama de tablitas (como se muestra [aquí](https://soloesciencia.com/2017/08/04/911/) donde dice **modelo relacional**) o algo más simple como:
```
Ciudad(cid int PK, nombre varchar, pid int FK)
Pais(pid int PK, nombre varchar)
```
Esta forma es muy similar al comando utilizado para crear las tablas en Postgres. He repetido infinitas veces que para marcar las llaves foráneas pueden agregar "FK" (o cualquier forma que se entienda).
