### ISSUE TITLE
Importar datos con utf-8

### ISSUE THREAD

**Issue by jbulness** [IIC2413/Syllabus-2020-1#136]
Hola! Quería saber si es que sql permite ingresar datos en formato utf-8, ya que trato de importar los archivos que tengo que están en ese formato y me arroja un error relacionado a esto, y estuve googleando y no encontré nada relacionado a que haya que poner un ENCODING UTF8 al momento de hacer COPY. Si es que existe un problema con sql y utf8 que debo hacer? o existe un comando para que acepte utf8? Muchas gracias!

**Comment by nivek0o0** [comment]
#124
