### ISSUE TITLE
Justificación BCNF en Tablas Intermedias

### ISSUE THREAD

**Issue by matioprts** [IIC2413/Syllabus-2020-1#137]
Hola!
Tengo una duda respecto a si es necesario representar la dependencia en una tabla intermedia para justificar el BCNF, considerando que mi tabla intermedia es para una relación N:M, donde contengo 2 datos, id1, id2, su tupla es PK y cada uno es FK. De ser necesario mostrar la dependencia, no visualizo como escribir la dependencia de id1 con id2, ya que sería una PK dependiendo de otra PK.

**Comment by nivek0o0** [comment]
Hola, no es necesario justificar la dependencia en tablas intermedias como las que mencionas. 

Asumiremos que ya están normalizadas. De hecho lo están porque al no tener atributos no primarios cumplen todas las formas normales. Es el caso borde.
