### ISSUE TITLE
Dependiencia transitiva en tabla Países.

### ISSUE THREAD

**Issue by shantifabri** [IIC2413/Syllabus-2020-1#138]
Hola, nos entró la duda respecto a las dependencias para justificar BCNF o 3NF.
Si por ejemplo, tengo la tabla `Paises (pid: int PK, pnombre: varchar(255), pcontacto: varchar(255))`, se que una dependencia es `pid -> pnombre, pcontacto`, pero también existe la dependencia `pnombre -> pcontacto`. Entonces no sabemos si la tabla cumple o no con la norma porque en este caso tanto pid y pnombre son candidatas a llave primaria, pero pid es más fácil de manejar después en consultas y ocupa menos memoria si lo pongo en otras tablas. ¿Podemos dejarlo así y justificar con lo último?

**Comment by nivek0o0** [comment]
> en este caso tanto pid y pnombre son candidatas a llave primaria

Esto es correcto, ya que no hay 2 países en el mundo con el mismo nombre. 

Lo que en realidad está pasando aquí es que estamos tratando de condensar 2 entidades en 1 sola: países (su id y nombre) y callcenter de la agencia (su teléfono). (Asumiendo 1 agencia por país). Esto claramente está mal modelado.

**Pero** dado que no nos interesa guardar información de la agencia, **no** les pediremos una tabla para ella. Entonces, el argumento anterior y el tema de la eficiencia de utilizar IDs **sí justifica** dejar esta dependencia transitiva.

Otra opción es utilizar el nombre como pkey y se olvidan del tema. Lo importante es que aprendan que en esta base de datos pequeña no veremos el impacto en eficiencia, pero en una BD gigante, donde cada milisegundo cuenta, se vuelve muy relevante.

**Comment by shantifabri** [comment]
> Lo que en realidad está pasando aquí es que estamos tratando de condensar 2 entidades en 1 sola: países (su id y nombre) y callcenter de la agencia (su teléfono). (Asumiendo 1 agencia por país). Esto claramente está mal modelado.

¿En este caso como sería correcto modelarlo? No entiendo porqué estaría mal así para este ejemplo en especifico, ya que lo único que existe de la agencia es el contacto relacionado al país y se entiende que éste es único y existente para todos los paises (entiendo si no fuera el caso).

**Comment by nivek0o0** [comment]
Está mal modelado porque hay una dependencia transitiva que ustedes descubrieron. Lo correcto sería separar las entidades, sin importar que tengan 1 solo atributo.

Pero insisto, para este caso no es necesario hacer eso. No nos fijaremos en esto al corregir.

**Comment by shantifabri** [comment]
Aa entiendo.
Me imagino que lo mismo aplica para el resto de las entidades ¿o hay alguna excepción?
