### ISSUE TITLE
Herramienta donde hacer diagrama E/R

### ISSUE THREAD

**Issue by danustilovsky** [IIC2413/Syllabus-2020-1#139]
Hola, hay alguna app o pagina hacer los diagramas de entidad relacion? Estaba tratando en Visio pero no tiene el IsA por ejemplo. Existe alguno que recomienden?

Gracias

**Comment by nivek0o0** [comment]
Hola, nunca he utilizado Visio, ¿pero no puedes hacer un triángulo y rotarlo? O importar un conjunto de figuras relacionadas con bases de datos? (o geometría para el triángulo). 

A mi me gusta Lucidchart, que es una herramienta online colaborativa con una buena biblioteca de figuras.
