### ISSUE TITLE
Duda operador selección

### ISSUE THREAD

**Issue by ShescBlank** [IIC2413/Syllabus-2020-1#14]
Hola :D 
Se pueden utilizar operadores matemáticos sobre **Int** para la condición al filtrar? Como por ej: precio*cantidad > 1000

Muchas gracias!

**Comment by fjlopez7** [comment]
Si se pueden utilizar operadores matemáticos sobre Int.
En el caso que quieres operar con varios atributos, deben cumplir con que todos sean Int.

Si quieres ver que se cumple la propiedad, ejecuta la consulta:
 σ aid*pid=2 (Actuo_en)
en [Relax](https://dbis-uibk.github.io/relax/calc.htm?data=gist:6de6266bb2fea2b082a58c884d0069c6)

**Comment by aalmuna** [comment]
Muchas gracias!
