### ISSUE TITLE
Cambiar tipo de dato de una columna

### ISSUE THREAD

**Issue by pelao97** [IIC2413/Syllabus-2020-1#141]
Hola estaba tratando de cambiar mi tipo de datos, con el siguiente codigo:
 ALTER TABLE Iglesia ALTER COLUMN hora_apertura TIME;

Pero esto me arroja un error, syntax error at or near TIME,

Busque en internet cual era la estructura, pero no logro que me funcione. 
Cualquier ayuda es bienevenida
Gracias!

**Comment by juanreutter** [comment]
Hola, creo que postgres demanda que le pongan un  

ALTER TABLE Iglesia ALTER COLUMN hora_apertura TYPE TIME 

o algo parecido. Si no te funciona ese, busca en internet el comando específico para postgres (varias veces los sistemas tienen formas ligeramente distintas de hacer cosas) y postealo aquí porfa!.
