### ISSUE TITLE
Ruta relativa commando COPY

### ISSUE THREAD

**Issue by ngermani** [IIC2413/Syllabus-2020-1#142]
Quiero importar datos en la base de datos. Primero subé mis archivos csv en una carpeta CSV dentro de una carpeta entrega2 dentro de mi carpeta de usuario
  ![image](https://user-images.githubusercontent.com/62521654/79153467-e5fa2400-7d9b-11ea-823a-f3154c6c0b12.png)

Despues uso el comando COPY como indicado en la wiki pero no encuentra mi archivo CSV. Por qué tengo este error?
![image](https://user-images.githubusercontent.com/62521654/79153594-19d54980-7d9c-11ea-82a8-345676abd019.png)

Gracias!

**Comment by mfocqueteau** [comment]
Ya estas en la carpeta csv, por lo que solo tienes que poner `from Plazas.csv` y debería encontrarlo. Sino, prueba tambien con `from ./Plazas.csv`

**Comment by ngermani** [comment]
Funcionó! gracias!

**Comment by pwillmer** [comment]
Hola tengo un error similar!

![image](https://user-images.githubusercontent.com/53840038/79674018-2c40f000-81ad-11ea-83e5-c3f65c508acc.png)

**Comment by nivek0o0** [comment]
El problema no es la ruta relativa del archivo, sino que en tu base **grupo87e2** no hay ninguna tabla creada.
