### ISSUE TITLE
Duda Consulta 6 Dinero Gastado

### ISSUE THREAD

**Issue by gachondoj** [IIC2413/Syllabus-2020-1#143]
Hola
Para la consulta 6 hay que calcular la cantidad de plata gastada por un usuario entre 2 fechas. Para esto, las reservas se pagan al momento de ingresar o a la salida?

**Comment by nivek0o0** [comment]
Hola, la consulta 6 pide el dinero gastado en **tickets**, por lo que las reservas de hoteles no tienen nada que ver.
