### ISSUE TITLE
ID para las ciudades

### ISSUE THREAD

**Issue by PapayaManco** [IIC2413/Syllabus-2020-1#144]
En una issue anterior #117  se dijo que las ciudades no eran únicas, ya que podrían estar en distintos países, por lo que se nos recomendó usar ID para estas. Y nosotros teníamos pensado en convertir la Pero en el archivo tickets-destinos.csv nos dan solo nombres de ciudades, por lo que no tendríamos forma de relacionar tal ID con la ciudad de la tabla o el país al cual pertenece ésta. ¿Cual seria la forma correcta de relacionarlas? ya que con la información dada se podría asumir que las ciudades no se repiten. Y teníamos la idea de hacer una tabla con una ID de origen y una ID de destino.

**Comment by nivek0o0** [comment]
Puedes simplemente asignarle un ID del 1 a N a cada ciudad. Luego en otros lugares donde aparezca el nombre pones el número y listo.

**Comment by sebaav12** [comment]
Me quedo una duda, si tengo 2 ciudades que se llaman igual, pero con diferente pais, luego, según lo anterior nosotros debiésemos asignarle un id diferente a cada ciudad. Por otra parte en lo archivos tickets-destinos.csv y usuarios-reservas-hoteles.csv solamente nos indican la ciudad correspondiente, entonces, como podrimos afirmar que esa ciudad corresponde a un idciudad = n si no conocemos el pais?

**Comment by nivek0o0** [comment]
Para evitar la ambigüedad que planteas es que no hay ciudades con el mismo nombre y distinto país. Por lo que en este proyecto no deben preocuparse y pueden asignarles fácilmente un ID.

Si quisiéramos evaluar ese caso de uso tendríamos que haberles entregados los datos con (ciudad,país) siempre juntos o bien los países con Id.
