### ISSUE TITLE
Datatype para el año de las obras

### ISSUE THREAD

**Issue by mfocqueteau** [IIC2413/Syllabus-2020-1#145]
Hola! Las fechas de la obras están sólo por año y cuando trato de meterlas a la tabla, no me deja porque no lo reconoce como un formato correcto de dato tipo `date`. ¿Debería trabajar estas fechas como `int` o hay una forma correcta de agregarlos como date?

**Comment by nivek0o0** [comment]
(Aquí)[https://dba.stackexchange.com/questions/99207/postgresql-column-for-year] se mencionan 2 formas. Consideraremos ambas como correctas.
