### ISSUE TITLE
Primary key para Artistas

### ISSUE THREAD

**Issue by tsgonzalez** [IIC2413/Syllabus-2020-1#146]
Cuando hay eventos que son muy poco probables, debo asumir que pueden pasar igual?? 

Por ejemplo, puede pasar que dos artistas se llamen igual, nazcan el mismo día y fallezcan el mismo día. Pero en la práctica, es imposible. 

Mi pregunta es si debo tener más en cuenta el sentido común (que sería: dado un nombre, fecha de nacimiento y de fallecimiento, conozco a la persona) o si me debo limitar a las cosas posibles en vez de las cosas probables, y simplemente agregar un id que me diferencie estos casos extremos. (porque hay varios casos de este estilo: otro sería que hayan dos ciudades con el mismo nombre en el mismo país, por ej).

**Comment by nivek0o0** [comment]
Como consejo para la vida, sí, deberías prepararte para los eventos poco probables, porque si llegan a ocurrir destruirán tu base de datos y tus consultas.

Por eso siempre es mejor utilizar como PK un ID. Además es más eficiente.
