### ISSUE TITLE
Conexión remota a la base de datos

### ISSUE THREAD

**Issue by rodobkn** [IIC2413/Syllabus-2020-1#147]
Hola!

Estaba viendo por internet una forma de poder crear las tablas, e insertar los datos desde python. Es más, hasta un amigo que ya hizo el ramo me dijo que se lo enseñaron en las actividades con este mismo método, en el cual usan "psycopg2".

Y al parecer no me puedo conectar al servidor con esos parametros:

![base_datos_1](https://user-images.githubusercontent.com/53799163/79172277-42703a00-7dc2-11ea-9c46-eaf6214e857b.PNG)

Y me tira este error:
![base_datos_2](https://user-images.githubusercontent.com/53799163/79172369-86fbd580-7dc2-11ea-98f5-5a9706aec623.PNG)

Espero que me puedan ayudar.

gracias!

**Comment by nivek0o0** [comment]
Hola, sucede que el puerto 5432 está bloqueado por seguridad. Ya le escribí al encargado en el DCC para que lo habilite. Avisaré en esta issue cuando eso ocurra.
