### ISSUE TITLE
Como importar fecha de Artistas

### ISSUE THREAD

**Issue by benito-tondreaux** [IIC2413/Syllabus-2020-1#149]
Hola! 

Al ejecutar el comando COPY para importar los datos csv, me indica un error "datastyle" en la fecha.

![IMG-1300](https://user-images.githubusercontent.com/53802150/79193948-a3673480-7df9-11ea-859e-798953710cdb.jpg)

En el csv las fechas están escritas así: "1431-09-13"

**Comment by nivek0o0** [comment]
#116
