### ISSUE TITLE
Duda sobre valores nulos en tablas

### ISSUE THREAD

**Issue by jacouyoumdjian** [IIC2413/Syllabus-2020-1#15]
Hola!
 
Tenemos la siguiente duda: pueden existir instancias dentro una tabla que tengan atributos con un valor nulo o todas deben tener un valor distinto de cero? 

Nos surge la duda porque tenemos casos en que no sabemos si crear otra tabla auxiliar para evitar estos valores nulos. Por ejemplo, con los lugares de las obras de arte, en que algunos  tienen un precio de entrada asociado y otros no. Gracias!

Saludos,

Joaquín C.

**Comment by nivek0o0** [comment]
Hola,
**no pueden** diseñar su esquema tal que para ciertas entidades (p.e. iglesias) un atributo sea siempre NULL.

Tienen que pensar en una forma de resolver esta situación: que algunas entidades sean del mismo tipo ("lugares") pero que difieran en sus atributos (museos, iglesias, etc)

**Comment by carajila** [comment]
Hola!

¿Es válido como atributo para una plaza por ejemplo, que no tiene horario de apertura ni de cierre, se le asigne, hora_apertura = "00:00:00", hora_cierre = "23:59:59" y costo = 0?

**Comment by nivek0o0** [comment]
Hola, 

Eso no es válido, ya que es justo la mala práctica cuando tienes entidades con distintos atributos y quieres guardarlas todas juntas. 

Las plazas simplemente no deberían tener esos atributos. Al igual que las Iglesias no deberían tener precio.

**Comment by Fernan-tess** [comment]
Respecto a esto, si tengo atributos que son binarios (onda 0 y 1) es válido?

**Comment by nivek0o0** [comment]
¿Para qué ocuparías ese atributo binario?

**Comment by Fernan-tess** [comment]
Por ejemplo, para ver si dos ciudades se conectan por tren. 1 si sí, 0 si no,

**Comment by nivek0o0** [comment]
Pero eso no necesitas guardarlo así en la BD. Para ese caso tendrás (o no) una fila en la tabla Destinos que vaya entre esas dos ciudades y cuyo medio de transporte sea tren.

**Comment by Fernan-tess** [comment]
Entonces, asumo que todas las ciudades se conectan solo por un medio de transporte?

**Comment by Fernan-tess** [comment]
Ya caché, gracias :)
