### ISSUE TITLE
Reservas como entidad o como tabla intermedia?

### ISSUE THREAD

**Issue by matumartinez** [IIC2413/Syllabus-2020-1#150]
Hola!

Tengo una tabla intermedia "reservas" que relaciona a usuarios y hoteles, por lo que puse al id del usuario y del hotel como primary keys, pero me acabo de percatar de que un usuario podría tener más de una reserva en el mismo hotel. ¿Es factible dejar los id de usuario y hotel como foreign keys y que la tabla intermedia tenga su primary key id propio?

**Comment by arpincheira** [comment]
Hola, 
en el caso de que tu "tabla intermedia" requiera más atributos... como por ejemplo fecha de inicio de la reserva o fecha de término de esta no convendría que la consideraras como una entidad dentro de tu trabajo? Digo esto principalmente porque efectivamente podrías crear un id de reserva y hacer lo que dices, pero no te debes olvidar de añadir ciertos atributos que esta puede contener.
Adicionalmente debo hacer énfasis en lo que viene siendo  el como modelarás el problema y que deberías tratar de lograr que tu modelo esté en BCNF.

Espero haberte ayudado.
