### ISSUE TITLE
Artistas y obras

### ISSUE THREAD

**Issue by juansjimenez** [IIC2413/Syllabus-2020-1#151]
Hola! Podemos asumr que cada obra estará hecha por solo un artista?
Gracias!

**Comment by arpincheira** [comment]
Hola, 
parte de esto se respondió en la issue #111 para que la pases a ver, ahí se habla de las distintas consideraciones a tomar con respecto a las obras de arte. 

Espero haberte ayudado.

**Comment by juansjimenez** [comment]
Gracias!
