### ISSUE TITLE
Datos actualizados

### ISSUE THREAD

**Issue by danustilovsky** [IIC2413/Syllabus-2020-1#152]
Hola, con mi compañero estabamos revisando el csv y al abrirlo nos dimos cuenta que nos aparecen cosas diferentes. Para mi la linea 5 termina con  en la misma ciudad;;;;;;;;;;; mientras que para el la linea tiene mas cosas. Porque puede pasar eso?

**Comment by arpincheira** [comment]
Hola, 
puede que eso se deba a una actualización que se hizo a los datos de los archivos csv que puede haber sido hace aproximadamente 10 días, les recomendaría actualizar sus archivos con la última versión encontrada en el repositorio del proyecto.

Espero que les sirva.

**Comment by juansjimenez** [comment]
Hola. Yo utilize los datos "viejos" e hice gran parte de la entrega con esos (dehecho ya termine). Nunca avisaron a mi parecer que habian cambiado los datos! Debo entonces hacer todo denuevo?

**Comment by arpincheira** [comment]
Hola, tanto los datos de usuarios pares como impares fueron actualizados hace 10 días, los casos de prueba para corregir la tarea van a ser con esos datos, por lo que deben utilizar la versión actualizada de estos.
En tu caso específico debes haber creado una función de pre-procesamiento de los datos, por lo que debes usarla en los datos nuevos y repoblar tu base de datos con estos. 
Saludos

**Comment by arpincheira** [comment]
Adicionalmente, las issues son un canal de comunicación oficial y en la issue #102 se avisó que los datos fueron cambiados para arreglar los errores que contenían los anteriores.

**Comment by juansjimenez** [comment]
Ok muchas gracias.
