### ISSUE TITLE
Tengo problemas al crear una tabla

### ISSUE THREAD

**Issue by Alonsinho1** [IIC2413/Syllabus-2020-1#153]
Hola estoy tratando se crear la tabla esculturaes que tiene dos llaves foraneas una es el aid de los artistas y la otra es el nombre del lugar. Estas son sacadas de las tablar artistas y de lugares respctivamentes.

Estoy tratando de correr el siguiente codigo:

`CREATE TABLE esculturas(nombreobra text, ano_inicio text, ano_termino text, periodo text, material text, aid int, nombrelugar text, PRIMARY KEY(nombreobra,ano_inicio,ano_termino), FOREIGN KEY(aid) REFERENCES artistas(aid), FOREIGN KEY(nombrelugar) REFERENCES lugares(nombrelugar));`

y me arroja el siguiente error:

`there is no unique constraint matching given keys for referenced table "lugares"`

Como puedo solucionar esto?

**Comment by Alonsinho1** [comment]
lo solucione

**Comment by nivek0o0** [comment]
Te sugiero utiliza IDs numéricos como llaves primarias de tus tablas :zany_face:
