### ISSUE TITLE
Relaciones débiles

### ISSUE THREAD

**Issue by juansjimenez** [IIC2413/Syllabus-2020-1#154]
Es necesario establecer si una relación es débil o no? Por ejemplo, ciudad en pais? O basta simplemente para esta entrega establecer las entidades con sus asociaciones y cardinalidades?

**Comment by arpincheira** [comment]
Hola, 
a decir verdad, no me queda muy claro tu ejemplo, de todos modos en términos generales siempre es bueno indicar si una entidad es débil o no. En todo caso _hint_ se supone que idealmente dentro de la moderación del proyecto, este está pensado para que no hayan entidades débiles. En todo caso, si encuentras que hay una debes justificar debidamente tu razonamiento en el informe, en una de esas se puede dar el caso de que logres demostrar que lo ideal es modelar algo así.
P.D.: Revisa bien la materia sobre entidades y relaciones débiles, en una de esas eso podría ayudarte a aclarar tu duda.
Espero haberte ayudado.
