### ISSUE TITLE
Problema al crear una llave foránea(no unique constraint)

### ISSUE THREAD

**Issue by Alonsinho1** [IIC2413/Syllabus-2020-1#155]
Hola ! estoy teniendo el siguiente problema, al crear mis tablas.

Escribire mi codigo seguido por el error que no se como arreglar :c 

```
CREATE TABLE pais(pais text, fono text, PRIMARY KEY(pais);

CREATE TABLE ciudades(ciudad text, pais text, PRIMARY KEY(ciudad,pais), FOREIGN KEY(pais) REFERENCES Pais(pais));

ALTER TABLE plazas ADD CONSTRAINT llave FOREIGN KEY(ciudad) REFERENCES ciudades(ciudad);

```

y el error que sale es

`there is no unique constraint matching given keys for referenced table "ciudades"`

Alguna forma de poder arreglar esto?

Muchas gracias :D!

**Comment by arpincheira** [comment]
Hola, 
lo primero que te tengo que decir es que tengas cuidado con el comando CREATE TABLE de la primera línea, le falta un paréntesis. Lo otro, tu error ocurre principalmente porque dentro de la tabla ciudades, no hay nada que certifique que el atributo ciudad sea único, por lo que no se puede hacer un referencia precisa al usar el comando de la tercera línea. En ese caso hay algunas soluciones:
- Hacer que ciudades tenga como primary key un id de ciudad y luego hacer referencia a ese id y no al nombre de la ciudad, adicionalmente esto evitaría darle dos primary keys como estás haciendo en tu ejemplo.
- Añadir a tu tabla un indicador "_unique_" que indique que ciudad es único, aunque solo te dejaría usar una vez cada nombre de ciudad.
- Poner como primary key solamente ciudad, pero ocurriría lo mismo que en el caso anterior.
- Hacer referencia a ciudad y país en tu tercera línea, lo que la verdad sería complicarse un poco a mi gusto.

Espero que logres decidir sabiamente y arreglar tu error, de no funcionar estas alternativas avisa por aquí.

Ojalá te haya podido ayudar con esto.

**Comment by Alonsinho1** [comment]
Muchas gracias entendi bien el problema!

Eso si trate de evitar el uso de ids en algunos casos para evitar redundancias. Esta bien la logica que si la llave primaria es solamente un id se pueden generar redundancia?

Que tan relevante es para la evaluación que las tablas no sean redundantes?

Con redundantes me refiero a lo que señalaba el profesor en los videos de la semana pasada

**Comment by nivek0o0** [comment]
Utilizar un ID no es generar redundancia, de hecho es todo lo contrario. Definitivamente es mejor que definir una llave compuesta con 2+ atributos, porque cuando necesites ponerla como llave foránea, sera solo un número y no una tremenda tupla.
