### ISSUE TITLE
Fecha fallecimiento

### ISSUE THREAD

**Issue by mpsubiabre** [IIC2413/Syllabus-2020-1#158]
Hola, 
me surgió una duda respecto a las fechas de fallecimiento.
Como se menciona en la issue #166 ,  no todos los artistas han fallecido, hicimos una entidad extra con el id del artista y su fecha de fallecimiento respectiva, por lo que no todos los artistas se encuentran en esta tabla(no han muerto todos) Como se agregaría esta relacion a el diagrama E/R?  ya que no es un 1-1

**Comment by nivek0o0** [comment]
En realidad sí es una relación 1:1, pero con algunos casos 1:0. Dado que la llave de artistas se posiciona como llave foránea en esta tabla, no habría problema alguno con los artistas vivos, ya que no estarían generando nulls.
