### ISSUE TITLE
Consulta 5 par

### ISSUE THREAD

**Issue by fcartoni** [IIC2413/Syllabus-2020-1#159]
Hola! En esta consulta piden la hora en formato hh:mm:ss, esto significa que esta parte no debe ser case sensitive? Porque también piden ingresar una ciudad y asumo que esa sí debe ser case sensitive. 
Otra pregunta que tengo es si se deben encontrar las iglesias que están abiertas exclusivamente en ese horario, o por ejemplo si tengo una iglesia abierta de 9:30 a 15.30 y el usuario escribe 8:00 a 19:00, entonces la primera también se debe incluir?
Gracias

**Comment by nivek0o0** [comment]
Hola

> En esta consulta piden la hora en formato hh:mm:ss, esto significa que esta parte no debe ser case sensitive

R: Los números son indiferentes a mayúsculas/minúsculas. Ingresaremos por ejemplo `10:30:00`

> También piden ingresar una ciudad y asumo que esa sí debe ser case sensitive.

R: ojo, la búsqueda de strings deben ser **case insensitive**, es decir, es equivalente buscar `roma` o `RoMa`

> se deben encontrar las iglesias que están abiertas exclusivamente en ese horario

R: se deben entregar aquellas iglesias que estén abiertas al menos 1 segundo entre las horas ingresadas, es decir, basta que estén abiertas un ratito. Distinto sería pedir que estuviesen completamente abiertas entre esas horas.

**Comment by danustilovsky** [comment]
Hola, las consultas aparte de ser case insensitive, deber obviar los tildes? por ejemplo belgica y BélGICA deben ser equivalentes?

**Comment by nivek0o0** [comment]
No, los tildes no deben obviarse.

Sólo les pedimos matching parcial y obviar las mayúsculas.

**Comment by lisraelrat1** [comment]
En esa misma consulta, que significa mostrar una fila por cada tupla? Feliz si me dan un ejemplo de una fila de output :)

**Comment by nivek0o0** [comment]
nombreIglesia | nombreFresco
-|-
Iglesia1 | Fresco1
Iglesia1 | Fresco2
Iglesia1 | Fresco3
Iglesia2 | Fresco6
Iglesia2 | Fresco7
Iglesia2 | Fresco8

donde `Iglesia1` e `Iglesia2` se encuentran en la **ciudad** ingresada y estuvieron abiertas en algún momento entre las horas de **apertura** y **cierre**.

**Comment by lisraelrat1** [comment]
Perfect muchas gracias! Eso mismo tenemos.

**Comment by shantifabri** [comment]
> R: se deben entregar aquellas iglesias que estén abiertas al menos 1 segundo entre las horas ingresadas, es decir, basta que estén abiertas un ratito. Distinto sería pedir que estuviesen completamente abiertas entre esas horas.

Con esto te refieres a que si el usuario ingresa por ejemplo 09:00:00 y 16:00:00, si una iglesia estuviera abierta de 15:59:00 a 19:00:00 tambien se incluye?

**Comment by nivek0o0** [comment]
Sí

**Comment by shantifabri** [comment]
Perfecto, gracias!

**Comment by JuaniAndres** [comment]
hola siempre el horario de apertura ingresado va a ser menor que el ingresado de cierre?
Por ejemplo puede ocurrir un caso que sea  23:00 hasta 15:00

**Comment by nivek0o0** [comment]
Para simplificar sí pueden asumir que en los parámetros horario de apertura < horario cierre.

No les vamos a pedir horarios de un día para otro.

**Comment by JuaniAndres** [comment]
genial gracias

**Comment by JuaniAndres** [comment]
Kevin una duda al revisar esta issues y el enunciado de la entrega que dice

> Ingrese una hora de apertura en formato hh:mm:ss, una hora de cierre y una ciudad.
Muestre los nombres de las iglesias ubicadas en esa ciudad, abiertas entre esas horas
(inclusive) junto a todos los nombres de los frescos que encuentra en cada una de ellas.

No debería ser que la iglesia este abierta durante todo el rango de los horarios ingresados y no solo un ratito?

**Comment by nivek0o0** [comment]
Si una iglesia X está abierta entre las 09:00 y las 18:00 y yo como usuario de tu aplicación te pido las iglesias abiertas entre las 06:00 y las 10:00 porque tengo ganas de visitar Frescos de madrugada. 

¿La iglesia X está abierta entre las horas que yo pedí? La respuesta es sí, pero con la condición de que solo durante 1 hora. En el enunciado no pedimos nada sobre esta condición así que da lo mismo.

¿Se entiende?

**Comment by JuaniAndres** [comment]
Te entiendo es que yo lo veía más como una totalidad al leerlo pero filo lo cambio 
Solo para quedar claro 
Horario iglesia 9:00-18:00
| Caso | Hora 1 | Hora 2 | Aparece la iglesia |
|------|--------|--------|--------------------|
| 1    | 6:00   | 10:00  | si                 |
| 2    | 10:00  | 15:00  | si                 |
| 3    | 15:00  | 20:00  | si                 |

Eso esta correcto?

**Comment by nivek0o0** [comment]
Sí, está correcto.

| Caso | Hora 1 | Hora 2 | Aparece la iglesia |
|------|--------|--------|--------------------|
|4|17:59:59|22:00|si|
| 5    | 18:00   | 22:00  | no                 |
| 6    | 06:00  | 9:00  | no                 |
| 7    | 06:00  | 20:00  | si                 |

**Comment by JuaniAndres** [comment]
ya genial me quedo todo mucho más claro muchas gracias
