### ISSUE TITLE
Problemas para conectarse al servidor

### ISSUE THREAD

**Issue by JuaniAndres** [IIC2413/Syllabus-2020-1#16]
Hola estaba tratando de conectarme siguiendo los pasos de la wiki usando la powershell pero cuando llego a poner la contraseña la consola no me deja escribir alguna idea de que puedo estar haciendo mal?

**Comment by arpincheira** [comment]
Hola, 
lo que probablemente sucede es que efectivamente estás escribiendo, pero por configuración del servidor, al momento de escribir no te aparece un "registro visual" de lo escrito. Es por esto que te recomiendo escribir tu contraseña en la consola para luego ingresarla aunque no puedas ver si escribiste algo.

Saludos

**Comment by JuaniAndres** [comment]
Buena si tenias razón gracias
