### ISSUE TITLE
Duda nombres distintos obras de arte

### ISSUE THREAD

**Issue by ngermani** [IIC2413/Syllabus-2020-1#160]
Tengo una duda para la primera consulta (grupos pares), que debe mostrar los nombres distintos de las obras.  
Son considerados los nombres "La anunciación" y "La Anunciación"  como nombres distintos?

Gracias!

**Comment by nivek0o0** [comment]
No, esos nombres son considerados como el mismo. En otras palabras, deben ignorar las minúsculas y mayúsculas. 

Como hint, podrían entregar todo en minúsculas ocupando la función lower() y filtrando duplicados.

Recuerden que los criterios de matching parcial y case insensitive son para los **parámetros ingresados**.

**Comment by danustilovsky** [comment]
Hola @nivek0o0, tengo una duda resoecto a esto. Existen varias obras con el mismo nombre, escrito con mayusculas y minusculas, pero todas creadas en diferentes años. Por lo tanto aunque sean diferentes obras se deben postrar una sola vez debido a la coincidencia de nombre?

**Comment by nivek0o0** [comment]
Sí, se deben mostrar 1 vez debido a la coincidencia de nombre, porque la consulta pide _los nombres distinto de las obras de arte_ y no _los nombres de las obras de arte distintas_.
