### ISSUE TITLE
Material esculturas en csv

### ISSUE THREAD

**Issue by danustilovsky** [IIC2413/Syllabus-2020-1#162]
Hola, dentro de las cosas que aparecen en el csv con los artistas y sus obras, uno de los materiales de una de las esculturas es : 'Flores [] (arreglos florales)'. Esta bien eso? o deberiamos quedarnos con solo un trozo de eso? y si es asi cual es el criterio para saber que hacer?

**Comment by nivek0o0** [comment]
Déjalo así nomás. El criterio es: si es un string/texto se deja tal cual.
