### ISSUE TITLE
Fecha fallecimiento Artistas

### ISSUE THREAD

**Issue by humbertoortuzar** [IIC2413/Syllabus-2020-1#163]
Hola, si dentro del csv entregado de artistas, considero que hay alguno que no existe, puedo hacer un supuesto de que era un error y eliminarlo de los datos? Por ejemplo, algún artista que se dice que falleció el 2100 (xd)

**Comment by nivek0o0** [comment]
Hola, no pueden eliminar ningún dato. Si lo hacen las consultas podrían entregar distintos resultados, en cuyo caso fallarían los casos de prueba.

Lo de la fecha 2100 se explicó en #116, son artistas que siguen vivos y deben modelar eso correctamente.
