### ISSUE TITLE
Llave primaria de Reservas

### ISSUE THREAD

**Issue by nico-mac** [IIC2413/Syllabus-2020-1#164]
El modelo que tenemos planeado consiste en usar llaves foraneas como llaves primarias. Por ejemplo,  para las Reservas queremos usar como llave primaria la fecha de entrada, junto con la llave del usuario y la llave del hotel. La llave del hotel y del usuario serían atributos y llaves foráneas.

Al hacer esto estariamos estableciendo relaciones en los atributos, pero ganaríamos las restricciones de no tener a un usuario, en un hotel, con 2 reservas al mismo dia, por ejemplo. Habría algún problema con hacerlo así? o debieramos agregar un id de reserva, una tabla que relacione reservas-usuarios, otra tabla que relacione reservas-hoteles y además perder las restricciones asociadas?

**Comment by nivek0o0** [comment]
Respecto a las tablas intermedias, estas nunca serán necesarias puesto que las relaciones **no** son N:M.

Para este caso que planteas, lo más correcto es utilizar un ID para la entidad Reserva, porque en ninguna parte del enunciado se dice que un usuario solo puede tener 1 reserva el mismo día en el mismo hotel. ¿Qué pasaría si alguien quiere hacer múltiples reservas que empiecen a la misma hora para los miembros de su familia?

**Comment by jhfh98** [comment]
Se puede entonces poner como atributo en una entidad una llave de otra entidad ? como es el caso descrito aquí.
