### ISSUE TITLE
Consultas anidadas postgresql y PHP

### ISSUE THREAD

**Issue by danustilovsky** [IIC2413/Syllabus-2020-1#165]
Hola, existe alguna forma en postgrsql de guardar las consultas intermedias para evitar tener tanto enredo de parentesis cuando se realizan las consultas anidadas? y lo mismo en PHP?

Gracias

**Comment by nivek0o0** [comment]
Con PHP siempre puedes manipular a tu gusto la ejecución y resultado de las consultas. Por ejemplo podrías hacer una consulta simple, y por cada resultado enviar más consultas y luego consolidar los resultados finales. Esta forma es bastante **ineficiente** porque una consulta tiene mucho overhead de conexión. Entonces hacer 1 gran consulta es mejor que hacer N.

La opción más bacán es crear un procedimiento almacenado en la base de datos misma. Es como una función que dejas guardada y luego puedes llamarla con parámetros. Esta materia creo que aún no la han visto así que es poco factible ahora.

Entonces, lo que te recomiendo es tratar de ordenar lo mejor posible la consulta en el archivo. Podrías definir un gran string utilizando bloques, tabulaciones, etc. Tambien podrías definir variables con los strings de las subconsultas y luego solo concatenas y ejecutas.

---------

Ahora, en la consola de postgres puedes utilizar Views, que son tablas temporales.
