### ISSUE TITLE
Duda tablas intermedias

### ISSUE THREAD

**Issue by diegomendieta** [IIC2413/Syllabus-2020-1#166]
Hola, en el caso de las ciudades, estas corresponden únicamente a un país. Entiendo que, en este caso, puedo agregar la id del país a la tabla de mis ciudades. En este caso, habría algún problema en crear una tabla intermedia que relacione ciudades y países? Sería esto mas correcto?

Gracias!

**Comment by mihenriquez** [comment]
Ambas opciones funcionan, sin embargo tu nueva tabla con ids de ciudades y países tendría las “mismas filas” que tu tabla ciudades (es decir una fila por cada ciudad) pero con la extensión del pid, por lo mismo pasa a ser innecesario crearla, y podría considerarse más eficiente agregar el pid a la tabla ciudades.

**Comment by diegomendieta** [comment]
Entonces lo agrego a la tabla ciudades. Gracias!
