### ISSUE TITLE
Duda id obras

### ISSUE THREAD

**Issue by diegomendieta** [IIC2413/Syllabus-2020-1#167]
Hola, en el enunciado de la E1 decía que una obra podía estar hecha por varios artistas. Considerando esto, cómo funcionaría la asignación de una id a cada obra? Esto debido a que podrían existir obras distintas con el mismo nombre, y otras entradas Obra con el mismo nombre y diferente artista que correspondan a la misma. En resumidas cuentas, mi duda es: cómo puedo diferenciar en la base de datos una obra de otra con el mismo nombre, sabiendo que existe la posibilidad de que hayan sido iniciadas y finalizadas en años iguales?

Gracias!

**Comment by nivek0o0** [comment]
Hola, la forma de diferenciar las obras ya se explicó en otra issue.
