### ISSUE TITLE
Copiar tablas desde otra database.

### ISSUE THREAD

**Issue by szabala** [IIC2413/Syllabus-2020-1#168]
Hola!
Mientras trabajaba el proyecto capte tarde que habia que crear y cargar las tablas en la database grupoXXe2 y no en grupoXX. Resulta que ya tengo todo listo en grupoXX y no he podido encontrar alguna manera de copiar todas las tablas de grupoXX en grupoXXe2. (Se menciono que se podia en la ayudantia pero no se dijo como 😢 ). Si alguien sabe como hacerlo, agradeceria mucho su ayuda, asi no tendria que volver a crear y cargar todas las tablas.

**Comment by nivek0o0** [comment]
En otra issue se explico como respaldar bases de datos.
