### ISSUE TITLE
Duda enunciado entrega 1 (Lugares)

### ISSUE THREAD

**Issue by JuaniAndres** [IIC2413/Syllabus-2020-1#17]
Hola en el enunciado en especifico la siguiente parte
![image](https://user-images.githubusercontent.com/48482216/77233835-006c2380-6b89-11ea-93d8-24bb3ab82e34.png)
Respecto a las ultimas lineas si o si tiene que estar el nombre de la ciudad en el esquema de la tabla de lugares o puede ser otro atributo como un id que me sirva para relacionar la información con otra tabla
Gracias de antemano

**Comment by nivek0o0** [comment]
Entre las opciones que mencionas, debes elegir la forma que minimice la redundancia de información en tu base de datos y reduzca las posibilidades de generar inconsistencias.
