### ISSUE TITLE
Username

### ISSUE THREAD

**Issue by raimundoloeser** [IIC2413/Syllabus-2020-1#170]
Hola,
Tenemos una duda con el uid que ustedes nos entregan, ya que existe el username el cual, por sentido comun, deberia ser unico (como en todas las cuentas que uno se crea) y nuestra base de datos se basa en que el username es unico y la primary key de esa tabla. Se puede trabajar solamente con el username? o debemos incluir el uid tambien (con esto ultimo, teniamos la duda de que no estaria bien ya que como username y uid son unicos, con ambos obtendriamos todos lod datos del usuario)

gracias de antemano

**Comment by nivek0o0** [comment]
Hola, deben incluir el uid porque algunas consultas lo utilizan.

Cualquiera de los 2 puede ser primary key.

No hay problema con tener 2 columnas únicas en una tabla.
