### ISSUE TITLE
Entrega dos primera consulta

### ISSUE THREAD

**Issue by lucas-valenzuela** [IIC2413/Syllabus-2020-1#171]
Hola! 
Para la consulta 1 tenemos que descplegar todas las obras con nombre distinto, pero no se especifica si también debe ser case sensitive. Estaría entonces correcto que se entregue "asuncion" y "Asuncion" como dos obras con nombres distintos?
Saludos!

**Comment by nivek0o0** [comment]
Hola, esto ya se respondió en una issue anterior.
