### ISSUE TITLE
Llaves foraneas en Modelo Entidad Relacion

### ISSUE THREAD

**Issue by martinrtc** [IIC2413/Syllabus-2020-1#172]
Hola, tengo una duda sobre el modelo entidad relacion.
Por ejemplo en mi entidad "Ciudad" tengo como atributo la llave foranea "pid" (indice del pais), tengo que ponerla en el modelo entidad relacion? Y siesque la respuesta es si, hay alguna forma específica de ponerla (como por ejemplo las primarias van subrayadas).
Muchas gracias.

**Comment by nivek0o0** [comment]
Hola, el modelo E/R no lleva llaves foráneas.
