### ISSUE TITLE
Duda sobre diagrama entidad/relacion

### ISSUE THREAD

**Issue by fsmc** [IIC2413/Syllabus-2020-1#173]
En el caso de obras de arte y artistas estos tienen cardinalidades n y m. Por lo que me gustaría saber si es necesario hacer una tabla intermedia que contenga el id de artista y el de sus obras. O hay alguna otra forma, como por ejemplo agregarle a las obras de arte una llave foranea que tenga el id del artista que la hizo.

Gracias!

**Comment by nivek0o0** [comment]
Hola, se ha repetido muchas veces en este foro que las tablas intermedias son necesarias cuando la cardinalidad es N:M.
