### ISSUE TITLE
Obras con mayúscula es distinta a una con minúscula?

### ISSUE THREAD

**Issue by VicenteEspinosa** [IIC2413/Syllabus-2020-1#174]
Hola, para la primera consulta de la parte par de la entrega 2 nos piden listar todos los nombre distintos de las obras de arte que hay. Pero hay algunas obras que son copias de otras, y tienen una letra en minúscula en vez de mayúscula, por ejemplo: La anunciación del año 1300, y La Anunciación del año 1472. Debería mostrar ambas obras en la lista o solo una? Por que al hacer unión quedan ambos pues no son exactamente el mismo nombre.
Saludos.

**Comment by nivek0o0** [comment]
Hola, esto ya fue respondido en issues anteriores
