### ISSUE TITLE
Input de las consultas en forma de Dropdown

### ISSUE THREAD

**Issue by benjastraub** [IIC2413/Syllabus-2020-1#175]
Hola, 

quería saber si necesariamente las consultas deben hacerse ingresando texto. 

Con mi compañero consideramos mejor hacer un _dropdown_ con las opciones (como en la imagen), pero nos entró la duda por el requerimiento de que las consultas sean _case insensitive_ y con _matching_ parcial.

![imagen](https://user-images.githubusercontent.com/30667727/79605857-aa729900-80be-11ea-9b05-e3b991481cf6.png)

**Comment by nivek0o0** [comment]
Hola, no pueden implementar un dropdown porque justamente estarían evitando esos requerimientos que queremos evaluar.

**Comment by aalmuna** [comment]
Hola :D entonces qué recomendarían hacer para las tildes? porque estaba investigando lo de hacerlo accent-insensitive. O lo dejamos que sea accent-sensitive?

**Comment by nivek0o0** [comment]
#182

**Comment by aalmuna** [comment]
oh muchas gracias! Disculpa se me fue esa issue :c
