### ISSUE TITLE
Explicitar largo de un Varchar

### ISSUE THREAD

**Issue by MGome** [IIC2413/Syllabus-2020-1#176]
Hola buenas,
Es necesario especificar el largo de la secuencia a utilizar en una respectiva columna varchar en el esquema relacional? (por ejemplo varchar(20))

**Comment by nivek0o0** [comment]
Para este proyecto no es necesario. No será evaluado.

Para la vida, en general se utiliza un largo fijo cuando quieres imponer una restricción de integridad. Por ejemplo, para que los números de teléfono tengan el mismo formato. En términos de rendimiento y memoria, depende del DBMS que estés usando, ya que cada uno lo implementa distinto.
