### ISSUE TITLE
Matching parcial solo para strings

### ISSUE THREAD

**Issue by F-arellano** [IIC2413/Syllabus-2020-1#177]
tengo dudas si tambien debería aplicarlo a las consultas que me piden id (consulta 4 impares). Encuentro poco práctico que yo busque el id 1 y me considere tambien {10, 11,...,19, 21,31,...}, ¿está bien esto o en este caso debería retornar solo el id 1?

disculpa si la pregunta está repetida, solo encontre issues para casos genéricos

**Comment by nivek0o0** [comment]
El matching parcial es sólo para parámetros de tipo **string**, no para números.

**Comment by DiegoEmilio01** [comment]
El matching debe ser sólo para los finales de los inputs o también antes? Ej: "fRanCia" = "fran" = "ciA" = "Francia"?

**Comment by nivek0o0** [comment]
Ambos. En tu ejemplo todos ellos deben entregar el mismo resultado.

**Comment by F-arellano** [comment]
hay algun problema en que en las consultas de matching parcial tambien retorne ademas el valor consultado? por ejemplo, si busco las ciudades de todos los paises %a% me retornará ciudades de francia, alemania, etc, asi que pensé en retornar una lista con (ciudad, pais) de forma que quede claro a que pais pertenece la ciudad

**Comment by nivek0o0** [comment]
Pueden asumir que nunca les pediremos buscar un string que coincida con múltiples resultados.

Pero si aún quieres asegurarte, entonces está correcto mostrar las tuplas (ciudad, país) en la consulta 2 impar o 3 par.
