### ISSUE TITLE
Importar datos a grupoXXe2

### ISSUE THREAD

**Issue by juanpacl111** [IIC2413/Syllabus-2020-1#178]
Para la entrega 1, ya incorporé todas las tablas al db grupoX. El tema es que para la segunda por lo que tengo entendido hay que utilizar grupoXe2. Existe alguna manera rápida de clonar una base de datos en otra en un mismo servidor? Por más que ha buscado no he logrado encontrar una solución óptima.

**Comment by nivek0o0** [comment]
[pg_dump y pg_restore](https://www.postgresql.org/docs/10/app-pgdump.html)
