### ISSUE TITLE
Archivo index en Sites

### ISSUE THREAD

**Issue by constanzacontreras** [IIC2413/Syllabus-2020-1#179]
Hola!!
Estamos usando repositorio de github para subir las cosas al servidor (en vez de usar filezilla), por lo tanto nuestra app esta en nuestro repositorio, pero queríamos saber como hacer que solo se agregue el archivo index en la carpeta Sites del servidor, ya que según enunciado ese es el archivo que debe ir en Sites. 
Sabemos que con pull se actualizan lo del repositorio al Servidor, pero como hacemos que solo se agregue ese archivo en específico?, y luego como lo hacemos para correr la página?

Muchas gracias!!!

**Comment by nivek0o0** [comment]
En el servidor debe estar el `index.php `y **todos los demás archivos**, de lo contrario la aplicación no funcionará. El archivo `index.php` por sí solo no hace nada.

Por lo tanto, lo correcto es que el repositorio de Github sea una copia fiel del servidor, en cuyo caso deben hacer `git pull`

**Comment by constanzacontreras** [comment]
Muchas gracias!
