### ISSUE TITLE
Duda Control 1

### ISSUE THREAD

**Issue by tamaralues** [IIC2413/Syllabus-2020-1#18]
Hola, en la última pregunta del control, no me queda tan claro que están pidiendo. Serían los nombres de la gente que pidió el articulo de 10000?

**Comment by nivek0o0** [comment]
Sí, pero no puedes simplemente filtrar por precio = 10.000, porque tu respuesta no sería válida para cualquier instancia. Por ejemplo, si alguien agrega un producto de 20.000 tu respuesta muere.

Tienes que pensar en una forma de encontrar el producto más costoso de una forma general.

**Comment by tamaralues** [comment]
👌 muchas gracias!
