### ISSUE TITLE
Consultas Anidadas

### ISSUE THREAD

**Issue by jacouyoumdjian** [IIC2413/Syllabus-2020-1#180]
Hola!

Tengo una duda sobre cómo hacer consultas anidadas complejas. En particular, si es que quiero hacer un inner join entre tablas para obtener una nueva con los datos que necesito (ejemplo):

`SELECT * FROM Tabla_1 INNER JOIN Tabla_2 ON Tabla_1.id = Tabla_2.id`

Puedo almacenar esta información en una nueva tabla y desde esa seleccionar los atributos que necesito, tipo:

`SELECT Tabla_1.id FROM (SELECT * FROM Tabla_1 INNER JOIN Tabla_2 ON Tabla_1.id = Tabla_2.id) AS Nueva_Tabla`

Y después de eso, "Nueva_Tabla" podría quedar "guarada en mi sistema" para ser utilizada en otra consulta? En este sentido, se pueden hacer dos comandos para obtener la consulta deseada?

Intenté eso literal pero no me funcionó, ¿existe alguna manera de hacerlo? Si es que no se puede y se debe hacer todo en un solo comando, cómo puedo ir "saltando" de tabla en tabla haciendo joins para llegar a mi consulta deseada (lei el jupyter de psql avanzado pero quedé corto como para las consultas que tengo que hacer).

Espero que se entienda la duda, y perdón por extenderme. Gracias!

Joaquín C.

**Comment by nivek0o0** [comment]
Existen 2 formas de haces consultas complejas como las que mencionas.

La primera es simplemente anidando y generar un monstruo de consulta. Pero debes tener cuidado con el renombre y de dónde obtienes los atributos. En el ejemplo que planteas estás llamando a `Tabla_1.id` que no existe afuera de la anidación. Afuera solo existe la tabla `Nueva_Tabla`. Por lo tanto, la consulta correcta sería:
`SELECT Nueva_Tabla.atributo FROM (SELECT * FROM Tabla_1 INNER JOIN Tabla_2 ON Tabla_1.id = Tabla_2.id) AS Nueva_Tabla`

La otra opción es dividir la consulta en **Vistas**. Las Vistas podemos entenderlas como abreviaciones de grandes consultas, que computan sus resultados cada vez que son llamadas. Es distinto a una tabla cuyos resultados son estáticos y fijos. Entonces, podrías hacer una única vez en tu base de datos:
`CREATE VIEW Anidada AS SELECT * FROM Tabla_1 INNER JOIN Tabla_2 ON Tabla_1.id = Tabla_2.id;`
Y luego en el código simplemente puedes hacer:
`SELECT atributo FROM Anidada;`
o cualquier otra consulta que ocupe a Anidada.

**Comment by jacouyoumdjian** [comment]
Gracias! Se entendió!
