### ISSUE TITLE
Tildes en matching parcial y lowercase

### ISSUE THREAD

**Issue by JuaniAndres** [IIC2413/Syllabus-2020-1#182]
Hola estaba tratando de llevar strings a minúscula sin embargo me encontré con el problema que la función strtolower no modifica caracteres como por ejemplo letras con tildes. Buscando en Internet encontré que existía mb_strtolower que debería solucionarme el problema especificando el encoding el problema es que al ocuparla y luego revisar el php del servidor me tira el siguiente error: 
Call to undefined function mb_strtolower
Mi duda es que si tengo que importar algo antes o simplemente esta no existe en la versión de php del servidor o nunca existió
Gracias de antemano

**Comment by nivek0o0** [comment]
¿Intentaste que Postgres se encargue de pasarlo a minúsculas?

De todas formas no probaremos con letras con tíldes en mayúscula.

**Comment by JuaniAndres** [comment]
Es que es para la condición de un like de una variable que se ingresa y no me a funcionado por eso quería editarlo por php con lo que encontré y lo de las tablas con lower.
Entonces con lo segundo que me comentas podría asumir que siempre las letras con tilde van a ser minúsculas?

**Comment by nivek0o0** [comment]
Sí, pueden asumir que no habrán mayúsculas con tildes.

**Comment by JuaniAndres** [comment]
Igual sigo con el problema que el strtolower trae problemas cuando tiene tildes porque genera �
Investigando encontré que las funciones mb son parte de una extencion llamada mbstring
Seria posible que la habiliten en el servidor ya que eliminaria todos los problema de trabajar con strings con tilde?

**Comment by nivek0o0** [comment]
Insisto en que es posible hacer que Postgres se encargue de ambas cosas: aplicar lower() a la columna donde se hace la búsqueda y aplicar lower() al parámetro string que ingresó el usuario.

Por ejemplo, el usuario ingresa `bÉlGi`. Entonces necesitas utilizar LIKE y comparar la columna nombre de la tabla países con algo como `'%bélgi%'`, ¿cierto?

Lo que hay que averiguar es cómo se podría formar en Postgres ese string que contiene símbolos de porcentaje a ambos lados y el parámetro lowercased.

**Comment by JuaniAndres** [comment]
ya me funciono, no se que hice que desde un comienzo no me funcionaba
muchas gracias
