### ISSUE TITLE
'Unique' en diagrama Entidad-Relación

### ISSUE THREAD

**Issue by FeBalla** [IIC2413/Syllabus-2020-1#183]
Hola, ¿cómo puedo expresar la cualidad _'unique'_ de un atributo en el diagrama entidad relación? ¿O esto solo se expresa en el esquema relacional?

**Comment by nivek0o0** [comment]
Solo se expresa en el esquema relacional. Podrías agregar la palabra `unique` despues del datatype del atributo. Aunque no evaluaremos eso en esta entrega.

En el diagrama E/R deben ir entidades, relaciones, atributos, PKs y cardinalidades (o determinación mediante las flechas)
