### ISSUE TITLE
Comparación de Horas, Fechas con Strings

### ISSUE THREAD

**Issue by MGome** [IIC2413/Syllabus-2020-1#184]
Hola buenas,
Tengo la duda sobre cómo comparar dos horas, donde una de ellas es un input del tipo Text y la otra del tipo Time. He intentado todas las formas que aparecen en la WEB (Usando strtotime() en la de formato text y usando TIME() en la misma), sin obtener resultado. Cabe decir que la comparación las he estado haciendo con los conectivos binarios menor o mayor

**Comment by nivek0o0** [comment]
Postgres es inteligente y se encarga automáticamente de la comparación, cuando el parámetro es string y la columna es TIME, DATE, etc. Lo importante es que el string tenga el mismo que lo que está guardado para evitar confusiones.

Por ejemplo, si quiero los Viajes que salen antes de las 10 am puedo simplemente hacer:
`SELECT * FROM Destinos WHERE horasalida < '10:00:00';`
