### ISSUE TITLE
Presentacion Diagrama ER

### ISSUE THREAD

**Issue by camaruri** [IIC2413/Syllabus-2020-1#185]
Hola en lucidchart, que era lo que algunos recomdaron para hacer el diagrama, tuve algunos problemas con los atributos porque no me dejaba poner mas de 50 figuras. 
Queria  preguntar si algun problema que en un mismo circulo de atributos, los pongamos todos (distinguiendo las llaves).
Quedaria de esta forma  

<img width="386" alt="Captura de Pantalla 2020-04-19 a la(s) 08 29 13" src="https://user-images.githubusercontent.com/53882047/79687812-dc4b4300-8217-11ea-94cc-9629551a670f.png">

Gracias

**Comment by nivek0o0** [comment]
Sí, esta forma también es válida.
