### ISSUE TITLE
Problemas al subir tablas a la base de datos

### ISSUE THREAD

**Issue by csantiagopaz** [IIC2413/Syllabus-2020-1#186]
Hola, estoy con problemas para subir las tablas a la base de datos, cuando intento ocupar el comando (\COPY usuario(uid,username,nombre,direccion,correo) from 'Tablas\usuario.csv' DELIMITER ',' CSV HEADER) no encontra la ruta, mismo cuando ponga la ruta en forma completa, y para asegurarme que estaba en la parte correcta, abri el powershell desde esa carpeta.
Como podria subir las tablas a la base de datos? porque pasa ese error?

pic del error:
![image](https://user-images.githubusercontent.com/42182095/79699533-1b03ec00-825e-11ea-952b-26aa47b74c64.png)

**Comment by nivek0o0** [comment]
Los datos deben estar subidos en el servidor, no sirve que estén en tu computador.
