### ISSUE TITLE
problema con crear dos foreing key en psql

### ISSUE THREAD

**Issue by Crespy98** [IIC2413/Syllabus-2020-1#187]
tengo una tabla de pais(id pais) y otra de ciudad(id ciudad), la cosa que tengo una tabla pais_ciudad(pais id,id ciudad) estas serian foreing key, que comando tengo que usar para crear esas dos llaves foraneas siendo que no estan en la misma tabla ?

**Comment by pbyoma** [comment]
Hola, 
Se trata igual como si fuera una, pero poniendo dos con sus respectivas tablas. 
CREATE TABLE registro(regid int, uid int, sid int, fecha_1 date, fecha_2 date, estado varchar(100), PRIMARY KEY(regid), FOREIGN KEY(uid) REFERENCES usuario(uid), FOREIGN KEY(sid) REFERENCES sendero(sid));
Este es un ejemplo, para que lo adaptes a lo que tu necesitas
