### ISSUE TITLE
Llaves minimales

### ISSUE THREAD

**Issue by benjaurr** [IIC2413/Syllabus-2020-1#188]
Hola! Con mi compañera estabamos definiendo las tablas en 3NF, y nos surgió una duda de llaves minimales. En el ppt de dependencias dicen que "Una relación esta en 3NF si para toda dependencia funcional no trivial X->Y, X es llave o Y es parte de una llave minimal". Unas diapositvas después dicen la modelación de curso esta en 3NF porque (profesor, modulo) es una llave minimal, pero (profesor, modulo) sería el X en este caso, y no el Y. Tampoco nos queda muy claro que se refiere con que "no existe llave X' tal que X' subconjunto X".

**Comment by alanezz** [comment]
Hola! Voy a partir al revés.

Lo primero, supongamos que tenemos la relación **Persona**(pid `int`, nombre `text`, dirección `text`) en la que sabemos que pid es único. Si queremos definir la llave de la relación Persona, una posible llave de la relación sabemos que es (pid, nombre, dirección) en conjunto. Esta es la dependencia trivial porque:

(pid, nombre, dirección) -> (pid, nombre, dirección)

Por lo tanto, al ser una llave "trivial" queremos buscar algo mejor. Si intentamos con (pid, nombre) también es válida, pero podemos encontrar algo mejor que sería que solamente pid sea llave. Si te fijas, pid sería "minimal", porque no vamos a poder encontrar una llave más pequeña que esta. A eso nos referimos con que no hay un conjunto de atributos **X'** tal que **X'** es subconjunto de **X** y **X'** sea llave (esto significaba que X no era minimal.

Ahora con su otra duda, en el ejemplo tenemos la relación **Curso**(sala, profesor, módulo) donde decimos:

- sala -> profesor
- profesor, módulo -> sala

Aquí la dependencia funcional que es candidata a llave es la segunda, porque involucra a todos los atributos de la relación **Curso**. En otras palabras, encontramos un par de atributos que es llave minimal, porque esta dependencia me está diciendo que en toda tupla de la relación el par (profesor, módulo) será distinto. Si no están convencidos de esto porfa deténganse a darle una vuelta. 
Entonces la segunda dependencia funcional no rompe 3NF porque (profesor, modulo) es candidato a llave. Ahora bien la primera no me está dando una candidata a llave, porque no puedo sacar ningún tipo de conclusión como con la dependencia anterior. Ahora bien, profesor **es parte** de una llave minimal (que sería el conjunto de atributos (profesor, modulo) ). Por lo que la primera dependencia **tampoco** rompe 3NF. 
En resumen, la definición dice "para toda dependencia funcional no trivial X->Y, X es llave o Y es parte de una llave minimal" entonces en este caso tenemos:

- sala -> profesor: aquí profesor ("el Y") es parte de una llave minimal.
- profesor, módulo -> sala: aquí (profesor, módulo) ("el X") es llave.

Por lo tanto esta relación está en 3NF.

Saludos.

**Comment by benjaurr** [comment]
Muchas gracias profe!

**Comment by benjaurr** [comment]
Muchas gracias profe!
