### ISSUE TITLE
BCNF

### ISSUE THREAD

**Issue by perezpefaur** [IIC2413/Syllabus-2020-1#189]
Si tengo un usuario que es modelado de la siguente forma:
![image](https://user-images.githubusercontent.com/48262438/79711486-ec096c80-8295-11ea-825c-dbaf96992d99.png)
Donde si tengo el id puedo saber todo el resto de los atributos, pero si tengo su mail tambien podria saberlo ya que un mail esta asosiado a un usuario unicamente y posiblemente otra llave tambien podria ser el username si es que la base de datos no deja crear dos personas con el mismo usuario.
Entonces no entiendo bien como podria justificar esta situacion.

**Comment by pbyoma** [comment]
Hola, 
Estas asumiendo que se puede crear un usuario por mail y que no se pueden repetir los username. No es algo que se pueda asumir que SIEMPRE se va a cumplir, sin embargo, si se puede asumir que SIEMPRE los user id van a ser unicos

**Comment by benjaurr** [comment]
No se puede asumir entonces que los usernames no se van a repetir? (Por lo que habría que tener userid)

**Comment by pbyoma** [comment]
Hola,
Los usuarios tienen un uid en los datos

**Comment by nivek0o0** [comment]
En otras issues se explicó que se toleraba este tipo de no normalización justificándose en la eficiencia de tener un ID por sobre un string.

---

Aunque teóricamente los profes me explicaron que tener ID y username únicos si estaría normalizado, dado que BCNF plantea que:

<img width="1208" alt="Captura de Pantalla 2020-04-20 a la(s) 17 36 45" src="https://user-images.githubusercontent.com/20782451/79802872-5a126a00-8350-11ea-9afe-4132144672f3.png">

es decir, si hay una dependencia X -> Y, X tiene que ser superllave para que esté normalizado.

La definición de superllave dice que:

<img width="1217" alt="Captura de Pantalla 2020-04-20 a la(s) 17 37 26" src="https://user-images.githubusercontent.com/20782451/79802995-9f369c00-8350-11ea-8c7e-c9a543116b08.png">

Entonces en este caso el par (ID, username) es superllave, porque tiene la capacidad de determinar todo lo demás de manera inequívoca. Por lo tanto la dependencia es `id, username -> otros` y la tabla sí está normalizada.

Finalmente puedes escoger cualquiera de los 2 como Primary Key, porque cada uno es llave candidata (superllave minimal). En general quieres escoger un ID numérico porque es más eficiente.
