### ISSUE TITLE
Consulta 5: Iglesias sin frescos

### ISSUE THREAD

**Issue by jperalta2202** [IIC2413/Syllabus-2020-1#190]
Hola, para la consulta 5 nos piden mostrar los nombres de las iglesias junto a los nombres de los frescos que contenga. Debemos asumir que todas las iglesias tienen al menos un fresco? o en caso de no haber un fresco en una iglesia entonces no debemos mostrar esa iglesia?

**Comment by nivek0o0** [comment]
Hola, si una iglesia no tiene Frescos entonces **no se muestra**.
