### ISSUE TITLE
Consulta 6: Todos los usuarios?

### ISSUE THREAD

**Issue by sebaav12** [IIC2413/Syllabus-2020-1#191]
La consulta debe retornar el id, user, gastos para **todos** los usuarios que gastaron en tickets entre las dos fechas dadas por el input? o además se sebe ingresar un id de un usuario en especifico como tercer input?

**Comment by nivek0o0** [comment]
Debes mostrar los gastos de tickets para **cada usuario** de la aplicación, incluso si el gasto es 0. Por ejemplo:

ID|username|Total
-|-|-
1|Juanito123|500
2|Pedrito_96|430

Te recomiendo revisar una issue antigua donde expliqué cuales tickets debían ser considerados para este cálculo.
