### ISSUE TITLE
Eliminar carpeta de Sites

### ISSUE THREAD

**Issue by dtgazmuri** [IIC2413/Syllabus-2020-1#192]
Subí una carpeta por error a Sites en el servidor. ¿Cómo puedo eliminarla de ahí?

**Comment by nivek0o0** [comment]
* Si ocupas Filezilla: click derecho en la carpeta remota y la eliminas.

* Si ocupas Github: puedes eliminarla de cualquiera de los 2 repositorios locales (tu PC o el servidor) y finalmente haces push para sincronizar el repositorio remoto (github). Es decir:
    * En tu computador eliminas la carpeta, luego haces allí git add, commit y push. Finalmente en el servidor haces git pull y se elimina la carpeta.
    * Lo mismo que antes pero invirtiendo los papeles. Eliminar, add, commit, push en el servidor y luego haces git pull para actualizar tu pc.

Esto es aplicable para cualquier acción: crear, editar, eliminar archivos o carpetas.

**Comment by dtgazmuri** [comment]
Estoy usando el terminal

**Comment by nivek0o0** [comment]
El comando para eliminar una carpeta es `rm -R <nombreCarpeta>`
