### ISSUE TITLE
Formato Output Consultas

### ISSUE THREAD

**Issue by JuaniAndres** [IIC2413/Syllabus-2020-1#193]
Hola una duda respecto a que en el enunciado se nos pide que respetemos el formato output enseñado en la ayudantia. Esto significa solamente que este el resultado este dentro de una tabla o algo más? Lo otro los resultados los ordenamos de alguna manera por ejemplo orden alfabético o cantidad?
Me preocupa porque como lo van a corregir automáticamente  y para no tenerlo mal por formato

**Comment by nivek0o0** [comment]
Hola, basta que el resultado esté dentro de una tabla y no importa el orden de las filas.

**Comment by JuaniAndres** [comment]
yap gracias
