### ISSUE TITLE
Elementos adentro de carpeta Entrega2

### ISSUE THREAD

**Issue by juansjimenez** [IIC2413/Syllabus-2020-1#195]
Hola! En el Enunciado dice que tenemos que tener un pdf dentro de la carpeta Entrega2, que es el reporte que se corregirá para esta entrega. Sin embargo, nosotros utilizamos un repositorio en github desde donde hacíamos pull, por lo que tenemos otros archivos en una carpeta llamada Data. ¿Hay algún problema con entregar la carpeta 2 con estos dos elementos en vez de solamente el pdf?

Gracias!

**Comment by nivek0o0** [comment]
No hay problema con que hayan otros archivos. Lo qué si tiene que existir es **Algo.pdf**, porque eso se va a recolectar.
