### ISSUE TITLE
Consulta 3: Usuarios hospedándose actualmente

### ISSUE THREAD

**Issue by snarriagada** [IIC2413/Syllabus-2020-1#197]
Hola! dice en la 3) Ingrese un username. Muestre todos los nombres distintos de países en los que ha hospedado el usuario con ese username mediante hoteles de la agencia.

si alguien a la fecha (ocupe current_date) esta hospedándose (es decir no ha llegado su check out) tambien debo considerarlo verdad? o solo mostrar los que ya hayan pasado su reserva completa del hotel?

gracias!

**Comment by nivek0o0** [comment]
Los que están actualmente hospedándose **sí deben ser considerados**. 

También existe una función en Postgres que te entrega el timestamp actual.
