### ISSUE TITLE
Error al hacer Push en Servidor

### ISSUE THREAD

**Issue by snarriagada** [IIC2413/Syllabus-2020-1#198]
Hola, en el servidor tenemos creado Sites pero no en nuestro repositorio remoto. Entonces pensamos hacer git push desde el server y luego pull de nuestro repo local para tener Sites pero salio el error que dejo abajo, no se si debo correr alguno de los comandos que sugiere o se puede subir otra Sites al remoto y luego pull del server y 'sobreescribir' la existente?

gracias!!

grupo77@codd:~$ git add .
grupo77@codd:~$ git commit -m"sites"

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: empty ident name (for <grupo77@codd.ing.puc.cl>) not allowed

**Comment by nivek0o0** [comment]
Simplemente ejecuta una vez estos comandos. Git necesita saber quién es el autor del commit. 
```
git config user.email "tu correo"
git config user.name "tu nombre"
```

La forma en que intentaste sincronizar Sites es la mejor. Si quisieras sobreescribirla podrían escontrarte con múltiples conflictos.

**Comment by snarriagada** [comment]
funciono pude hacer push, pero solo se subieron archivos basura como .psql_history .bash_history etc al repo remoto y no se subio la carpeta Sites (que esta vacia y en el servidor), que puede ser?

gracias!

**Comment by nivek0o0** [comment]
Las carpetas vacías no con consideradas por git. Deben tener algún archivo adentro.

**Comment by snarriagada** [comment]
perfect, entonces tengo que crear algo en Sites desde el servidor y hacer push para que pesque?
como lo creo?

**Comment by nivek0o0** [comment]
No entiendo para qué necesitas tener una carpeta vacía en Github. Cuando vayas a subir todos los archivos de la aplicación se creará automáticamente.

De todas formas, se puede crear un archivo vacío con `touch hola.txt`
