### ISSUE TITLE
Duda esquema relacional

### ISSUE THREAD

**Issue by Sweinzierl28** [IIC2413/Syllabus-2020-1#199]
Holaa! No tengo muy claro si el esquema relacional se debe presentar en forma de cuadros, colocando como título del cuadro el nombre de la tabla y en las filas de ésta los atributos con sus datatypes y destacando las llaves, o simplemente listando las tablas como lo decian en la ayudantia, es decir, de la siguiente forma:
Artista(id: int PK, nombre: text, fecha_nacimiento: date, fecha_fallecimiento:date, descripcion: text)
Gracias!

**Comment by clolate** [comment]
Ambas sirven! te recomiendo ~~para facilitar la corrección :)~~ los cuadros
