### ISSUE TITLE
Esquema 

### ISSUE THREAD

**Issue by perezpefaur** [IIC2413/Syllabus-2020-1#2]
Como no tenemos una base de datos el esquema simplemente van a ser columnas, eso esta bien? o se refieren a la notacion de Actuo En(aid: int, pid: int, nombre personaje: string)

**Comment by nivek0o0** [comment]
Hola,
nos referimos a la notación
**Personajes(nombre, apellido, edad)**.

Recuerda revisar la rúbrica publicada junto al enunciado!
