### ISSUE TITLE
Duda Control 1 pregunta 4

### ISSUE THREAD

**Issue by jperalta2202** [IIC2413/Syllabus-2020-1#20]
Hola, en la pregunta 4 se piden los nombres de los clientes  que pidieron al menos 2 productos. Esto significa los clientes que han pedido al menos 2 unidades de algún producto? o los clientes que han pedido en TOTAL al menos 2 productos (puede haber pedido 1 unidad de un producto y 1 unidad de otro)?

**Comment by pbyoma** [comment]
Hola, 
son los clientes que han pedido al menos dos productos distintos, sin importar la cantidad que haya pedido de cada uno.

**Comment by jperalta2202** [comment]
gracias

**Comment by sebacarrasco** [comment]
Hola, entonces se excluyen los casos en que alguien compró un mismo producto en dos o más pedidos?

**Comment by nivek0o0** [comment]
Si el cliente en toda su historia **solamente** compró 1 producto en varias oportunidades, entonces se excluye de la respuesta. 

Se buscan aquellos clientes que compraron 2 o más productos distintos, sin importar que hayan hecho 1, 2, 3, 1000 pedidos por cada uno de ellos.

**Comment by jacouyoumdjian** [comment]
Hola!

En este misma pregunta me surgió la duda de si es que existe (o de que si es legal) alguna función que se le pueda aplicar a una tabla para saber la cantidad de tuplas que tiene. Como "sacar la cardinalidad" de una tabla. Gracias!

Saludos,

Joaquín C.
