### ISSUE TITLE
Dudas consultas grupo par

### ISSUE THREAD

**Issue by t-schilling** [IIC2413/Syllabus-2020-1#200]
Hola, la idea de las consultas para el grupo par es que entreguen exactamente lo pedido en el enunciado o que puedan entregar lo solicitado?
Me refiero, por ejemplo, si la consulta 2 debe ser un botón que solo entregue los nombres de las plazas en las cuales hay obras de Gian Lorenzo Benini o si debo implementar una consulta en la cual uno escoja un artista y un tipo de lugar e indicar los nombres de los lugares en donde hay obras de ese artista.
Gracias

**Comment by juanreutter** [comment]
Hola, con lo primero que dices, para la consulta 2, bastaría, por que no pedimos que ingreses un artista (a diferencia de la 3, donde pedimos ingresar país). 
Pero si puedes hacer lo segundo (y mejor aún, decirle a php que ponga a Bernini como default), dale nomás!
