### ISSUE TITLE
Borrar CSV luego de importar datos

### ISSUE THREAD

**Issue by IriSalazar** [IIC2413/Syllabus-2020-1#201]
Hola!
Si ya se importaron los datos de los csv a psql, se pueden borrar del servidor y se mantienen en el psql? Pregunto por un tema de orden en la carpeta.

Saludos! <3

**Comment by clolate** [comment]
Hola! si se mantienen, el servidor y la base de datos en psql son espacios diferentes. Te recomiendo igual tener un respaldo en alguna parte por si acaso.

**Comment by IriSalazar** [comment]
Gracias! :D
