### ISSUE TITLE
Problemas con el input

### ISSUE THREAD

**Issue by jitorcas** [IIC2413/Syllabus-2020-1#202]
Hola!

Lamento lo tarde, pero hemos estado estado teniendo problemas únicamente con esto y luego de agotar todas las instancias (google) decidimos preguntar.

No logramos hacer que $nombre_input = $_POST["nombre_input"] nos lea el input. Para clarificar tenemos lo siguiente:

**index.php** 

```
<form align="center" action="consultas/consulta_dos.php" method = "post">
    <input type="text" name="nombre_input">
    <button type="submit" class="btn btn-dark">BUSCAR</button>
    <br/>
</form>

```

**consulta_dos.php**

```
<?php
  require("../config/conexion.php");
  $nombre_input = $_POST["nombre_input"];

        $query = "SELECT nombrex FROM tabla1,tabla2 WHERE tabla1.id = tabla2.id AND nombre = '%$nombre_input%';";
        $result = $db -> prepare($query);
        $result -> execute();
        $usuarios = $result -> fetchAll();
  ?>
```
pero $nombre_input nunca recibe el input, ya que cuando probamos la consulta con un nombre determinado, nos arroja bien las tablas, lo mismo ocurre cuando hacemos las consultas directamente del servidor. 
¿Saben qué puede ser el problema? Estamos trabajando con Bootstrap4

**Comment by juanreutter** [comment]
No conozco Bootstrap4, pero el código debería ser $_POST["nombre_input"], por que así es como lo nombraste en el form.

**Comment by jitorcas** [comment]
@juanreutter si! sorry, se me fue cambiarlo en la pregunta que hice, pero coincide con el que está en el form

**Comment by jitorcas** [comment]
@juanreutter si! sorry, se me fue cambiarlo en la pregunta que hice, pero coincide con el que está en el form

**Comment by juanreutter** [comment]
Lo otro: la definición de $query está rara. Como una forma de debugging, pídele que te haga un echo al string $query, para que lo veas en la página.

**Comment by alanezz** [comment]
Complementando lo que dice Juan, deberías hacer un echo de `$nombre_input` para ver si el problema es que el parámetro no está llegando.

**Comment by jitorcas** [comment]
@juanreutter @alanezz Muchas gracias! Si lee la variable. ¿eso supone que la consulta está mal hecha?
En ese caso, cuando en vez de asignarle una variable en la consulta, le asigno un string directamente (en este caso es un país) me devuelve la tabla bien filtrada, ¿saben por qué podría suceder eso? (que con variable no funcione y cuando asigno texto si filtre)

**Comment by juanreutter** [comment]
Claro, debe ser el prepared statement. Yo encuentro extraño que usas = '%$string%' en vez de LIKE '%$string%', otra opción sería que el prepared statement se confunde en este caso.

**Comment by jitorcas** [comment]
@juanreutter Muchas gracias!, la verdad no estaba de la mejor forma definido $query, pero como nos funcionaba en el servidor, no nos cuestionamos usar LIKE. ahora funciona!
