### ISSUE TITLE
Duda dependencia atributos

### ISSUE THREAD

**Issue by jadawabe** [IIC2413/Syllabus-2020-1#203]
Hola, tenemos una duda. Si uno sabe id_cuidad_origen, id_cuidad_destino y medio entonces podemos saber la duración y la cantidad máxima? En otras palabras, es esto una dependencia?

**Comment by juanreutter** [comment]
Hola, en general trata de dar contexto (somos grupo impar, tenemos una tabla de viajes), etc. Lo que preguntas es parte de la modelación, de cuantos viajes se pueden hacer desde un origen a un destino, por cada medio. Tienen que ver del enunciado si acaso esto es verdad o no: ¿es solo un viaje? ¿solo un viaje por medio? Miren bien la parte de destinos!
