### ISSUE TITLE
Reporte: consultas implementadas

### ISSUE THREAD

**Issue by javieranavarrete** [IIC2413/Syllabus-2020-1#204]
hola, en el reporte que se pide hay una sección "Todas las consultas en SQL que implementaron en su aplicación.".
Con esto se refiere a que digamos cuales si y cuales no se implementaron, o que literal pongamos el código con el cual se obtiene lo pedido estilo "SELECT atributo_pedido FROM tabla1"

**Comment by nivek0o0** [comment]
Hola, cuales sí y cuales no.
