### ISSUE TITLE
Matching parcial múltiple de parámetros

### ISSUE THREAD

**Issue by dtgazmuri** [IIC2413/Syllabus-2020-1#205]
Hola
Si se ingresa solo una parte del username y se utilizan %%, la consulta arrojaría todos los usuarios que tienen esa parte dentro de su username. Por ejemplo, si están los usuarios María, Pedro y Tomás, ingresar 'a' en la consulta daría como resultado todos los países en los que han estado María y Tomás. Entonces, ¿asumo que en la corrección se ingresarán los usernames completos para evitar esto?

**Comment by nivek0o0** [comment]
#177
