### ISSUE TITLE
Comparación de fechas y horas

### ISSUE THREAD

**Issue by Tomasalvarez15** [IIC2413/Syllabus-2020-1#206]
No puedo hacer la comparación entre los horarios de cierre y apertura de la iglesia con los input del usuario. Si pongo "13:00:00" directamente sí funciona. Pero usando la variable que tengo $horarioa no tiene caso que entregue algo la request.
![request](https://user-images.githubusercontent.com/42297751/79920607-7a98fd80-83fe-11ea-90e1-a85ed9afcd76.png)

**Comment by nivek0o0** [comment]
Cuando una consultas SQL quiere comparar un string contra una columna DATE, TIME, etc, debe entregar el string encerrado en comillas simples.

Tu consulta está quedando como `...iglesias.horaapertura>13:00:00;`, lo que fallará

**Comment by nivek0o0** [comment]
![15875092724644511661351664002483](https://user-images.githubusercontent.com/20782451/79921647-a61ce780-8400-11ea-8939-b80856fd78b8.jpg)

**Comment by Tomasalvarez15** [comment]
Muchas gracias sos un dios
