### ISSUE TITLE
CAMBIO CLAVE POSTGRES!

### ISSUE THREAD

**Issue by shantifabri** [IIC2413/Syllabus-2020-1#207]
Hola, sobre el correo que mandó el profesor sobre el cambio de clave, si nosotros ya la cambiamos no tenemos que cambiarla de nuevo o si?

**Comment by nivek0o0** [comment]
Si ya cambiaron la clave **del servidor**, entonces no es necesario.

El profe se refería a la clave **de Postgres**, esa sí deben actualizarla a algo más seguro. De lo contrario les asignaré una aleatoria en los próximos días.

**Comment by shantifabri** [comment]
Esa también la cambiamos asique supondre que todo bien. Gracias!
