### ISSUE TITLE
Error transferencia.sql guia ejercicios procedimientos almacenados

### ISSUE THREAD

**Issue by benjastraub** [IIC2413/Syllabus-2020-1#208]
Hola, intenté usar la función transferencia que muestran en la guía creando el archivo `transferencia.sql` y usando `\i transferencia.sql` pero después tengo el siguiente error:

```
SELECT transferencia.sql;
ERROR:  missing FROM-clause entry for table "transferencia"
LINE 1: SELECT transferencia.sql;
```

PD: cuando definen PersonasCompleto ocupan "run" y en la función ocupan "rut"

**Comment by nivek0o0** [comment]
Hola, una vez que logras importarlo correctamente, debes llamar a la función según el nombre que le pusiste dentro del procedimiento. En este caso sería:
`SELECT transferencia();`

Y si encuentras algún typo puedes arreglarlo y debería funcionar.
