### ISSUE TITLE
Modificar página

### ISSUE THREAD

**Issue by ShescBlank** [IIC2413/Syllabus-2020-1#209]
Hola :D
Solo quería preguntar si ya podemos modificar nuestra página o influirá en la corrección? (sin tocar grupoXXe2)

Muchas gracias 😄

**Comment by nivek0o0** [comment]
Hola, ya pueden modificarla sin problemas.

Como regla general, podrán modificarla 1 hora después de la entrega anterior, esto debido a que todas las app se copian al llegar el deadline.
