### ISSUE TITLE
Operadores

### ISSUE THREAD

**Issue by tamaralues** [IIC2413/Syllabus-2020-1#21]
Hola! 
Se pueden usar operadores no vistos en clases, como sum(), max() o group by?

**Comment by ridiazcampos** [comment]
¡Holaaa!
Por el momento, y para el caso del control de Álgebra relacional, no :(

Con los operadores que vieron en clases esta semana es posible formar otros más "complejos", y que sirven para el caso de las consultas del control!

Lo genial es que cuando se puedan usar, ya sabrán una forma en la que podrían funcionar algunos de los operadores que mencionas (*) :D 

Cualquier otra duda nos comentas!
Saludos y mucho éxito con las actividades! (: 

(\*) al menos para el caso de max y group by 😊

**Comment by humbertoortuzar** [comment]
Hola! y se puede utilizar estos para condiciones?
Por ejemplo al filtrar:
sigma_p.x=max(p.x) (MiTabla)

**Comment by juanreutter** [comment]
No, la idea es que lo hagas con las condiciones dadas. Parte de la pregunta es que puedas pensar cómo filtrar los productos más caros usando solo comparaciones tipo menor/mayor/igual!
