### ISSUE TITLE
Hay grupoXe3?

### ISSUE THREAD

**Issue by StroveLight** [IIC2413/Syllabus-2020-1#210]
Para esta entrega (3), se necesita crear una nueva base de datos, o se puede usar la de la entrega pasada?

**Comment by nivek0o0** [comment]
Hola, sí es necesario que creen una nueva base de datos, para no interferir con la corrección de la E2.

**Comment by benjastraub** [comment]
Hola @nivek0o0, quedé con dos dudas respecto a esto.

Por lo que entendí del enunciado, ¿habría que crear la BDD en los servidores de los dos grupos que nos juntamos, pero tener la página solo en una que accede a los dos?

Lo otro es si ¿hay que usar los mismos datos de la entrega 2?

**Comment by nivek0o0** [comment]
El **objetivo primordial** es no alterar los datos para la corrección de la Entrega 2. 

Si tu estimas que el cambio que necesitas hacer (_por ejemplo, agregar una columna con las contraseñas_) no afecta a las consultas implementadas en la E2, entonces puedes modificar `grupoXXe2` y no pasa nada.

Si no estás seguro, puedes copiar toda la BD desde **e2** hacia **e3** y hacer todos los cambios que desees en **e3**. 

Los datos son los mismos para el resto del proyecto.

**Comment by amaiajuanchuto** [comment]
Hola, 

Tengo una duda con respecto a lo que preguntaron que no me quedó claro. Tenemos que cada grupo por separado copiar su BD desde la e2 a la e3 para que luego nuestra página web entre a los dos servidores y trabaje con las BD, o podemos juntar ambas BD en una nomas y trabajar desde ahí??

Muchas gracias!!
