### ISSUE TITLE
Creación BDD grupoXe3

### ISSUE THREAD

**Issue by benjastraub** [IIC2413/Syllabus-2020-1#211]
Hola, ¿ustedes crearán las BDD para la entrega3?

Porque usando `\l` no aparecen las correspondientes a esta entrega y tratando de crearla con `CREATE DATABASE grupoXe3;` me retorna `ERROR:  permission denied to create database`

**Comment by nivek0o0** [comment]
Hola, ahora sí están creadas esas bases de datos. Lo siento, pensé que tenían los permisos para crearlas.
