### ISSUE TITLE
Videos Sesión de Consultas Procedimientos Almacenados

### ISSUE THREAD

**Issue by ranelson1** [IIC2413/Syllabus-2020-1#212]
Hola,

¿Podrían subir el video de la sesión que hizo el profesor Adrían el viernes pasado? No lo encuentro ni en ayudantías ni videos clases.

Si no es mucho pedir tambien los videos de las otras sesiónes de consulta si es posible.

Gracias!

**Comment by nivek0o0** [comment]
Hola! 

Acabo de subir el link en el readme de las clases online. [aquí](https://github.com/IIC2413/Syllabus-2020-1/blob/master/Clases%20Online/README.md)
