### ISSUE TITLE
Dudas enunciado entrega 3: consulta artistas

### ISSUE THREAD

**Issue by ChayoPerez** [IIC2413/Syllabus-2020-1#213]
A qué se refiere con esto?

> La lista de obras que ha hecho ese artista: todos los atributos en otra tabla.

Tengo que hacer una tabla por obra? O son todas las obras en una misma tabla? Tengo que por apartado poner onda un punteo con los nombres?

Gracias

**Comment by nivek0o0** [comment]
Hola, se refiere a que hagas una tabla para listar todos los atributos de las obras que haya hecho ese artista.

Lo de "otra tabla" se refería a que debe ser diferente a la tabla donde se muestran los atributos del artista.

Por ejemplo:
**Artista**
nombre|fecha nacimiento|descripción
-|-|-
Pedro|01-01-1800|lorem ipsum blablabla

**Obras**

nombre|fecha_inicio|fecha_culm|periodo|tipo|técnica|material
-|-|-|-|-|-|-
Obra1|1830|1831|Barroco|Fresco||
Obra2|1832|1833|Barroco|Pintura|Óleo|
Obra3|1834|1835|Barroco|Escultura||yeso

**Comment by ChayoPerez** [comment]
yaya entiendo, gracias! :)

**Comment by ChayoPerez** [comment]
Una pregunta. Tengo que poner dónde está la obra también?

**Comment by nivek0o0** [comment]
En esta página del artista, **no**. 

En la página de la obra, **sí**. Además, ese lugar debe ser un vínculo a la página del lugar.

**Comment by constanzacontreras** [comment]
Hola! no entiendo por que hay que poner la información de las obras dos veces (es decir, en la página del artista y de la obra), siendo que hay en la página de artista están las obras realizadas por él con un link que lo lleva a su respectiva información (considero que así es más ordenado y es lo que entendí del enunciado).

**Comment by nivek0o0** [comment]
Hola @constanzacontreras 

Hay que poner toda la información de la obra en la **página de la obra** porque es su página y es el lugar donde debe estar.

Ahora bien, hay que poner toda la info. de las obras que realizó el artista en la **página del artista** para distinguir las obras que tengan alcance de nombre.

¿Cuál es el problema con que una misma información se muestre en 2 lugares distintos? Puedes simplemente copiar y pegar el código que construye la tabla o bien modularizarlo.

**Comment by fjcroquevielle** [comment]
Hola!, Sale en el enunciado que cuando me muestran las obras de los artistas (en la pagina de los artistas) debo poder ir a la pagina de las obras a partir del nombre de la obra, podría ser a partir del oid?
Saludos,
Gracias
