### ISSUE TITLE
Dudas Generales E3

### ISSUE THREAD

**Issue by nivek0o0** [IIC2413/Syllabus-2020-1#214]
¿Cómo haremos para trabajar con ambas BD por separado entrando a cada servidor según lo que queramos hacer?

¿Cómo tenemos que copiar la BD que hicimos en la e2 a la e3? Si podemos modificar la BD de alguna forma que nos sirva más para trabajar en esta entrega. En relación a esto también, el enunciado dice que hay que inventar una nueva entidad de "entradas a museos" y no sabemos en cuál BD crear esa entidad o si hay que crearla en ambas BD.

Y por último, en la parte de la entrega del procedimiento almacenado, ¿Tengo que implementarlo en mi código de la página y además subirlo aparte en la carpeta e3?

**Comment by nivek0o0** [comment]
Para trabajar con ambas bases de datos solo deben duplicar todo el código de conexión. Por ejemplo, podrían tener los siguientes archivos:

**data.php**
```
<?php
   $user1 = 'grupoXX';
   $password1 = 'grupoXX';
   $databaseName1 = 'grupoXX';

   $user2 = 'grupoXX';
   $password2 = 'grupoXX';
   $databaseName2 = 'grupoXX';
?>
```

**conexion.php**
```
<?php
  try {
    require('data.php');
    $db_par = new PDO("pgsql:dbname=$databaseName1;host=localhost;port=5432;user=$user1;password=$password1");
    $db_impar = new PDO("pgsql:dbname=$databaseName2;host=localhost;port=5432;user=$user2;password=$password2");
  } catch (Exception $e) {
    echo "No se pudo conectar a la base de datos: $e";
  }
?>
```
Y luego mandas la query a `$db_par` o `$db_impar` dependiendo de dónde están los datos que necesitas.

-----------

Respecto a copiar la base de datos, existen comandos para descargar toda una base de datos en un archivo e importarlo en otra ya existente. Estos son `pg_dump` y `pg_restore`. Puedes buscar en la documentación de Postgres (version 10) ejemplos de cómo utilizarlos.

-------------

Para esta entrega tendrán que modificar la base de datos (la nueva grupoXXe3 porfavor para no alterar la corrección de la E2). Por ejemplo para agregar a los usuarios una columna de contraseñas o para crear la nueva entidad de Entradas a museos. ¿Dónde crear las entradas? Pues es decisión de ustedes, pero deben tener en mente las entidades con las que se relacionará esta nueva tabla. 

Por ejemplo si la funcionalidad que deben implementar dice que deben obtener las entradas del usuario con nombre "Pedro", entonces sería conveniente crearla en la BD impar para facilitar el JOIN. Si deben mostrar las entradas con el nombre del museo, sería útil crear la tabla en la BD par, porque ahí esta la tabla museos.

Finalmente, si deben obtener los nombres de los museos para cierto usuario, da lo mismo dónde pongas esta tabla porque te quedará un JOIN sin poder hacerse y tendrás que hacerlo de forma manual en PHP, obteniendo y cruzando datos de ambas BDs.

----------------------

Respecto al procedimiento almacenado, este debe ser implementado en la base de datos, y en el lenguaje **PL/pgSQL** que es propio de Postgres y no tiene nada que ver con PHP. La forma de hacer esto es crear un archivo llamado _procedimiento.sql_ (por ejemplo), con la definición de la función. Luego lo importas a la base de datos haciendo `\i procedimiento.sql` y finalmente lo llamas desde la página como una consulta típica: `SELECT mi_funcion(param1, param2,...);`
Nosotros les pedimos que suban una copia de ese _procedimiento.sql_ a la carpeta `Entrega3` para corregirlo.

**Comment by lisraelrat1** [comment]
Hola @nivek0o0! Tratando de hacer la configuración como está en esta issue, nos sale el siguiente error:
<img width="1237" alt="Captura de Pantalla 2020-05-08 a la(s) 13 53 57" src="https://user-images.githubusercontent.com/52945060/81433964-6873ca80-9133-11ea-9fcc-b0a866795f34.png">
Revisé muchísimas veces los archivos y la contraseña está correcta y todo está igual a como se pide. Lo único que se me ocurre es que como los archivos están en el servidor del grupo menor, en nuestro caso el 16, entonces no se puedan conectar con el otro servidor. Como podría arreglarlo?

**Comment by nivek0o0** [comment]
Hola @lisraelrat1 
puedes intentar ahora?

**Comment by lisraelrat1** [comment]
Traté de nuevo, volviendo a cargar todos los archivos y todavía no me funciona, mismo error :(

**Comment by nivek0o0** [comment]
@lisraelrat1 La clave de Postgres del grupo 91 no es `BDD2020`, por eso la app no puede conectarse.

**Comment by rodobkn** [comment]
@nivek0o0 en la parte de procedimientos almacenados tengo una duda.

En php se puede conectar a las dos bases de datos para hacer las consultas a las dos bases de datos de manera cómoda, sin embargo, en el archivo .sql que se debe crear en una base de datos determinada para realizar el procedimiento almacenado, como puedo usar las tablas de la otra base de datos?

Puesto que no hay problemas al usar las tablas de la base de datos en donde está el archivo .sql del procedimiento almacenado, pero como hago la referencia en lenguaje PL/pgSQL que voy a utilizar las tablas de la base de datos del otro grupo al que se nos unió?

Espero hayas entendido mi pregunta.
