### ISSUE TITLE
Procedimientos almacenados jupyter notebook error

### ISSUE THREAD

**Issue by bgfeuereisen** [IIC2413/Syllabus-2020-1#215]
Hola buenas, he tratado de ejecutar la guía de procedimientos almacenados a través de jupyter notebook y me tira el siguiente error.

(psycopg2.OperationalError) 
(Background on this error at: http://sqlalche.me/e/e3q8)
Connection info needed in SQLAlchemy format, example:
               postgresql://username:password@hostname/dbname
               or an existing connection: dict_keys([])

qué puedo hacer?
gracias

**Comment by MarceloSaldias** [comment]
Hola!

Esto puede suceder por 2 razones:
1. El string de conexion no tiene el formato correcto. Revisa que la celda tiene un formato similar a este:

       postgresql://<usuario_de_postgres>:<pass_de_postgres>@localhost/<nombre_db>
2. El string de conexion tiene el formato correcto pero no tiene las credenciales correctas.  Para esto corrobora que los valores entre <> sean correctos!

**Comment by bgfeuereisen** [comment]
Debo crear la base de datos? o al correr el código se creará automaticamente la nueva db?
gracias

**Comment by MarceloSaldias** [comment]
La idea es que pongas el nombre de una base de datos que ya tengas creada, o bien crees una y pones ese nombre ahi, cualquiera sirve
