### ISSUE TITLE
Dar de baja a un usuario

### ISSUE THREAD

**Issue by ShescBlank** [IIC2413/Syllabus-2020-1#217]
Hola 😄 
Cuando demos de baja a un usuario debemos eliminar la tupla de la tabla usuarios (usando ```ON DELETE SET NULL```) o, simplemente, eliminar su información pero dejar el id para no alterar a las otras tablas?

Muchas gracias!

**Comment by nivek0o0** [comment]
Hola,
la verdad es que la forma en que implementen la funcionalidad de **dar de baja a un usuario** no nos importa. El objetivo es lograr que este usuario no se pueda volver a logear. 

Pueden eliminar su contraseña, marcar en una columna aparte que está inactivo o eliminar su tupla. Todas estas alternativas, correctamente implementadas, pueden impedir el login de ese usuario en el futuro.

Si deciden eliminar la tupla, me parece que da igual si ocupan `ON DELETE SET NULL` u `ON DELETE CASCADE` para las entidades relacionadas, dado que eliminarlas no afecta el resto de las funcionalidades de esta entrega.

**Comment by aalmuna** [comment]
Me parece que ```CASCADE``` no se debería usar porque se pide que la información de los tickets, reservas y entradas se mantenga en la aplicación. Lo menciono por si a alguien más le surge la duda.

Muchas gracias por la respuesta :D

**Comment by furzuadr** [comment]
Hola! @nivek0o0 se puede oser DELETE CASCADE? Ya que en el enunciado sale que se tienen que mantener los otros datos!
Gracias!

**Comment by nivek0o0** [comment]
Es verdad. Entonces la única alternativa es `SET NULL`.
