### ISSUE TITLE
Reserva de hoteles: ¿qué atributos mostrar?

### ISSUE THREAD

**Issue by ChayoPerez** [IIC2413/Syllabus-2020-1#218]
Hola!
En el enunciado dice que se tienen que mostrar todos los hoteles. ¿Qué implica exactamente? Solo nombre o nombre/dirección/telefono/precio?

Gracias!

**Comment by nivek0o0** [comment]
Hola, 
como regla general, mostrar una entidad significa mostrar todos sus atributos.

**Comment by StroveLight** [comment]
Eso significa tambien mostrar el id de cada hotel, y si tiene algun otro id en sus columnas mostrarlo tambien?

**Comment by nivek0o0** [comment]
El ID de la entidad no es necesario mostrarlo, porque dado que es inventado por ustedes para uso interno, no agrega valor.

Si hay IDs de otras entidades asociadas, deben mostrar el nombre de la entidad asociada. (Me imagino el nombre de la ciudad). Si corresponde a una funcionalidad descrita en el enunciado (como el lugar donde está una obra), ese nombre debería ser un enlace a otra página de la entidad relacionada.
