### ISSUE TITLE
Clase 6/5

### ISSUE THREAD

**Issue by VicenteElCyrano** [IIC2413/Syllabus-2020-1#221]
Donde se encuentra la clase de hoy?

**Comment by itplanella** [comment]
Hola! Esperamos que hayan aprovechado la semana de ajuste.

Les quiero contar que ya está disponible el video de la semana en el siguiente link:

https://youtu.be/9zeiEzqG8ps

Este video dura cerca de 45 minutos. Es ideal que tengan el video visto para la clase que vamos a tener el miércoles al sexto módulo (como siempre, disponen del 5to módulo para ver el video). Yo me voy a conectar desde las 16:30 para responder dudas. Este video es re importante porque hay actividad de esto para la próxima semana y la clase del sexto módulo no se va a entender si no lo ven.

Saludos!

(Esto le llego a una de las secciones, yo lo copie)

**Comment by VicenteElCyrano** [comment]
Gracias! Por lo que estoy cachando los de la sección 1 no recibimos el link con la clase

**Comment by alanezz** [comment]
Hola,

Perdón, pero por error postee el anuncio dos veces en la sección Juan en vez de una vez en cada sección. Nos vemos a las 17:00 en la clase.

Saludos y perdón por tan poco.
