### ISSUE TITLE
input type=text accidentalmente desabilitado?

### ISSUE THREAD

**Issue by ChayoPerez** [IIC2413/Syllabus-2020-1#222]
Hola!

Por alguna razón, en el código puesto abajo, si bien se ven las cajitas de los input, no dejan que se escriba nada :(
Qué podría ser? Agradecería mucho la ayuda.

```
<table>
  <tr>
    <td style="padding-right:100px">
      <img src="../Images/ticket-transporte.png">
    </td>
    <td> <form action="compra_transporte.php" method="post" id="plan_transporte">
          <br><br><br><br>
          Ciudad de origen: 
          <input type="text" name="origen" id="origen"><br><br>
          Ciudad de destino:
          <input type="text" name="destino" id="destino"><br><br>
          Vía de transporte:
          <input type="text" name="via" placeholder="(avión/tren/bus)" id="via"><br><br>
          Fecha del viaje:
          <input type="date" name="fecha" id="fecha">
          <br><br>
          <input class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored mdl-js-ripple-effect" type="submit">
        </form>
    </td>
  </tr>
</table>
```

**Comment by arpincheira** [comment]
Hola, una consulta, lograste arreglar tu problema? De lo contrario me podrías indicar tu grupo? 

Lo que pasa es que probando localmente el código html que pusiste no encontré ningún problema, así que necesito eso para poder analizar tu caso más específicamente.

Saludos.

**Comment by ChayoPerez** [comment]
Lo arreglé pero no sé cómo @_@ me da miedo tocarlo más. Si vuelve el error lo posteo aquí! Graciaas

**Comment by ChayoPerez** [comment]
Volví a tener un problema similar!

```
<h5>Elige un asiento:</h5>
<br><br>
<form action="compra_transporte3.php">
  <select id="cars" name="cars">
    <option value="volvo">Volvo</option>
    <option value="saab">Saab</option>
    <option value="fiat">Fiat</option>
    <option value="audi">Audi</option>
  </select>
  <input type="submit">
</form>

```

El select no see puede seleccionar, ni tampoco el texto "Elige un asiento"

http://codd.ing.puc.cl/~grupo46/Pages/compra_transporte2.php/?id_transporte=46

**Comment by fjlopez7** [comment]
El problema se puede deber al css que tiene la página. Para comprobar que es eso saca o comenta el tag link que va al css.
