### ISSUE TITLE
Problema con notebook psycopg2

### ISSUE THREAD

**Issue by etoteiza** [IIC2413/Syllabus-2020-1#225]
Hola!

Al tener uso del notebook de psycopg2, y ejecutar el primer bloque de código me aparece el siguiente error: `OperationalError: fe_sendauth: no password supplied`, no encuentro mucho al respecto, por lo que por eso pongo esta issue. Saludos!

**Comment by MarceloSaldias** [comment]
Hola!
Que sistema operativo usas?
En [esta](https://github.com/IIC2413/Syllabus-2020-1/wiki/PostgreSQL-y-psycopg2) guia se menciona que por defecto pueden dejar el argumento `password` como un string vacío. 
Si con eso no te funciona, lo mas probable es que la base de datos haya quedado protegida con alguna contraseña. Las opciones en ese caso son crear una base de datos nueva que sepas que no tiene contraseña, o bien intentar con la contraseña de tu usuario en el computador o alguna que hayas usado en la instalacion de postgres
