### ISSUE TITLE
Problema postgres

### ISSUE THREAD

**Issue by jperalta2202** [IIC2413/Syllabus-2020-1#227]
Hola, estoy teniendo problemas para correr postgres de manera local. Este problema lo tania hace tiempo pero como al trabajar en el proyecto usábamos el servidor no lo solucione en ese entonces. 

al ejecutar el comando psql en mi terminal, me sale el error "error: could not connect to server: FATAL: role "miusuario" does not exist"

**Comment by arpincheira** [comment]
Hola,
 el problema que estás teniendo actualmente se debe a la falta de un usuario de postgress. El usuario de postgress es aquel que tiene los permisos para poder crear tablas, otros usuarios, editar tablas u otro, por lo que postgress al no encontrar un ente que sea capaz de realizar estas acciones simplemente no te estaría dejando usarlo.

Para poder resolver este problema te recomiendo revisar aquello que dicen [aquí](https://stackoverflow.com/questions/15301826/psql-fatal-role-postgres-does-not-exist), si tu problema persiste por favor coméntalo en la issue y comenta también tu sistema operativo.

Espero haberte ayudado.

**Comment by jperalta2202** [comment]
No me sirvió lo que sale en el link, tengo windows.

**Comment by arpincheira** [comment]
Hola nuevamente,
no me manejo mucho con el uso de postgress a través de windows, pero buscando encontré [este post](https://stackoverflow.com/questions/28276706/postgresql-error-fatal-role-username-does-not-exist) que podría serte de utilidad. En el foro indicado básicamente acceden al usuario de postgres que se estaría creando por defecto para poder crear otros usuarios.


P.D. : [Aquí](https://github.com/PostgresApp/PostgresApp/issues/313) hablan sobre una solución posible, en una de esas te sirve, especialmente si lo anterior no te funciona.
Espero que te sirva.

**Comment by jperalta2202** [comment]
Ahi me resulto! gracias
