### ISSUE TITLE
Método get_next_tuple actividad 2

### ISSUE THREAD

**Issue by tomasalvarez13** [IIC2413/Syllabus-2020-1#229]
Hola, quería preguntar que debe retornar el método `get_next_tuple`, cuando no hay ninguna tupla más adelante (por ejemplo si me encuentro en la última tupla de la última página).
Gracias.

**Comment by ChayoPerez** [comment]
Yo retorné None

**Comment by TamaraCucumides** [comment]
Retornar None está bien, pueden printear algun mensaje si quieren, mientras se entienda que no hay otra tupla está ok :D

**Comment by benjaurr** [comment]
En el caso que no haya un siguiente una siguiente tupla, donde debe quedar seteado el current_block?

**Comment by TamaraCucumides** [comment]
@benjaurr queda a tu criterio, mientras la función explicite de alguna manera (retornando None o printeando algo) que no encontró otra tupla, está ok.

**Comment by benjaurr** [comment]
Gracias!
