### ISSUE TITLE
Duda Repositorio Personal

### ISSUE THREAD

**Issue by constanzacontreras** [IIC2413/Syllabus-2020-1#23]
Hola!, Tengo dos dudas
1) Cree un repositorio personal y hice lo que salía en las instrucciones con el repositorio local, pero al momento de tratar de subir un archivo me sale este error. 
![Captura de pantalla 2020-03-21 22 47 09](https://user-images.githubusercontent.com/48296666/77240557-1d731780-6bc6-11ea-82d0-7b1a8d95202c.png)

2)También al momento de crear un repositorio personal puse que tuviera el Readme, pero despues en las instrucciones que busque salia que debía crearlo después por lo que lo borre directamente de Github, nose si eso influye ya que no lo borre desde el terminal, de todas formas en ese momento no había clonado el repositorio. 

Muchas gracias!

**Comment by ridiazcampos** [comment]
¡Holaaa!

**Respecto a la primera pregunta:**
Al parecer no se han encontrado diferencias entre al repositorio local y el remoto, sin embargo, comenta que _.DS_Store_ aún no tiene seguimiento (aparece como _untracked_).

Puede ser útil intentar agregar el archivo que quieres manualmente con `git add nombre_archivo` antes de hacer _commit_. En el caso de que _.DS_Store_ no sea el archivo que quieres subir (y no sea necesario hacerlo), puedes agregarlo al _.gitignore_ para que esta línea de error no aparezca nuevamente 😊.

Quizás lo anterior ya lo hiciste! Si no funciona, puedes usar `git status` para ver el estado actual de tu versión local (en qué rama se encuentra el repositorio local, si hay alguna actualización desde el remoto, si falta hacer commit, entre otros). Nos puedes comentar por aquí qué aparece para ver qué podríamos hacer!

Traté de hacer lo mismo que comentas, y al hacer push me dio un error (al parecer de conflicto) que se pudo solucionar gracias a [esta página](https://stackoverflow.com/questions/11696295/rejected-master-master-non-fast-forward) (utiliza git pull --rebase). No estoy al tanto de si esto podría solucionar lo que ocurre en tu versión local, estaré atento! (*)


**Respecto a la segunda pregunta:**
Borrar el Readme no debería ser problema :D tampoco crearlo antes o después! [Según este sitio](https://stackoverflow.com/questions/30758784/how-does-initializing-a-repository-with-a-readme-help-in-letting-you-immediately), puede que si se crea el repo sin el readme, sea necesario mencionar la rama a la que se desea hacer referencia (algo como lo que se menciona en el tutorial!).

Saludos!

(*) En caso de que en la carpeta local haya algún archivo que crearon y que sirva para la entrega, recomendaría respaldarlo en algún lugar!

**Comment by constanzacontreras** [comment]
Muchas gracias por la respuesta!
Al final si pude agregar un archivo al repositorio personal, también hicimos un archivo git ignore. Al meternos a nuestro repositorio local para hacer pull , nos sale lo siguiente:

![Captura de pantalla 2020-03-22 18 42 26](https://user-images.githubusercontent.com/48296666/77261943-f887ae80-6c70-11ea-8e4e-8d0ce1ee8194.png)


En el tutorial dice que debemos especificar a que rama debe sincronizarse, pero no entendemos como hacerlo.

Muchas gracias

**Comment by ridiazcampos** [comment]
¡Genial que ya se puede agregar, y que ya funcione .gitignore!
Ahora, para especificar la rama que quieren sincronizar, pueden intentar con lo que se menciona ahí, quedaría como:
`git branch --set-upstream-to=origin/master master`

Luego `git pull` de nuevo!

Si quieren nos comentan de nuevo por aquí si eso funciona! Podemos buscar otras soluciones de no funcionar :D

**Comment by lisraelrat1** [comment]
No nos funcionó :(
Nos tira este error: fatal: branch 'master' does not exist
Feliz si nos pueden ayudar a encontrar otra forma de solucionarlo

**Comment by ridiazcampos** [comment]
Oh, ya! :D 
Edit: Pueden intentar con:
`git pull origin master`
`git branch --set-upstream-to=origin/master master`
Es decir, hacer esa especie de git pull indicando la rama! 

------------------------------------------------------------------------------------------
En el caso de que el edit no funcione, pueden intentar escribir `git remote -v`, y revisar si aparecen dos líneas del estilo:
`origin  https://github.com/<user>/<repositorio> (fetch)`
`origin  https://github.com/<user/<repositorio> (push)`

Si esto aparece así, puede que esté en orden, entonces el único problema es que no encuentra la rama _master_, en ese caso pueden intentar con `git checkout master` que podría solucionar el problema!

-------------------------------------------------------------------------------------------
Estaremos al tanto!

Referencias: [1 👀](https://stackoverflow.com/questions/46915350/got-fatal-branch-master-does-not-exist-in-git) [2 😊](https://stackoverflow.com/questions/26281767/run-command-git-branch-set-upstream-to-produce-error/42305655)
Y a @nivek0o0, gracias por el dato solucionador!

**Comment by lisraelrat1** [comment]
Nos funcionó!! Muchas gracias :)

**Comment by ridiazcampos** [comment]
¡Wujuuu! Cualquier otra cosa nos pueden comentar (:

¡Mucho éxito con las entregas! 😄

**Comment by constanzacontreras** [comment]
Perdón por seguir con estas preguntas jaja, pero ahora en el repo local todo bien, pero al meterme a nuestro repositorio privado, y al hacer un pull (ya que mi compañera agregó un .gitignore), y al hacer un git status, me aparece esto, y no entiendo porque..
![Captura de pantalla 2020-03-22 20 29 23](https://user-images.githubusercontent.com/48296666/77265696-245c6180-6c7c-11ea-9460-5f786b116ee3.png)

Traté de solucionarlo haciendo git add .DS_Store pero no funcionó. En cambio a mi compañera le funciona bien.

Muchas gracias!

**Comment by constanzacontreras** [comment]
Intente de nuevo y me sale ahora esto:
![Captura de pantalla 2020-03-22 20 37 20](https://user-images.githubusercontent.com/48296666/77265977-f7f51500-6c7c-11ea-8b10-150e8ad04d51.png)

No entiendo a que se refiere

Gracias!

**Comment by ridiazcampos** [comment]
No hay problema en que sigan comentando! 
Al parecer se resolvieron ciertos conflictos al hacer _merge_ ("mezclar" dos versiones de un archivo, por ejemplo, desde la versión remota con la local), pero falta hacer `git commit` para que concluya este proceso. Pueden intentar entonces con un _commit_, y luego `git pull` para ver si es posible en esta oportunidad, si no, podemos seguir investigando!

**Comment by constanzacontreras** [comment]
Al hacer un git commit, me aparece lo siguiente; error: Committing is not possible because you have unmerged files.

**Comment by constanzacontreras** [comment]
intente usar eso: https://stackoverflow.com/questions/11646107/you-have-not-concluded-your-merge-merge-head-exists
Pero no me funcionó con merge abort

**Comment by ridiazcampos** [comment]
Al parecer aún hay archivos en conflictos! Qué archivos son distintos entre la versión local y la remota? Si encuentran alguno, es posible solucionarlo manualmente abriéndolo con algún editor de texto, podrán notar una estructura así en algunas partes:

```
<<<<<<< HEAD

# Esto es lo que aparece en la versión local.

===========

# Esto es lo que aparece en la versión remota.

>>>>>>> (posiblemente código de commit)
```

Entonces pueden borrar los <, > e =, eligiendo qué parte del archivo quieren dejar definitivamente!

Si no encuentran archivos en conflicto, nos pueden comentar! Buscaré si puede existir alguna otra razón para el error.

Por cierto, otra manera -quizás no la ideal, pero puede funcionar sobre todo si no tienen muchos archivos con cambios importantes para la entrega- podría ser mover los archivos locales a otra carpeta, y luego hacer git pull, entonces no deberían haber conflictos!

**Comment by constanzacontreras** [comment]
Creo haberlo solucionado! Hice un -rm .DS_Store en mi repositorio personal, y con eso se arregló, hice un git pull, y luego git status 
![Captura de pantalla 2020-03-22 21 02 37](https://user-images.githubusercontent.com/48296666/77267295-f0376f80-6c80-11ea-89a7-169cfe2f947e.png)

Creo que deberia estar bien asi... jajaja
Muchas gracias!

**Comment by nivek0o0** [comment]
Creo que el error se produjo porque tu hiciste un commit donde agregabas el archivo .DS_Store y tu compañera hizo lo mismo (con su propio .DS_Store). Entonces los repositorios divergieron.

Por eso es recomendable primero ignorar esos archivos inútiles en un `.gitignore` y luego hacer pulls y pushs.

De todas formas, cualquier problema que surja debería ser fácil de resolver siguiendo los consejos que el mismo git te entrega entre paréntesis y comillas.

Por último, git te dice que tienes 2 commits sin pushear, te recomiendo pushearlos y trabajar cuando el `git status` te diga solamente "Already up-to-date"

**Comment by constanzacontreras** [comment]
Muchas gracias! yo creo que eso era.., acabo de hacer un git push y ahí se arregló lo que me dijiste, gracias. Una pregunta, cuando subamos la tarea la subimos a nuestra repo privada, con git add, commit, push, y luego nos metemos a nuestra repo remota y solamente una hace git pull? o ambas?

Gracias!

**Comment by nivek0o0** [comment]
El repositorio remoto es uno solo y lo maneja Github.
Repositorios locales pueden haber muchos, como los computadores de cada integrante del grupo y como **el servidor**. Sí, la carpeta en el servidor también es un repositorio local que se sincroniza al remoto de Github.

Entonces, para subir una tarea, cualquier integrante del grupo puede hacer `add, commit, push` en su repositorio local y con eso sincronizan el remoto.
Luego se conectan al servidor del curso (**codd.ing.puc.cl**) y hacen `git pull` (para sincronizarlo con el remoto) y listo.

¿Se entiende? :confounded:

**Comment by ridiazcampos** [comment]
Algo así! 😄

![image](https://user-images.githubusercontent.com/37166300/77270495-dbf87000-6c8a-11ea-8efe-2dc411891157.png)

**Comment by constanzacontreras** [comment]
Buenisiima muchas gracias! Te pasaste

**Comment by constanzacontreras** [comment]
*Se pasaron!
