### ISSUE TITLE
Duda actividad 2 parte 2 Poblar el diccionario

### ISSUE THREAD

**Issue by JuaniAndres** [IIC2413/Syllabus-2020-1#230]
Hola no me quedo muy claro en que minuto hay que poblar el diccionario si es antes de la definición de las funciones o dentro de cada una?
Gracias de antemano

**Comment by TamaraCucumides** [comment]
Como ya vas a tener ciertas tuplas dentro de tu tabla, al ejecutar las funciones estas ya debiesen estar en el diccionario. Así que lo lógico sería poblarlo antes.

**Comment by oscars810** [comment]
Si yo lo hago antes, entonces porqué en search_with_index me pasan una instancia de ArtWork?... Mi duda es que voy a poblar mi hash_index con una instancia que yo voy a crear, y como cada vez que se crea una instancia se desordenan los datos, mi hash index no va a tener ninguna relacion con la instancia que se me entrega. Por ende no sé que hacer con esa instancia 😢 

Espero se haya entendido la pregunta

**Comment by JuaniAndres** [comment]
@TamaraCucumides No me quedo claro una cosa leyendo también la otra issues sobre el tema con poblarlo antes te refieres a dentro de ambas funciones hacemos un pre proceso por llamarlo de una manera que seria llenar el dic con todas las tuplas de la tabla entregada luego como segundo paso hacemos lo que nos piden que seria buscar una tupla o insertarla según corresponda?
Lo otro no importa si modificamos la posición del puntero de la tabla osea que no quede en donde estaba originalmente?

**Comment by TamaraCucumides** [comment]
Hola, no entiendo muy bien el problema. ¿A qué te refieres con que al crear una nueva instancia se desordenan los datos? Recuerda que los datos NO están ordenados, porque el indice es unclustered.

**Comment by oscars810** [comment]
A lo que me refiero cuando digo que se desordenan los datos es que cuando creo una nueva instancia una obra que estaba en la pagina 1 puede estar en la pagina 3, por lo que como dices, los datos estan desordenados. Por ende, mi hash_index tiene que ser creado en función de la instancia en particular que se usa por cada funcion.
Por lo tanto, las funciones se van a usar en contextos independientes y no entiendo como podría crear el hash_index fuera de la función si no voy a tener la instancia en particular.

**Comment by TamaraCucumides** [comment]
Por qué dices que al crear una nueva instancia te cambian de orden las tuplas? 

> cuando creo una nueva instancia una obra que estaba en la pagina 1 puede estar en la pagina 3

Esto no debería pasar, intenta crear varias instancias
```
obras1 = Artwork('o-1')
obras2 = Artwork('o-1')
```
y podrás ver que las tuplas se mantienen en las mismas paginas y posiciones.

**Comment by oscars810** [comment]
Oh, toda la razón! :o 
Lo que pasaba era que cada vez que creaba una instancia ponia la funcion ``create()`` y por eso se me desordenaban los datos.

Gracias por la aclaración, ya entendí como hacerlo! 🤟

**Comment by juansjimenez** [comment]
Una pregunta! Por qué entonces nos dan una instancia de la clase en **search_with_index**? Si al final se puede hacer creando una instancia adentro de la funcion como dice el enunciado, termine la funcion sin nunca utilizar la instancia que recibe.

**Comment by TamaraCucumides** [comment]
Hola, no es necesario que uses la instancia que te llega como argumento en la función.

**Comment by FeBalla** [comment]
Una pregunta con respecto a lo último, se puede poblar el hash_index con una instancia cualquiera?, es que que pasa si a la instancia que me dan se le añadieron tuplas que a la que usé para poblar el diccionario no se le añadieron?

**Comment by TamaraCucumides** [comment]
Para poblar el diccionario debes usar las tuplas presentes en las páginas. La idea es que dentro de alguna función o en alguna celda, iteres sobre las paginas usando los métodos de ArtWork y vayas añadiendo las cosas al diccionario, así tu solución funcionara para cualquier instancia y no solo la particular del ejemplo (la idea no es que puebles el diccionario "a mano" con los datos que te pasamos).  

Recuerda que para esto puedes asumir que la primera pagina se llama "o-1"

**Comment by JuaniAndres** [comment]
Una pregunta respecto a eso digamos que poblé el hash_index con lo que tenían las paginas del disco con una instancia nueva de artwork table llamada tabla1 luego hago tabla1.insert_into_table(99,"La mejor obra")
Si yo hago tabla1.search_with_index(hash_index,tabla1,99) debería poder encontrar esa tupla o solamente las tuplas que yo ingrese posteriormente con insert_with_index?
