### ISSUE TITLE
Dudas actividad 2 parte 1

### ISSUE THREAD

**Issue by danustilovsky** [IIC2413/Syllabus-2020-1#231]
Hola, tratando de hacer la actividad me surgieron ulgunas dudas:
1. En la funcion 'has_next_tuple' es necesario hacer que al terminar de ejecutarse se devuelva el puntero al bloque en el que se estaba?
2. En la funcion 'insert_into_table', en caso que el id entregado ya exista en la tabla, que se debe hacer?  Se cambia por otro o simplemente no se hace nada?
3. Para 'get_tupple_by_id'  en caso de no  exista la tupla, se debe dejar el puntero al final de la tabla?
4. para  'get_all_elements_from_table'  es relevante donde se deja el puntero al terminar de imprimir las tuplas?

Gracias

**Comment by TamaraCucumides** [comment]
1. La idea sería quedarse en el lugar
2. No hacer nada, el id es llave primaria asi que no puedes insertar el elemento en cuestión. Si quieres puedes imprimir un error. 
3. No necesariamente
4. No
