### ISSUE TITLE
Poblar hash_index

### ISSUE THREAD

**Issue by FeBalla** [IIC2413/Syllabus-2020-1#232]
¿Con la instancia _ArtworkTable_ que nos dan en las funciones poblamos el hash_index?
¡Gracias!

**Comment by TamaraCucumides** [comment]
Si, esa es la idea

**Comment by FeBalla** [comment]
Pero me queda una duda, porque finalmente para poblar el _hash_index_ igual tengo que recorrer toda la relación, ¿o da lo mismo ese detalle?

**Comment by TamaraCucumides** [comment]
Toma ese paso como un pre-procesamiento. Lo importante es que después para buscar tuplas, no recorras toda la tabla.

**Comment by FeBalla** [comment]
Último que te molesto (lo siento:c). Es que hasta al menos como lo entendí yo, estoy poblando el _hash_index_ cada vez que llaman a la función (usando otra función diferente), porque no sé a priori si siempre serán las mismas tuplas o si han agregado más, ¿eso está bien?, porque me causa dudas ya que, en teoría, queríamos poblarlo antes de la función.

**Comment by TamaraCucumides** [comment]
O sea, cada vez que agregas una tupla tienes que actualizar el diccionario hash_index. Entonces la idea es 
1) Poblamos hash_index inicialmente con las tuplas que ya estan en la tabla
2) cada vez que insertamos, agregamos el nuevo id:pag al hash index

Siguiendo ese orden nunca deberia pasar que alguna tupla este en la tabla y no en el diccionario. Se entiende?

**Comment by tsgonzalez** [comment]
De todas maneras se debe verificar si el id existe revisando si el id está en las keys del hash_index verdad? 
En ese caso, puedo hacer un defaultdict que me entregue un valor None dado un id que no está en el hash_index?

**Comment by TamaraCucumides** [comment]
@tsgonzalez sii, no hay problema con eso.
