### ISSUE TITLE
Duda Procedimientos Almacenados Entrega 3 Proyecto

### ISSUE THREAD

**Issue by rodobkn** [IIC2413/Syllabus-2020-1#233]
En la parte de procedimientos almacenados tengo una duda.

En php se puede conectar a las dos bases de datos para hacer las consultas a las dos bases de datos, sin embargo, en el archivo .sql que se debe crear en una base de datos determinada para realizar el procedimiento almacenado, como puedo usar las tablas de la base de datos del otro grupo?

Puesto que no hay problemas al usar las tablas de la base de datos en donde está el archivo .sql del procedimiento almacenado, pero como hago la referencia en lenguaje PL/pgSQL que voy a utilizar las tablas de la base de datos del otro grupo al que se nos unió?

Hay algún tipo de conexión como se hace en php, sólo que en  lenguaje PL/pgSQL?

Espero hayan entendido mi pregunta.

**Comment by nivek0o0** [comment]
Hola, la función que andas buscando se llama [dblink](https://www.postgresql.org/docs/10/contrib-dblink-function.html), y te servirá para establecer una conexión y ejecutar consultas entre bases de datos.

**Comment by bahidalgo** [comment]
Hola! 
Con respecto a este tema, he intentando utilizar la función dblink para cruzar bases de datos buscando en internet y lo último a lo que llegué era que necesitaba crear la extensión, sin embargo, me pide condición de superuser para hacerlo. Ahora no entiendo si ese no es el camino o si me falta hacer algo. 
Por otro lado, ¿se espera que realice solo un archivo .sql donde se realice todo el itinerario? ¿o puedo utilizar múltiples archivos de procedimiento almacenado?
Muchas gracias!

**Comment by nivek0o0** [comment]
@bahidalgo Todas las funciones dblink están creadas en la BD desde siempre.

**Comment by bahidalgo** [comment]
Hola, disculpa por insistir tanto con el mismo tema, pero no logro resolver esto.
He tratado de usar la función de todas las formas posibles que encontré en Internet y me sale el mismo error siempre del estilo:
`ERROR:  function dblink(unknown, unknown) does not exist`
Buscando en google, encontré varias páginas que hablaban al respecto, pero la mayoría insistía en crear la extensión. Lo único que logré obtener lo muestro en la imagen adjunta, en donde la primera tabla proviene de escribir:
`select * from pg_extension;`
Y la segunda tabla al usar:
`select * from pg_available_extensions;`
Por una parte, no entiendo cómo se accede a las funciones que están dentro sin tener instalada la extensión y por otra parte, he usado dblink, dblink_connect y dblink_connect_u y me sale el mismo error.

![dblink](https://user-images.githubusercontent.com/48327186/82637698-52eeae00-9bd3-11ea-9299-ece9d3f9daf1.png)

**Comment by nivek0o0** [comment]
Hola @bahidalgo 
Puedes revisar en las bases de datos `grupo46e2` o `grupo46e3`, que son las que ocupamos para esta entrega del proyecto?

**Comment by bahidalgo** [comment]
Ayer me había metido a grupo46e3 y grupo69e3 a probarlo y no funcionaba, pero ahora si! No sé qué hiciste pero muchas gracias, llevaba una semana sin poder avanzar, mil gracias!!!

**Comment by carajila** [comment]
Hola!
Al utilizar la función dblink para realizar consultas entre bases de datos no da resultado. 
La consulta que realizamos es la siguiente:

![image](https://user-images.githubusercontent.com/42160512/82744445-af260f00-9d46-11ea-8239-f0556862fa75.png)

No se si estamos utilizando mal la función (la consulta si da resultado sola y la tabla Entradas no está vacía), pero no nos conecta las bases de datos. 

Al parecer hay un error del tipo: Fatal error: Uncaught Error: Call to undefined function dblink()

Gracias

**Comment by rociomartineza** [comment]
Hola, a mi tambien me sale lo del superuser. Como puedo arreglarlo?

**Comment by nivek0o0** [comment]
Estás segura?
La extensión `dblink` está instalada en todas las bases de datos **e2** y **e3** de todos los grupos.

Podrías pegar una imagen del error?

**Comment by rociomartineza** [comment]
Aaa que pava. Si, acabo de cachar que me estaba metiendo a otra base de datos, gracias.

**Comment by rociomartineza** [comment]
Estoy tratando de hacer dblink_connect_u desde el grupo1 a la base de datos grupo22e3 pero me sale este error:
ERROR:  permission denied for function dblink_connect_u
CONTEXT:  SQL statement "SELECT dblink_connect_u('testconn', 'dbname=grupo22e3 user=grupo22')"

he buscado harto en internet pero nada me funciona.

**Comment by rociomartineza** [comment]
@nivek0o0 tambien trate esto:
grupo1e3=> SELECT dblink_connect_u('testconn', 'host=codd.ing.puc.cl port=5432 dbname=grupo22e3 user=grupo22 password=grup
o22');
ERROR:  permission denied for function dblink_connect_u
grupo1e3=> GRANT EXECUTE ON FUNCTION dblink_connect_u(text, text) TO grupo1;
ERROR:  permission denied for function dblink_connect_u
grupo1e3=> GRANT EXECUTE ON FUNCTION dblink_connect_u(text) TO grupo1;
ERROR:  permission denied for function dblink_connect_u

**Comment by nivek0o0** [comment]
@rociomartineza intenta con `dblink_connect` o simplemente `dblink`. (Yo intenté desde tu BD y me funcionó).

La función que estás usando está bloqueada por defecto porque es una forma de conexión insegura.

[Documentación](https://www.postgresql.org/docs/10/dblink.html).
