### ISSUE TITLE
Actividad 2:  del_tuple_by_id

### ISSUE THREAD

**Issue by ChayoPerez** [IIC2413/Syllabus-2020-1#234]
Hola! Estaba haciendo el bonus y  sin querer, usando `self.set_empty_on_page()` le hice este horror a mi archivo:

```
0x32 0x2c 0x4c 0x61 0x20 0x6d 0x6f 0x6e 0x61 0x20 0x6c 0x69 0x73 0x61
0x31 0x30 0x2c 0x45 0x6c 0x20 0x6a 0x75 0x69 0x63 0x69 0x6f 0x20 0x66 0x69 0x6e 0x61 0x6c
<EMPTY>
0x31 0x31 0x2c 0x45 0x6c 0x20 0x4d 0x6f 0x69 0x73 0xe9 0x73
0x39 0x2c 0x4c 0x61 0x20 0xfa 0x6c 0x74 0x69 0x6d 0x61 0x20 0x63 0x65 0x6e 0x61
<EMPTY>
```
Mató totalmente la parte donde se conecta a los otros. Sin hacerme la tarea por supuesto, me podrían decir cuál es la lógica de lo que pasó aquí? 

Gracias!

**Comment by TamaraCucumides** [comment]
Hola, por error borraste el puntero de tu pagina actual a la página siguiente. 

Como hint: ten ojo dónde tienes el puntero al usar `self.set_empty_on_page()`

**Comment by ChayoPerez** [comment]
Genial, gracias! Voy a tener más ojo
