### ISSUE TITLE
Insert_with_index

### ISSUE THREAD

**Issue by danustilovsky** [IIC2413/Syllabus-2020-1#235]
Hola, en la funcion insert_with_index se debe utilizar el index para revisar que el index ingresado no exista en la tabla, y luego si no existe se recorre el arbol entero para ver donde se debe insertar y en caso de no haber espacio, se crea una nueva pagina? O si se debe contar cuantos elementos hay de la misma pagina en el hash_index para asi saber en que pagina se debe insertar la tupla, sin recorrer el arbol?
Mi duda es si se mantiene la logica del insert de la parte 1, solo que se puede optimizar la revision de la clave?

gracias

**Comment by TamaraCucumides** [comment]
Hola, se mantiene la lógica del insert de la parte uno y, como mencionas, la única diferencia es optimizar la revisión del id.
