### ISSUE TITLE
Duda sobre el bonus por imágenes en el proyecto

### ISSUE THREAD

**Issue by JuaniAndres** [IIC2413/Syllabus-2020-1#237]
hola estaba pensando el bonus y queria saber si se puede crear una tabla adicional aparte o agregarle un  atributo  a las obras/lugares/artistas para guardar el url de la imagen ya que dice que no se deben almacenar esas imagenes en el servidor?
Gracias de antemano

**Comment by nivek0o0** [comment]
Hola, sí, pueden modificar su DB a su gusto para lograr cualquier funcionalidad.

**Comment by JuaniAndres** [comment]
yap gracias
