### ISSUE TITLE
Entrega 3 Proyecto por semana de receso

### ISSUE THREAD

**Issue by crow-rojas** [IIC2413/Syllabus-2020-1#238]
¡Hola!

La fecha de la entrega 3 del proyecto, ¿quedará afectada por la semana de receso que empieza el 25 de mayo? ¿O se mantiene para ese mismo día?

¡Saludos!

**Comment by crow-rojas** [comment]
Medio visto que me dejaron :(

**Comment by SarahEverke** [comment]
Hola, quedó para el 1 de Junio #246

**Comment by crow-rojas** [comment]
Gracias <3
