### ISSUE TITLE
Duda insert_with_index

### ISSUE THREAD

**Issue by ChayoPerez** [IIC2413/Syllabus-2020-1#239]
Tengo una pregunta sobre insert_with_index(hash_index, artwork_table, id_artwork, name_artwork)
Si ya hay una tupla en ese index, tengo que reemplazarla por la nueva? O mando un mensaje de que el espacio está ocupado?

Gracias!

**Comment by TamaraCucumides** [comment]
Hola, lo segundo. Al final estás intentando insertar una tupla con un id ya existente, por ende, no deberías insertarla. Ahí tu decide si retornas o imprimes algo que explicite el error.
