### ISSUE TITLE
Duda países visitados

### ISSUE THREAD

**Issue by FeBalla** [IIC2413/Syllabus-2020-1#24]
Para la entrega ,¿consideramos un país como visitado a aquel donde hay un ticket de vuelo asociado o aquellos donde haya una reserva de hotel asociada?

**Comment by fhohlberg** [comment]
Hola!

Pueden verlo como los destinos de tickets por cualquier medio de transporte en que la fecha de viaje ya pasó y las reservas de hoteles cuyo periodo de reserva ya empezó o terminó.

Espero haber aclarado tu duda!

Saludos

**Comment by fhohlberg** [comment]
Pd: para saber la fecha actual, pueden utilizar fecha.hoy() o alguna fecha arbitraria como la fecha de entrega.

**Comment by FeBalla** [comment]
Pero, ¿cómo podríamos hacer una operación que nos indique si la fecha ya pasó o no?, ya que hasta donde se nos ha enseñado la fecha la manejamos como un _string_, entonces no sé si sería válido que estableciéramos una condición de este estilo, por ejemplo: "reserva,fecha <= fecha.hoy()". ¿Es esto válido?

**Comment by FeBalla** [comment]
> Pero, ¿cómo podríamos hacer una operación que nos indique si la fecha ya pasó o no?, ya que hasta donde se nos ha enseñado la fecha la manejamos como un _string_, entonces no sé si sería válido que estableciéramos una condición de este estilo, por ejemplo: "reserva,fecha <= fecha.hoy()". ¿Es esto válido?



> Pero, ¿cómo podríamos hacer una operación que nos indique si la fecha ya pasó o no?, ya que hasta donde se nos ha enseñado la fecha la manejamos como un _string_, entonces no sé si sería válido que estableciéramos una condición de este estilo, por ejemplo: "reserva,fecha <= fecha.hoy()". ¿Es esto válido?

**Comment by nivek0o0** [comment]
Sí es válido comparar fechas con operadores de desigualdad.

**Comment by FeBalla** [comment]
Última pregunta: ¿las fechas son del tipo string o de algún tipo diferente?

**Comment by fhohlberg** [comment]
Las fechas son de tipo date o datetime. Saludos
