### ISSUE TITLE
Idea de proyecto

### ISSUE THREAD

**Issue by perezpefaur** [IIC2413/Syllabus-2020-1#241]
Hola, aunque sé que nos dan una libertad para hacer el proyecto, quería saber cual era la intención detrás de esta entrega, refiriendome a que si querían que programaramos solo en php o también incluyamos python.  Para orientarnos un poco a como abordamos esta entrega.

**Comment by nivek0o0** [comment]
Hola, esta entrega es 100% en PHP.
