### ISSUE TITLE
Poblar diccionario pregunta 2.2 actividad

### ISSUE THREAD

**Issue by juansjimenez** [IIC2413/Syllabus-2020-1#242]
Hola! En esta pregunta **insert_with_index()** se menciona que se tiene que tener un diccionario que funcione como indice para poder referenciar en que página se encuentran las tuplas con id. La función debe "insertar la tupla en la tabla y actualice el índice con el nuevo valor". Sin embargo, mi implementación es que tengo una función auxiliar que se encarga de poblar un diccionario que retorna. Por ende, esta bien si **insert_with_index()** es básicamente lo mismo que **insert_into_table()** de la parte 1, pero ahora se revisa si es que la tupla esta con las keys del diccionario? A lo que me refiero es que, esencialmente mi función **insert_with_index()** no actualizará el diccionario index, si no que al insertar una tupla y generar el diccionario nuevamente con la función auxiliar que lo retorna cada vez que es llamada se encarga de leer la tabla y generar un diccionario, por ende este siempre estará actualizado cuando se llame.
Es válido esto? O tengo que tener necesariamente un diccionario afuera que se genera una vez globalmente con una instancia específica de la clase ArtworkTable y que luego tengo que ir cambiando?

**Comment by TamaraCucumides** [comment]
Hola, si es válido pero no es muy eficiente generar todo el hash_index desde 0 cada vez que insertas 1 elemento. Pero si funciona, está bien, no te preocupes :D

>  si insert_with_index() es básicamente lo mismo que insert_into_table() de la parte 1, pero ahora se revisa si es que la tupla esta con las keys del diccionario? 

La respuesta a esto es si, esa tiene que ser esencialmente la diferencia
