### ISSUE TITLE
Problema al utilizar INSERT INTO TABLE VALUES en php

### ISSUE THREAD

**Issue by bahidalgo** [IIC2413/Syllabus-2020-1#243]
Hola, al intentar agregar el nuevo usuario a la base de datos, la aplicación reconoce perfectamente si el usuario no existe y teóricamente crea la cuenta. Al utilizar lo siguiente:

````
$query_add = "INSERT INTO usuarios VALUES ($new_id, $nombre, $usuario, $correo, $direccion, $clave)";
    $result_add = $db_impar  -> prepare($query_add);
    $result_add -> execute();
````
Donde $new_id corresponde al id siguiente. Luego, al ver la tabla en la base de datos impar, no se encuentra la tupla extra y no entendemos la razón de ello. ¿Podrían ayudarnos por favor?

Saludos!

**Comment by nivek0o0** [comment]
Hola, tal vez la consulta falla porque no estás enviandole los strings entre comillas simples

**Comment by bahidalgo** [comment]
En efecto, muchas gracias!
