### ISSUE TITLE
Log in

### ISSUE THREAD

**Issue by perezpefaur** [IIC2413/Syllabus-2020-1#244]
A que se refiere una contraseña dummy? No es lo mismo que no tener contraseña?

**Comment by nivek0o0** [comment]
Una contraseña dummy es algo como **1234**.

Es muy distinto a no tener contraseña, porque implica que debes implementar un login y chequear que la contraseña ingresada en la página web sea igual a la almacenada en la BD.

**Comment by perezpefaur** [comment]
Pero es una misma contraseña para todos los usuarios? A que se refiere con dummy?

**Comment by nivek0o0** [comment]
Ahh si,
dummy = simple y la misma para todos.
