### ISSUE TITLE
Posible Supuesto

### ISSUE THREAD

**Issue by brayanmoreno** [IIC2413/Syllabus-2020-1#245]
es válido suponer que los nombres de los archivos para las paginas tendrán como ultimo carácter un dígito, ya que para crear una nueva página lo que hago es simplemente tomar el nombre de la última en cola y mantener el mismo, pero aumentar en uno su dígito final. Si lo anterior no fuera valido, supongo que sería necesario implementar un algoritmo más sofisticado, dado que es necesario evitar colisiones entre los nombres de las paginas, pero no creo que esto sea un objetivo del control.

**Comment by TamaraCucumides** [comment]
Hola, deja esto especificado en el readme :D
