### ISSUE TITLE
Creo tener un error en la Actividad 2

### ISSUE THREAD

**Issue by DonJavi-538** [IIC2413/Syllabus-2020-1#247]
Mientras trabajaba en la sección de insert_into_table cree una página o-4 que posteriormente borre de forma manual. Sin embargo, aunque solo tenga 3 páginas (o-1, o-2, o-3) el código piensa que next_page_name es o-4 una vez que se posiciona en o-4.

**Comment by TamaraCucumides** [comment]
Probablemente quedo instanciado el puntero a la pagina siguiente en "o-3"
