### ISSUE TITLE
Actividad 2 Parte 2 diccionario hash_index

### ISSUE THREAD

**Issue by franciscafdez** [IIC2413/Syllabus-2020-1#248]
Estuve revisando las issues, pero aun no me queda claro si se debe poblar el diccionario hash_index fuera de las funciones con una instancia que yo creo o si se debe hacer dentro de las funciones con las instancias que se entregan como parámetros cada vez que estas sean llamadas.
Gracias.

**Comment by TamaraCucumides** [comment]
Hola, 
para search_with_index NO ES NECESARIO utilizar la instancia que te pasan. 

El diccionario debes poblarlo con todas las tuplas que se encuentren dentro de los archivos "o-1", ...

Te recomiendo crear una funcion que haga esto, es decir que parta recorriendo la Tabla desde "o-1" añadiendo los elementos al hash_index. Esto **se hace 1 vez**, y luego el hash se va actualizando acorde a las inserciones
