### ISSUE TITLE
Conexion de php local a database del servidor

### ISSUE THREAD

**Issue by tomasalvarez13** [IIC2413/Syllabus-2020-1#249]
Hola, estoy corriendo la pagina de la entrega 3 en el localhost, y la conexion con la base de datos la hice usando la IP del servidor. Mi pregunta es si se puede hacer lo anterior,o puede causar problemas al correr la página desde el servidor (ya que en POD host ya no seria 'localhost').

Gracias!

**Comment by rafafdz** [comment]
Hola! No debería darte mayores problemas. De todas formas haz una prueba rápida para ver que ande bien. En el peor de los casos puedes desarrollar local y cuando estés listo vuelves a usa "localhost" como la IP de la base de datos.
