### ISSUE TITLE
Duda control 1 pregunta 2

### ISSUE THREAD

**Issue by vicerc** [IIC2413/Syllabus-2020-1#25]
Cuando preguntan por los los nombres de los clientes que pidieron algo de Vestuario y algo de Herramientas, ¿Se refieren a los clientes que compraron algo de Vestuario y a los clientes que compraron algo de herramientas o a los clientes que compraron de ambas categorías?

**Comment by ridiazcampos** [comment]
Holaaaa!
Esta consulta se referiría a la segunda opción, es decir, a quienes compraron ambas categorías :D (*)

Cualquier cosa nos comentas! Salu2 cordiales.
pd: 🥑

(*) Entonces, si por ejemplo alguien compró algo de Vestuario, pero no ha comprado nada de Herramientas, no debería aparecer como respuesta a la consulta😊 (agrego esto, porque mi respuesta seguía siendo ambigua jaja).

**Comment by vicerc** [comment]
Graciaaas <3
