### ISSUE TITLE
Como hacer referencia a una llave foranea de una tabla que no esta en la base de datos?

### ISSUE THREAD

**Issue by perezpefaur** [IIC2413/Syllabus-2020-1#250]
Cómo hacer referencia a una llave foránea de una tabla que está en la base de datos del otro grupo?
Me encuentro con este problema al crear la tabla de tickets museos que necesita necesariamente el id del usuario y el id del museo. Los dos son tablas que estan en distintas base de datos.

**Comment by fjlopez7** [comment]
Te puede servir lo que se dice en la issue #214 : 

"Por ejemplo si la funcionalidad que deben implementar dice que deben obtener las entradas del usuario con nombre "Pedro", entonces sería conveniente crearla en la BD impar para facilitar el JOIN. Si deben mostrar las entradas con el nombre del museo, sería útil crear la tabla en la BD par, porque ahí esta la tabla museos."

**Comment by JuaniAndres** [comment]
Hola pero respecto a las FK es posible crearlas de alguna manera entre dos tablas de distintas base de datos o simplemente no es recomendable.
Que almenos esa relación parece ser necesaria la funcionalidad para validar y eliminar en cascada

**Comment by nivek0o0** [comment]
Hola, no es posible crear FK entre bases de datos distintas.

En este caso la única alternativa es prescindir de la llave foránea, manejar los ID como números y hacer los joins a mano en PHP.

Recuerda que no es necesario eliminar en cascada, se dijo en una issue anterior.

**Comment by JuaniAndres** [comment]
yap gracias
