### ISSUE TITLE
El matching parcial para entrega 3

### ISSUE THREAD

**Issue by bahidalgo** [IIC2413/Syllabus-2020-1#251]
Hola,

¿Es necesario realizar esa funcionalidad para el proyecto? En caso de serlo, ¿cómo deberíamos responder al momento de seleccionar una ciudad de origen de un itinerario? (Por ejemplo, si ponen solo una vocal, dado que solo puede existir una ciudad de origen).

Muchas gracias!

**Comment by nivek0o0** [comment]
Hola, esta funcionalidad no es necesaria para esta entrega!
