### ISSUE TITLE
Corrección Proyecto Entrega 2

### ISSUE THREAD

**Issue by veneguitas** [IIC2413/Syllabus-2020-1#252]
Hola! Acabo de darme cuenta que estaban las notas de la Entrega 2, pero no entiendo a qué se refiere el corrector en el comentario que nos puso. Soy del grupo 2 y el comentario es el siguiente: "Guardaron juntos los distintos tipos de obras y lugares, lo que provoca que hayan NULLs".

**Comment by rafafdz** [comment]
Hola! Yo fui tu ayudante corrector. Con eso me refería a que si guardas en la misma tabla "Obras", instancias de  frescos, pinturas y esculturas, tendrás que rellenar con NULLs las columnas que cada una de estas entidades no poseen. Por ejemplo, si guardas una escultura, la columna técnica quedará con NULL porque las esculturas no tienen una técnica. (Solo las pinturas la tienen).
Y como ya revisaron en clases, tener NULLs no es una buena idea con SQL.
