### ISSUE TITLE
Corrección Proyecto Entrega 2

### ISSUE THREAD

**Issue by Paldana99** [IIC2413/Syllabus-2020-1#253]
Hola!
Tenia una duda de la correccion, nos pusieron: "Revisen la fecha de fallecimiento, deben evitar los NULL"
Pero viendo la base de datos, no tenemos ningun valor NULL, por lo que no entiendo muy bien a que se refieren.
Soy del grupo 84.
Gracias!

**Comment by rafafdz** [comment]
Hola! Esto es un problema de modelación. Si intentan agregar un autor que sigue vivo, su fecha de fallecimiento será NULL. Aunque la instancia que les pasamos no tenga este caso, su esquema debe estar pensado para todos los casos.
