### ISSUE TITLE
Correr entrega 3 localmente

### ISSUE THREAD

**Issue by danustilovsky** [IIC2413/Syllabus-2020-1#254]
Hola,
Queria saber si existe alguna forma de correr php en un local server o algo que se deba bajar para poder hacerlo? Que cambios se deberian hacer en los archivos para que funcione?

Muchas gracias!!

**Comment by tomasalvarez13** [comment]
Descargate php, en la conexión PDO cambia el 'localhost' por la IP del servidor (146.155.13.72), y en el terminal corre el comando `php -S localhost:3000`. Eso me funcionó a mi.

**Comment by danustilovsky** [comment]
@tomasalvarez13  muchas Gracias!
