### ISSUE TITLE
Entradas a museos

### ISSUE THREAD

**Issue by matumartinez** [IIC2413/Syllabus-2020-1#255]
![Screen Shot 2020-05-19 at 4 57 54 PM](https://user-images.githubusercontent.com/42516267/82378191-be2d5a00-99f2-11ea-8ae1-04d0af548f9e.png)

Hola! Con respecto a la entradas a museos de cada usuario, no me queda claro si esa información la tenemos que inventar o está en alguna parte que no me he percatado.

**Comment by nivek0o0** [comment]
Las entradas a museos no existían antes. Deben crear la tabla y asociaciones para soportar esta funcionalidad.

Y al principio nadie tendrá entrada alguna porque la tabla estará vacía, pero se debe ir llenando a medida que los usuarios van comprando entradas en la aplicación (otra funcionalidad descrita más abajo).

**Comment by danustilovsky** [comment]
Hola, una duda con respecto a las entradas a museos. Dado que en necesario tanto los usuarios como los museos, tendremos que copiar alguna de las tablas de una base de datos a la otra. Mi duda es que dado que se pueden agregar mas usuarios o eventualmente mas museos, deberiamos olvidarnos de aquella que fue copiada y solo usar la version copia? Para que esta se mantenga actualizada? 
Y con respecto a lo mismo, dado que hay dependencias, como hacemos para manejarlas? o debemos mantener actualizada ambas copias de las tablas?

Gracias

**Comment by nivek0o0** [comment]
¿Por qué tendrías que copiar tablas entre las bases de datos?
