### ISSUE TITLE
Consultas en procedimiento almacenado

### ISSUE THREAD

**Issue by bahidalgo** [IIC2413/Syllabus-2020-1#256]
Hola!
Hice una pregunta en una issue anterior, pero me parece que es mejor ponerla como issue aparte para aclarar la duda. Nuestra situación en la entrega 3 para procedimientos almacenados es la siguiente:

**Parte 1.** Tenemos una miniconsulta que obtiene información inicial.
**Parte 2.** Tenemos una consulta compleja que se repite varias veces.

Mi duda es, ¿es necesario crear un _archivo.sql_ que utilice tanto las consultas de la parte 2 como la consulta pequeña? ¿o puedo realizar la primera consulta en la _página.php_ y llamar únicamente a la consulta más importante varias veces?

Muchas gracias!

**Comment by nivek0o0** [comment]
Hola,
la idea es que la funcionalidad esté autocontenida en la base de datos y la aplicación llame al `procedimiento(parámetros)` una única vez. Es decir, que todo se haga en lenguaje **PLpgSQL**.

Ahora bien, si quieres modularizar la lógica dentro de la BD y hacer que un procedimiento mayor llame a otros más pequeños, lo puedes hacer, es una buena práctica de programación. En este caso deberás entregar todos los archivos que definen cada procedimiento.
