### ISSUE TITLE
Entrega 3, paginas de artistas, obras, lugares

### ISSUE THREAD

**Issue by fmaturanaa** [IIC2413/Syllabus-2020-1#257]
Hola! Quería preguntar si es necesario que el código se tiene que ajustar a cualquier base de datos de artistas (o lugares o obras) entregada o mas bien podemos crear las diversas paginas por separado pero que no se generarían automáticamente en caso de agregar un nuevo artista a la base. 

Gracias!

**Comment by nivek0o0** [comment]
Hola,
las páginas deben crearse dinámicamente dependiendo de los datos que hayan en la base de datos. En otras palabras, debes parametrizar la página de un artista (por ejemplo) para que a partir de un ID vaya a buscar y muestre los datos.

**Comment by fmaturanaa** [comment]
Claro, pero podemos asumir que no se van a agregar artistas, obras y lugares, a los que ya están?

**Comment by nivek0o0** [comment]
¿En qué afecta ese supuesto?

**Comment by fmaturanaa** [comment]
Que tenemos paginas establecidas por obra, lugar y artista (dentro de cada una se conectan con la base y todo). Pero si se agrega un nuevo artista no se crearia su pagina automaticamente

**Comment by nivek0o0** [comment]
Tienen 19 páginas de artistas, 22 de lugares y 39 de obras?!? Osea 80 archivos php distintos?

**Comment by fmaturanaa** [comment]
Queremos evitar eso jajaja. Pero no logro encontrar la forma de que php guarde como variable el id o nombre de lo que se seleccionó en una lista (o list group)

**Comment by nivek0o0** [comment]
Tienen que evitar eso, es de locos!

La solución puede pasar por usar URL params o Query params. 
Por ejemplo, al hacer click en el link del nombre del artista los mandas a `/artistas.php?id=N` (string que formateas para cada caso). Luego obtienes el `N` de la ruta y haces la consulta por el artista con id **N**.
