### ISSUE TITLE
Borrar cuentas de la base de datos

### ISSUE THREAD

**Issue by ChayoPerez** [IIC2413/Syllabus-2020-1#259]
Hola!
Mi compañero y yo estamos muy confundidos porque la funcionalidad borrar cuenta resulta cuando las cuentas las creó desde su computador y casi nunca cuando las creo yo desde el mío.

```
$query_delete = "DELETE FROM usuarios WHERE uid = $my_id;";
$result = $db_impar  -> prepare($query_delete);
$result -> execute();
```
Cuando "borra" la cuenta imprime el id, así que eso sabemos que está bien. No sé cómo puede haber una diferencia entre los dos casos si el código es el mismo.

Agradecería mucho cualquier idea sobre cómo solucionarlo!

**Comment by nivek0o0** [comment]
Primero, felicitarlos porque su aplicación está **muy buena**. Es un ejemplo a seguir!. Funciona perfecto comprar tickets, entradas o hacer reservas. Incluso hacen muchas validaciones deseables.

Luego de investigar un rato, creo que su problema de la eliminación de usuarios está en que la entidad está referenciada desde otras tablas (entradas, tickets, etc) por lo que la eliminación directa no es posible. Esto lo descubrí ejecutando el comando que dices directamente en la base de datos.

Deben modificar las llaves foráneas para que al eliminar un usuario se eliminen en cascada las demás cosas o bien se seteen como null las referencias, ustedes deciden. Investiguen sobre `ON DELETE CASCASE` o `ON DELETE SET NULL`.

Si esto no resuelve el problema me avisan!

**Comment by ChayoPerez** [comment]
Muchas gracias por el cumplido y por solucionar nuestro problema! :))) Saludos
