### ISSUE TITLE
Itinerario Procedimiento Almacenado

### ISSUE THREAD

**Issue by diegomendieta** [IIC2413/Syllabus-2020-1#260]
Hola, al crear un itinerario se dice que se puede seleccionar más de un artista a la vez, para pasar por ciudades que tengan sus obras. Esto significa que tengo que pasar por ciudades que contengan obras de todos los artistas a la vez, o puedo pasar por ciudades que contengan obras de sólo uno de los artistas seleccionados?

**Comment by nivek0o0** [comment]
Hola, es lo segundo, ciudades que contengan obras de **algún** artista seleccionado (al menos 1).
