### ISSUE TITLE
Contraseña dummy 

### ISSUE THREAD

**Issue by danustilovsky** [IIC2413/Syllabus-2020-1#261]
Hola, 

Dado que para la entrega 3 la contraseña debe ser dummy, se le debe pedir una contraseña al usuario y guardarla en la BD cuando se registra? o no se le pide contraseña y al iniciar sesion se puede revisar que la contraseña ingresada sea igual a la que se definio para todos?
Gracias!

**Comment by nivek0o0** [comment]
Hola,

la contraseña es dummy para los usuarios ya existentes, pero custom para los nuevos usuarios cuando se registran.

**Comment by danustilovsky** [comment]
Gracias!
