### ISSUE TITLE
Rutas absolutas

### ISSUE THREAD

**Issue by cchauriye** [IIC2413/Syllabus-2020-1#262]
Hola! Podemos usar rutas absolutas en esta entrega? Nos facilitaría mucho la navegación.

Gracias!

**Comment by nivek0o0** [comment]
Hola, las rutas absolutas están **prohibidas**.
La razón es que impiden la corrección.

En términos de desarrollo no deberían tener problema entre usar una u otra. Si tienen dificultades avísame y vemos como solucionarlo.

**Comment by cchauriye** [comment]
Gracias! Nuestro problema es que tenemos una navbar y no logramos que los links funcione siempre usando rutas relativas. Buscamos harto y la solución en general era el uso de rutas absolutas. ¿Podrían ayudarnos con eso? Esta navbar no es esencial para el flujo que nos piden, pero igual nos gustaría incluirla.

**Comment by nivek0o0** [comment]
Y si las rutas de tu navbar las construyes como `url_base + ruta_relativa`.

La url base la puedes obtener de la variable global $_SERVER. (Sugiero ver la documentación de PHP).

De esta forma, la navbar debería funcionar bien independiente si la app está en `http://codd.ing.puc.cl/~grupo10/index.php` o esta en `http://codd.ing.puc.cl/~ayudantía/Entrega3/grupo10/index.php` (que será donde corrijan los ayudantes.

**Comment by cchauriye** [comment]
Voy a probar gracias!
