### ISSUE TITLE
Nueva base de datos e3

### ISSUE THREAD

**Issue by jfernandez7** [IIC2413/Syllabus-2020-1#263]
Hola! Solo para confirmar, entonces no es necesario usar la base de datos grupoxxe3? No interfirió con la entrega pasada, que ya está corregida.
Muchas gracias!

**Comment by nivek0o0** [comment]
Hola, en un principio no es necesario.

Pero si mandaste a recorregir las consultas de la E2, lo mejor es no haber tocado la BD de esa entrega.
