### ISSUE TITLE
Input de fecha

### ISSUE THREAD

**Issue by furzuadr** [IIC2413/Syllabus-2020-1#264]
Hola, en una parte del enunciado sale que los inputs de las fechas serán de la forma: yyyy-mm-dd
Estamos usando el 
`<input type=date>`
con el cual se despliega un mini calendario y se selecciona la fecha, la que queda de la forma dd-mm-yyyy, pero igualmente el servidor reconoce las fechas de buena manera. Es posible que lo dejemos de esta forma? O deben ingresarse los inputs a mano?

**Comment by nivek0o0** [comment]
Hola, no hay problema con utilizar el mini calendario.

El formato `yyyy-mm-dd` es para aquellos que deciden recibirlo como texto.
