### ISSUE TITLE
Listados enunciado

### ISSUE THREAD

**Issue by cchauriye** [IIC2413/Syllabus-2020-1#265]
Hola!

Cuando en el enunciado dicen "listado", ¿se refieren a literalmente una lista/tabla o es equivalente usar una lista desplegable?

Gracias!

**Comment by nivek0o0** [comment]
Hola, listado se refiere a una Tabla, donde cada elemento ocupa una fila. (Que es distinto a una lista hacia el lado separados por coma)

No importa si es desplegable o estática.

**Comment by cchauriye** [comment]
Gracias!
