### ISSUE TITLE
Comprar un itinerario

### ISSUE THREAD

**Issue by bahidalgo** [IIC2413/Syllabus-2020-1#266]
Hola,

Tenemos dos dudas:

1.- No entendemos si la función del itinerario es solo una lista con las opciones o además hay que agregarle un botón de compra a cada itinerario. 

2.- En caso de compra, todos los viajes deben realizarse el mismo día o solo el primer viaje?
Es decir, tenemos el siguiente itinerario:

Origen: Roma, Destino: París, Horario: 23:00:00, Duración: 4
Origen: París, Destino: Florencia, Horario: 07:40:00, Duración: 5

El cual sería válido en el sentido de que los horarios no se intersectan, pero necesitaría viajar un día posterior a la fecha ingresada. ¿Para la compra debemos buscar todas las tablas que tengan un día distinto al ingresado para comprar los tickets?

Muchas gracias!

**Comment by nivek0o0** [comment]
Hola, no es necesario _comprar un itinerario_, ya que no aparece dicha funcionalidad en el enunciado.

Solo hay que calcularlo y mostrarlo en 1 tabla por cada itinerario encontrado. (Donde las filas de esta tabla corresponden a los viajes del itinerario)
