### ISSUE TITLE
Comparar int con time

### ISSUE THREAD

**Issue by elisafdz** [IIC2413/Syllabus-2020-1#267]
Hola!
Para la parte de procedimientos almacenados en la entrega 3, quiero sumar la hora de salida con la duración del viaje para ver la hora de llegada pero la duración es un int y la hora de salida es del tipo time. He tratado de pasar la duración a horas en mi función de varias formas distintas pero no me funciona. Agradecería mucho si me pudieran ayudar.

Gracias!

**Comment by nivek0o0** [comment]
Hola, Postgres tiene mil formas de manipular fechas con horas, enteros, otras fechas, etc. Eso se explica en la [documentación](https://www.postgresql.org/docs/10/functions-datetime.html).

**Comment by elisafdz** [comment]
Gracias!
