### ISSUE TITLE
Manejo de sesión en PHP

### ISSUE THREAD

**Issue by JupaOlivares** [IIC2413/Syllabus-2020-1#268]
Hola existe algun metodo de como saber si un usuario esta conectado y acceder a sus credenciales?

**Comment by nivek0o0** [comment]
Hola, puedes manejar la sesión con la variable global $_SESSION. ([documentación](https://www.php.net/manual/es/reserved.variables.session.php))

Básicamente la inicias al principio del archivo, guardas los datos del usuario cuando se logea exitosamente, eliminas los datos cuando se deslogea. En cualquier momento puedes acceder a esos datos. 

Recordar que estamos usando PHP 7.2
