### ISSUE TITLE
Duda pregunta 6 Control 1

### ISSUE THREAD

**Issue by rodobkn** [IIC2413/Syllabus-2020-1#27]
Hola!

Quería preguntar si en la pregunta 6 del Control 1, se refiere a que debo imprimir los nombres(o el nombre) de los clientes que gastaron más dinero en total? o que en solamente un pedido gasto más dinero? o el que compro simplemente el objeto más caro?

Gracias!

**Comment by nivek0o0** [comment]
Les pedimos los clientes que compraron el **producto** más caro, da lo mismo si fueron 1 o 10 unidades de él.

En la instancia del enunciado la respuesta a la consulta 6 es Tamara, pero si hubiesen más clientes que hayan comprado alguna vez pid=1 entonces la respuesta los contendría a todos.

**Comment by rodobkn** [comment]
ok, ya entendí. Gracias!

**Comment by fjcroquevielle** [comment]
Entonces asumimos que siempre alguien comprara ese producto? Osea siempre alguien comprara pid=1

**Comment by nivek0o0** [comment]
No pueden asumir nada sobre la instancia.

Podrían haber comprado ese producto o no, y eso no debe influir en la consulta en álgebra relacional. Si no ha sido comprado la respuesta será vacía simplemente.

Si te influye es porque estás _harcodeando_ el pid y eso está incorrecto. El producto más caro podría ser el pid=2 o pid=3. Debes encontrarlo haciendo un Self Join y las condiciones adecuadas.

**Comment by fjcroquevielle** [comment]
Perfecto. Gracias!
