### ISSUE TITLE
Procedimientos almacenados y PHP

### ISSUE THREAD

**Issue by bpeirano1** [IIC2413/Syllabus-2020-1#271]
Hola!
Quería saber si en la parte de procedimientos almacenados hay que hacer toda la consulta dentro de la función, es decir, acceder a tablas de otras bases de datos, filtrar las tablas y retornar una tabla
o podría acceder a diferentes tablas utilizando php y después se las paso cómo atributo a mi función y de ahí trabajo con ellas.

Saludos

**Comment by nivek0o0** [comment]
Hola, toda la lógica debe estar dentro de la función del procedimiento almacenado.

**Comment by sebaav12** [comment]
Esto quiere decir que las consultas que nos permitirían seleccionar los artistas y luego obtener las ciudades donde existen obras, ¿también deben estar dentro de la función del procedimiento almacenado?

**Comment by nivek0o0** [comment]
Las consultas que traen los artistas y las ciudades si puedes hacerlas primero desde PHP, para ofrecerle al usuario seleccionar mediante checkboxes o dropdowns.

De ahí en adelante la responsabilidad debe pasar al procedimiento almacenado. Esto implica que PHP debe entregarle como parámetros los artistas seleccionados y la ciudad de origen al procedimiento. Con esos datos ya pueden realizar toda la lógica para calcular los itinerarios.
