### ISSUE TITLE
No puedo editar el archivo mystyles.css

### ISSUE THREAD

**Issue by lflozano** [IIC2413/Syllabus-2020-1#275]
Hola, al intentar modificar mi página ocurre el siguiente error:
Cuando modifico el index.php, al subir los cambios al servidor mi página se modifica pero al modificar el mystyles.css no se ve ningún cambio, ocupo filezilla para subir los archivos al servidor y no se que es lo que puede estar causando este error ya que no ocurre ningún problema al transferir los archivos.

**Comment by fjlopez7** [comment]
Puede ser que no estés llamando correctamente el archivo de css en index.php. Como lo haces?

**Comment by lflozano** [comment]
Creo que te refieres a este código, es el mismo de la ayudantía de php.
![Sin título](https://user-images.githubusercontent.com/48394340/82848089-ea981900-9ebf-11ea-95c6-a70cc2bc4d29.png)
Y lo pongo en mi index.php de la siguiente manera:
![Sin título 2](https://user-images.githubusercontent.com/48394340/82848119-26cb7980-9ec0-11ea-8c05-742aaa25b569.png)

**Comment by fjlopez7** [comment]
Pareces que tienes problemas con el head. Intenta eliminar el \<head\> en index.php y mueve el link de la font  al head del header.html y recuerda cerrar el html (\</html\>) en index.php

**Comment by lflozano** [comment]
Siguen sin hacerse los cambios en la página :( , es raro porque para la entrega 2 lo podía editar y se hacían los cambios, pero  ahora para la entrega 3 no se efectúan los cambios del css al subirlos al servidor, pero los del php si.

**Comment by lflozano** [comment]
Acabo de cambiar de navegador (de opera a internet explorer) y veo los cambios en la página, trabajaré viendo la página en ese navegador, pero tengo una consulta, ¿Los ayudantes van a poder ver los cambios que hice en la página o no?

**Comment by fjlopez7** [comment]
Te recomiendo revisar con que funcione correctamente en google chrome y en firefox, dado que son los más comunes.

**Comment by lflozano** [comment]
Oka gracias :D
