### ISSUE TITLE
Artistas No Fallecidos

### ISSUE THREAD

**Issue by mscuturrufo** [IIC2413/Syllabus-2020-1#276]
Hola! Está bien que, cuando un artista aún no fallece, al desplegar los atributos del artista la columna de Fecha de Fallecimiento quede vacía? O es necesario no desplegar tal columna?

**Comment by nivek0o0** [comment]
Hola, no hay problema que esa columna se muestre vacía para los artistas vivos.

**Comment by mscuturrufo** [comment]
Gracias!
