### ISSUE TITLE
Procedimientos almacenados

### ISSUE THREAD

**Issue by fernando98alba** [IIC2413/Syllabus-2020-1#278]
Hola, en la parte de procedimientos almacenados piden que se ingrese una fecha, no entendí para que, es para ver si hay disponibilidad en los viajes?
Lo otro, el viaje tiene que ser en un día o puede ser mas? Porque si puede ser en mas no habría problemas de topes, solo habría que esperar mucho para tomar la conexión.

**Comment by nivek0o0** [comment]
Hola, la fecha sirve para decirle al usuario en qué momento debe tomar cada uno de los viajes, ya que es muy diferente tomar un cierto viaje el Lunes 25, Martes 26, o Miércoles 27 si el itinerario parte el mismo 25 y hay restricciones de duración que cumplir.

El enunciado dice que los viajes tienen una hora de salida y se repiten todos los días de la semana. Entonces si lo piensas, cualquier combinación de viajes podría ser válida, si esperar el tiempo suficiente entre ellos.

Los itinerarios no necesariamente deben ser de 1 solo día, pueden ser de cualquier duración, lo importante es que cada viaje empiece después de que el anterior llegó a destino. 

Veamos este ejemplo:
|nombre|hora salida|duración (hrs)|
|-|-|-|
|viajeA|23:00|2|
|viajeB|03:00|1|

Tanto A+B como B+A serían itinerarios válidos, puesto que puedes tomar estos 2 viajes en cualquier orden, esperando un cierto tiempo (que podría ser corto o largo, da lo mismo). 
Por ejemplo: 
- Tomo el Viaje A el Lunes 25 a las 23:00 y el viaje B el Martes 26 a las 03:00. 
- Tomo el viaje B el Lunes 25 a las 03:00 y el Viaje A el Lunes 25 a las 23:00.

¿Qué pasaría si el viaje A dura 5 horas? No podrías tomar el viaje B durante la madrugada más próxima, pero sí la del día siguiente. Por ejemplo:
- Tomo el Viaje A el Lunes 25 a las 23:00 y el viaje B el Miércoles 27 a las 03:00. 
- Tomo el viaje B el Lunes 25 a las 03:00 y el Viaje A el Lunes 25 a las 23:00.

Entonces, ¿como distingues el primer itinerario de cada ejemplo? Con la **fecha**.

**Comment by raimundoloeser** [comment]
Hola, 
nosotros tenemos la misma duda.
Con el formato que nos piden mostrar los itinerarios no aparecen las fechas de los vuelos, solo las horas. Entendemos que es relevante para el usuario la fecha del vuelo, pero si no esta presente en el formato con el que mostramos los itinerarios, todo viaje que cumpla con las escalas va a ser valido.
Lo que pensamos era buscar alguna relacion con los tickets de nuestra tabla de tickets, los cuales tienen precio, pero esos están asociados a un id de usuario, por lo tanto no podríamos decir que están "libres".

gracias de antemano

**Comment by nivek0o0** [comment]
No entiendo cuál es el problema. Desde mi punto de vista los tickets no tienen nada que ver, ya que el precio de los viajes está en la tabla Destinos.

**Comment by raimundoloeser** [comment]
Sisi, nos confundimos de tabla, ahora nos calza
gracias!

**Comment by humbertoortuzar** [comment]
Hola, tengo una duda con respecto a esto. 
Entiendo el punto que dices que son distintos itinerarios, ya que son viajes en fechas distintas, sin embargo ambos itinerarios hacen sentido con esas fechas tomadas en consideración.

Si tomo esos itinerarios como válidos, entonces cualquier escala/viaje, sin importar la duración y hora, será posible. Por lo tanto el primer punto que dice "los itinerarios deben hacer sentido", si tomamos un itinerario de varios días no es necesario poner restricciones de horas, ya que no se pide tampoco indicar la fecha en que se hará el viaje ni considerar el precio por estadía en hoteles o algo por ese estilo.

Mi duda es entonces, ¿Como debería considerar la hora en el momento de restricciones?, ya que por ahora entiendo que podría tomar cualquier itinerario si me demoro los suficientes días.

**Comment by nivek0o0** [comment]
Hola, estoy totalmente de acuerdo contigo. Dados los requisitos escritos en el enunciado y lo que he dicho a través de las issues: **cualquier escala/viaje, sin importar la duración y hora, será posible**

Por lo tanto, el problema se reduciría a encontrar una secuencia de viajes que existan en la BD, que partan en la ciudad seleccionada y que pasen por ciudades con obras de los artistas seleccionados. Y el tema de mostrar la hora (y fecha) de cada viaje tendrá que ser considerado como un plus. 

Lo importante es que dado que el problema no estuvo muy claro desde el inicio, seremos muy flexibles en la corrección.

**Comment by fernando98alba** [comment]
Pero todas las ciudades intermedias deben tener obras de los artistas o
solo la última?

**Comment by nivek0o0** [comment]
Todas excepto la primera (que es la escogida por el usuario).

**Comment by ngermani** [comment]
> Todas excepto la primera (que es la escogida por el usuario).

Hola, 
No entiendo su respuesta "Todas excepto la primera"?   Si nuestro itinerario es con 1, o 2 escalas, no es solamente la ultima ciudad (destino final) que debe tener al menos una obra de los artistas?
Igual tienen restricciones las ciudades de las escalas?   

Gracias

**Comment by nivek0o0** [comment]
Hola @ngermani 
Como dice el enunciado, debemos viajar a ciudades con obras de los artistas seleccionados. Esto hace referencia a todas las ciudades por las que pasemos y no solo la última, porque si tienes que hacer escala en una ciudad intermedia (e incluso esperar algunas horas) igual habrás _"viajado"_ a esta ciudad.

Es así como funcionan las agencias de turismo en la vida real. Cada lugar de un itinerario por donde pasas es un lugar de interés donde quieres ver o hacer algo. Nadie parte en Santiago y pasa por Miami, Madrid, Roma y Beijing para finalmente llegar a París a ver la torre eiffel, que era lo único que me interesaba. 

Tal vez te confundiste con las conexiones, que es lo que realizan las aerolineas para largas distancias. Pero esto no tiene mucho sentido ya que el trasfondo del proyecto es el caso anterior de la agencia de turismo splinter.

La simplificación que les propuse es que ignoráramos la primera ciudad para chequeo de obras, puesto que es la que elije el usuario. De no hacerlo, tendrías que validar en la app que la ciudad y artistas escogidos tuviesen obras de por medio. Por eso la intención era eliminar ese trabajo.

**Comment by ngermani** [comment]
Queda claro! Gracias!
