### ISSUE TITLE
problemas con git 

### ISSUE THREAD

**Issue by juakoke** [IIC2413/Syllabus-2020-1#279]
Con nuestro grupo intentamos trabajar con ramas, sin embargo tuvimos muchos problemas por lo que decidimos no hacerlo, sin embargo, algo dejamos mal. Ahora nuestro git tiene los archivos necesarios y 2 ramas la master y una de respaldo, nuestro repositorio local esta con los archivos necesarios igual y sin ningún problema, el problema es en el servidor. Este tiene archivos diferentes al del git y este no nos deja hacer git pull, es por esto que queremos volver a "clonar" el repositorio pero no sabemos como, ya que lo hicimos según el tutorial de la wiki con git init y luego con git remote no con git clone, ¿Como se podria resetear esta carpeta del servidor y lograr pullear nuestros archivos de git?

**Comment by nivek0o0** [comment]
En vez de clonar de nuevo el repo, podrían intentar forzar el existente a que pierda sus cambios y se sincronice con el de github.

Qué error les tira al hacer `git pull`? que les aparece con `git status`? Podrían intentar `git checkout -- *` para eliminar cualquier cambio local o bien `git pull -f` para forzar la sobrescritura de los archivos locales.
