### ISSUE TITLE
Duda Control 1

### ISSUE THREAD

**Issue by Paldana99** [IIC2413/Syllabus-2020-1#28]
Para las consulta hay que ir explicando paso a paso cada consulta que se hace?
O solo es necesario escribir la consulta como tal.

**Comment by mihenriquez** [comment]
Hola! Solo es necesario escribir la consulta :)

Pero si inevitablemente tienes varios pasos y quieres explicarlos para facilitarle la corrección al ayudante, bienvenido sea!
