### ISSUE TITLE
Itinerarios de largo variable

### ISSUE THREAD

**Issue by danustilovsky** [IIC2413/Syllabus-2020-1#280]
Hola, 
Dado que hay itinerarios con 0,1 o 2 escalas, para el procedimiento almacenado lo mas correcto es generar 3 tablas distintas o una sola que contenfa NULL?

Gracias

**Comment by nivek0o0** [comment]
Hola, 
la verdad es que la forma de generar, almacenar y entregar los itinerarios a la aplicación queda a su elección, por lo que pueden escoger la forma que más les acomode. No nos fijaremos en eso al momento de corregir.
