### ISSUE TITLE
como copiar la BD

### ISSUE THREAD

**Issue by snarriagada** [IIC2413/Syllabus-2020-1#281]
Hola! aun tengo problemas para copiar la base de datos de la e2 hacia la e3. Vi una issue anterior que recomendaron usar pg_dump y pg_restore, pero no cache bien que atributos ponerle a pg_dump y al correr pg_dump grupo77e2 > respaldoe2.sql dentro del psql de la e2 no reconocio el comando. No se si hay que hacerlo en otro lugar, o hay una manera mas facil
gracias!!

**Comment by nivek0o0** [comment]
Hola, estos comandos son del **servidor**, no de la base de datos (psql).
Simplemente hay que hacer
`pg_dump grupoXXe2 > db.sql`
`pg_restore -d grupoXXe3 db-sql`

**Comment by snarriagada** [comment]
Hola! para el comando pg_dump no tuve problemas, pero con el pg_restore primero tiro error por el "-" que luego cambiamos a "."
y en el segundo intento dice que el respaldo es .txt y que hay que usar psql (?)
gracias!!

grupo77@codd:~$ pg_restore -d grupo77e3 db-sql
pg_restore: [archiver] could not open input file "db-sql": No such file or directory
grupo77@codd:~$ pg_restore -d grupo77e3 db.sql
pg_restore: [archiver] input file appears to be a text format dump. Please use psql.

**Comment by nbnavarro** [comment]
Hola @snarriagada !

Quizás podrían probar con el siguiente comando en alternativa al que no les funcionó `psql -d grupoXXe3 -f db.sql`. Sería ejecutar los sgtes dos comandos:
- `pg_dump grupoXXe2 > db.sql`
- `psql -d grupoXXe3 -f db.sql`

**Comment by snarriagada** [comment]
perfect, funciono gracias!
