### ISSUE TITLE
Duda acerca de navegación y cómo mostrar la información

### ISSUE THREAD

**Issue by lucastack** [IIC2413/Syllabus-2020-1#282]
Hola!

En el enunciado se nos pide mostrar la información de las entidades en una tabla (como el caso de artistas y obras). Se puede mostrar esa **misma información** pero en una especie de perfil y no en una tabla? Es sólo para que se vea "más bonito"...

**Comment by nivek0o0** [comment]
Hola, sí, da lo mismo si la tabla es hacia el lado o hacia abajo.
