### ISSUE TITLE
Ids de artistas, obras, lugares al mostrar info en cada página

### ISSUE THREAD

**Issue by juansjimenez** [IIC2413/Syllabus-2020-1#283]
Hola! No veo cuál es la utilidad de mostrar el aid, oid o lid cuando se pide la información de cada artista, lugar u obra en cada una de estas páginas. Es necesario mostrar esto o podemos omitir este atributo?

**Comment by nivek0o0** [comment]
Hola, pueden omitirlo puesto que no agrega valor.
