### ISSUE TITLE
PROCEDIMIENTOS ALMACENADOS

### ISSUE THREAD

**Issue by martinrtc** [IIC2413/Syllabus-2020-1#284]
Hola, tengo una duda sobre como trabajar con el procedimiento almacenado.
Nuestro procedimiento almacenado tiene que ser capaz de trabajar con ambas bases de datos? O tenemos que tener 2 procedimientos los cuales sacan informacion de cada base de datos respectivamente y trabajar con esa informacion?.
Gracias

**Comment by nivek0o0** [comment]
Hola, no hay restricción respecto a dónde ejecutan el procedimiento almacenado. 

La única restricción es que toda la lógica esté en los procedimientos y no en PHP.
