### ISSUE TITLE
error en login 

### ISSUE THREAD

**Issue by snarriagada** [IIC2413/Syllabus-2020-1#286]
Hola! tengo un error con el login. Cuando ingreso no funciona el if que compara la password que ingreso el usuario con la extraida de la BD. Al imprimir ambas en pantalla, primero se agrega un espacio a la extraida de la BD: "abcd " , y si ingreso "abcd " de password me imprime bien ambas (aparentemente iguales), pero no entra al if, sino que arroja password incorrecta del else.

Por si necesitas ver el codigo en detalle es el grupo 77

gracias!

if ($usernames[0][0] != ""){
    **if (strval($usernames[0][1]) == strval($password))**{
        echo 'Has sido logueado correctamente '.$_SESSION['k_username'].' <p>';
    } else {
        echo "<h4> password incorrecta </h4>";
    }
 }else{
  echo 'Usuario no existente en la base de datos';
}

}else{
 echo 'Debe especificar un usuario y password';
}

**Comment by nivek0o0** [comment]
El problema estaba en la forma en que agregaron la columna con un valor por defecto. Habían unos espacios muy raros. 

Prueben si funciona ahora. Yo pude logearme correctamente.
