### ISSUE TITLE
Página de obras con más de un artista

### ISSUE THREAD

**Issue by PabloRabeloRoa** [IIC2413/Syllabus-2020-1#287]
Tengo una duda, cuando se crean las paginas para las obras que tienen más de un artista que participo en ellas, el enunciado dice que solo se debe mostrar el nombre de el artista que la realizo, en este caso se debería poner el nombre de todos los que participaron?

**Comment by nivek0o0** [comment]
Sí, se deben mostrar todos los artistas que participaron en esa obra (incluyendo un link a su página). La forma de mostrarlos queda a su criterio.
