### ISSUE TITLE
Procedimiento Almacenado viajes

### ISSUE THREAD

**Issue by Paldana99** [IIC2413/Syllabus-2020-1#288]
Es valido un itinerario que te haga repetir las ciudades, por ejemplo hace: 

1. roma parís. 
2. parís florencia.
3. florencia parís

Siendo Florencia y París, ciudades en donde se encuentran obras de los artistas seleccionados.

**Comment by nivek0o0** [comment]
Es válido. El enunciado no dice que las ciudades no se puedan repetir.

**Comment by diegomendieta** [comment]
De ser así, deberían aceptar las dos opciones, ya que en el excel de ejemplo del procedimiento almacenado se da a entender que esto no puede ser así.

**Comment by nivek0o0** [comment]
Claro, ambas opciones serán correctas.

**Comment by furzuadr** [comment]
Hola, con respecto a esto me queda una duda, la pongo con un ejemplo:

Tengo un artista (Caravaggio), que tiene obras en varias ciudades, pero solo se puede llegar de Roma a Florencia (y viceversa).
Existen 4 viajes de Roma a Florencia, a la vez existen 4 de Florencia a Roma.

Los posibles itinerarios debiesen ser:
1. Roma - Florencia (sin escalas)
2. Roma - Florencia - Roma - Florencia (2 escalas)

En base a eso, existirían los posibles siguientes itinerarios:
Itinerario 1: 4 viajes
Itinerario 2: 4 combinaciones en primer viaje, 4 en la siguiente y 4 en la siguiente = 64 viajes distintos

Con todo esto, habrían en total 68 posibles itinerarios. Hay algo mal en mi razonamiento? O de lo contrario, tengo que mostrar todos esos 68 posibles itinerarios?

Gracias!

**Comment by nivek0o0** [comment]
Hola, no es necesario mostrarlos todos. De hecho el enunciado no pide mostrarlos todos.

Cuando redactamos el enunciado no pensamos en estos casos especiales, así que mi sugerencia es que trates de entregar todos los que puedas, sin complicarte tanto. Seremos muy flexibles en la corrección.
