### ISSUE TITLE
Duda Control consulta 1

### ISSUE THREAD

**Issue by JuaniAndres** [IIC2413/Syllabus-2020-1#29]
Hola solo verificar cuando hablan de algo de más de 5000 pesos se refieren al precio individual del producto y no del valor total pagado en el pedido (producto*cantidad)?
Gracias de antemano

**Comment by nivek0o0** [comment]
Hola,
en las primeras 3 consultas cuando se habla de **algo** se refiere a un **producto**. Por lo tanto sería lo primero que dices.

**Comment by JuaniAndres** [comment]
ok muchas gracias
