### ISSUE TITLE
/~grupoXX/index.php vs /home/grupoXX/Sites/index.php

### ISSUE THREAD

**Issue by mserranob** [IIC2413/Syllabus-2020-1#290]
Cual es la diferencia de meterse a los sitios con un link o el otro? Ya que me muestran los mismo pero hay unas funciones que no me funcionan en el con ~ pero si en el otro.

**Comment by nivek0o0** [comment]
¿Cuáles son las funciones que fallan y en qué carpeta están?

La idea es que utilicen únicamente rutas relativas partiendo desde la carpeta donde se encuentra el index. Por ejemplo si están en `index.php` y quieren ir a la consulta 1, dirigirse a `consultas/consultas1.php`. Si estan en `consultas1.php` y quieren regresar a la página principal, dirigirse a `../index.php`

**Comment by mserranob** [comment]
Las funciones que fallan son las del login del usuario, entonces como no se puede logear no se puede acceder a otras funciones que estan restringidas a estar logeado. Se ocupa un archivo JavaScript que está en la carpeta js y otro archivo php que se llama LoginAjax que está en la carpeta login, todo esto dentro de sites. Pero lo raro es que  con este link: http://codd.ing.puc.cl/home/grupo88/Sites/index.php 
nos funciona todo desde cualquier dispositivo entonces nose si será por rutas absolutas.

**Comment by nivek0o0** [comment]
Hola, el problema que arroja es el siguiente (pueden verlo desde la consola del inspector de Chrome)
`POST http://codd.ing.puc.cl/Sites/login/LoginAjax.php 404 (Not Found)`
Esta ruta claramente no existe, porque Sites no está en la raíz del servidor, sino más adentro, en las carpetas de cada grupo.

Solo cambié la ruta a donde hacen el POST y funcionó el login en ambos casos que mencionas. Antes tenían `url:'../Sites/login/LoginAjax.php'` y lo dejé como `url:'./login/LoginAjax.php'`.

Les sugiero revisar todas estas URLs en todas las funciones que tengan implementadas.
