### ISSUE TITLE
Procedimiento Almacenado - Conexión BDD

### ISSUE THREAD

**Issue by sebaav12** [IIC2413/Syllabus-2020-1#291]
Hola:
Estamos tratando de conectar el procedimiento almacenado con la base de datos externa, para lo cual comenzamos ejecutando:

SELECT dblink_connect('dbname=grupoXXe3 options=-csearch_path= password= XX');
desde grupoxxstored1 pero obtenemos el siguiente error:

ERROR:  function dblink_connect(unknown) does not exist
LINE 1: SELECT dblink_connect('dbname=grupo72e3 options=-csearch_pat...
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

Averiguando, notamos que este error se podría deber a problemas de instalación de la librería, ¿es posible que de verdad sea así?¿o que esta sucediendo realmente?

Por ultimo, notamos que dblink no es del todo segura, ¿esto es relevante?.

PD nos guiamos en parte por la issue 233.

**Comment by nivek0o0** [comment]
Hola, yo diría que el error es que no están siendo meticulosos con el contenido de ese string de conexión. Yo sacaría el options (que por cierto tiene un signo = de más), juntaría la clave al signo igual, agregaría `user=grupoXX`.

Por otro lado, no importa si la llamada a otra BD a través de dblink no es segura, ya que solo vive dentro del mismo servidor.

Me avisas como te va.
