### ISSUE TITLE
Duda Bonus navegación tarea entrega 3

### ISSUE THREAD

**Issue by JuaniAndres** [IIC2413/Syllabus-2020-1#292]
Hola tengo una duda que sería una navegación sobresaliente y que no lo seria?
Gracias de antemano

**Comment by nivek0o0** [comment]
Hola, una navegación sobresaliente es aquella donde es fácil logearse, deslogearse, ir a mi perfil, ir a las páginas de los artistas, comprar cosas, volver a la página principal, etc.

En resumen, poder hacer todas las acciones de forma intuitiva sin nunca tener que escribir la URL a mano en el navegador.

**Comment by JuaniAndres** [comment]
yap gracias
