### ISSUE TITLE
Procedimientos Almacenados Fechas

### ISSUE THREAD

**Issue by lucas-valenzuela** [IIC2413/Syllabus-2020-1#293]
Hola! Se debe asumir que todos los viajes de un itinerario deben hacerse todos dentro del día (siendo posible que el arrival del último viaje sea al otro día, pero con departure del mismo día)? De otra manera habrían infinitos itinerarios, porque bastaría que se asigne el viaje del día siguiente para que no hayan para que no hayan inconsistencias con los horarios, ej. elegir el vuelo1 un martes a las 17.00 y el vuelo2 siguiente el miércoles a las 15.00.

**Comment by nivek0o0** [comment]
Hola, mira las últimas respuestas en #278 y #288, allí hay aclaraciones respecto a este tema.
