### ISSUE TITLE
DBLINK

### ISSUE THREAD

**Issue by martinrtc** [IIC2413/Syllabus-2020-1#294]
Hola, hemos tenido constantes problemas intentando conectar nuestras dos bases de datos. intentamos usar dblink, dblink_connect, dblink_connect_u, y todo nos arroja errores de superuser.

DETAIL:  Non-superusers must provide a password in the connection string.

Intentamos entregandole la contraseña tambien pero no hemos logrado nada. 
Hemos intentado desde la base de datos grupoXXe2 y grupoXXe3 y ninguna nos funciona.
Se agradece la ayuda de antemano.

**Comment by nivek0o0** [comment]
Hola, podrías poner algunos ejemplos de cómo están llamando a esas funciones?

A otros grupos les ha funcionado bien, así que debe ser un error de sintaxis nomás.

**Comment by martinrtc** [comment]
![WhatsApp Image 2020-05-29 at 18 01 21](https://user-images.githubusercontent.com/53836754/83309174-94381c80-a1d6-11ea-92e3-c5500d4399d7.jpeg)

**Comment by nivek0o0** [comment]
`user=grupoXX`
