### ISSUE TITLE
Procedimientos almacenados

### ISSUE THREAD

**Issue by sgutgar** [IIC2413/Syllabus-2020-1#295]
Hola, tengo una duda al momento de recibir los artistas seleccionados para partir con los procedimientos. Sigo sin poder encontrar una forma de que mis funciones reciban un numero indefinido de parámetros y la única forma de solucionarlo es haciendo una parte de lógica en php.
Si saben de alguna forma en que una función reciba una tabla o una lista me sería de gran ayuda.

**Comment by nivek0o0** [comment]
Hola, los procedimientos pueden recibir un arreglo de enteros, cuyo tipo de dato se escribe en la función como `integer[]`. Y postgres maneja los arreglos de enteros como, por ejemplo, `ARRAY [1,2,3]` o bien `'{1,2,3}'`.

Igual te recomiendo buscar un ejemplo antes de probar.
