### ISSUE TITLE
Fecha en itinerario

### ISSUE THREAD

**Issue by itplanella** [IIC2413/Syllabus-2020-1#296]
Hola! Se que es una pregunta que se ha hecho mucho, he leido todas las issues pero aun no me queda claro. 
Como se menciono en otras issues, los itinerarios pueden durar mas de un dia, por lo que yo supongo que no habrá limite de días y en ese caso todos los viajes que cumplan con que existan escalas serán posibles. Ya que si uno sale en un horario que el anterior no le permite si se podria usar ya que lo haría al día siguiente.
Mi pregunta es si lo que mencione recien es correcto o esta mal, y si es asi como deberia entenderlo.
Muchas gracias de antemano!

**Comment by nivek0o0** [comment]
Hola, está correcto. En las issues #278 y #288 hice más aclaraciones al respecto.

**Comment by tsgonzalez** [comment]
Hola! me leí las issues pero creo que esto no lo preguntaron: 
sigue siendo necesario pedirle una fecha al usuario, aunque no se utilice para nada???  o podemos pedirle una seleccion de artistas y una ciudad de origen solamente?

**Comment by juanreutter** [comment]
MMm, no entiendo cuando dices que no se usa. Quizá no se utilice en el grueso del algoritmo, pero si para ver cuando empezar. Mira la issue #278 que apuntó Kevin. Hay que pedir fecha!

**Comment by tsgonzalez** [comment]
Me refiero a que en esa misma issue se dice que, como en nuestra página no tenemos que mostrar las fechas de los viajes de cada itinerario, y como los viajes se pueden hacer todos los días, entonces encontrar la información **que se debe mostrar** de los itinerarios es un problema que se puede resolver sin tener el dato de la fecha de partida. Es por esto que me preguntaba si seguía siendo necesaria pedirla, porque voy a mostrar lo mismo en la página, independiente de la fecha que ingrese el usuario. 

Creo que se debería usar la fecha si es que tuviera que mostrar la fecha en que termina el itinerario o algo así, pero no se pide nada de ese estilo.

**Comment by juanreutter** [comment]
En realidad depende de cómo lo estés mostrando o ordenando. Ahora que lo pienso, hay formas de ir a buscar esa información que se anclan en una fecha y buscan hacia adelante, pero otras que no. En esa issue Kevin estaba pensando en una forma en la que ordenamos los itinerarios por el día en que salen (después de la fecha). 
De todas formas, aunque usas una forma de buscar la información que no se ancle en la fecha, píde la fecha igual, para que quede todo estándar.
