### ISSUE TITLE
Procedimiento Almacenado

### ISSUE THREAD

**Issue by veneguitas** [IIC2413/Syllabus-2020-1#298]
Hola! Quería saber si puedo poner un límite de espera en horas (estaba pensando en quizás máximo 12 horas de espera), ya que por lo que entendí en la issue #278 todos los viajes serán válidos ya que se podría esperar al día siguiente en muchas situaciones. Por ejemplo:
Viaje A: Roma a Florencia a las 9:00 hrs con 5 horas de duración.
Viaje B: Florencia a Nancy a las 9:30 hrs 3 horas de duración.
Aquí el Viaje A no alcanza a llegar al Viaje B en el mismo día, pero si se puede esperar al día siguiente para el viaje, por lo tanto es válido, pero considero que no sería óptimo poner este itinerario ya que sería una espera de 19 horas.

**Comment by nivek0o0** [comment]
Hola, no es relevante para la corrección si hay esperas de muchas horas. Lo que nos interesa es que encuentren las conexiones entre ciudades a partir de los datos que selecciona el usuario.

Creo que ponerte ese máximo solo añade más complejidad a la solución.
