### ISSUE TITLE
Duda lista en consultas

### ISSUE THREAD

**Issue by itplanella** [IIC2413/Syllabus-2020-1#299]
Hola! para mi procedimiento almacenado estaba haciendo una consulta con la siguiente condicion:

WHERE D1.ciudad_id IN (1,3,5)

la cual al ejecutarla en la base de datos como consulta me funciona bien, sin embargo, al momento de pasarla a mi procedimiento almacenado, y entregarla como variable, tengo entendido que no se pueden usar listas como variables y en ese caso tendria que entregar esa lista como un varchar. Queria saber si esto funciona de igual manera si le entrego la lista en formato de string, antes de seguir armando mi procedimiento almacenado sin que vaya a funcionar.
Muchas gracias de antemano

**Comment by itplanella** [comment]
Estuve probando usando SELECT value FROM STRING_SPLIT('h,o,l,a'    ,     ' , '  ) pero me arroja el siguiente error :
No function matches the given name and argument types. You might need to add explicit type casts.

**Comment by nivek0o0** [comment]
Hola, #295

**Comment by itplanella** [comment]
@nivek0o0 muchas gracias!
