### ISSUE TITLE
Numero de telefonos

### ISSUE THREAD

**Issue by perezpefaur** [IIC2413/Syllabus-2020-1#3]
Los numeros de telefono van a ser solo numeros o tambien podrian incluir "+" y "-"

**Comment by fjlopez7** [comment]
Respecto a tu duda, seria si el número de teléfono es un string o int.
En este caso, seria mejor tratar el número de teléfono como un string dado que puedes tener el simbolo "+" y/o espacios en ciertas partes. En general no sabes si en la base de datos esta ingresado el dato solo con números, por eso se prefiere el uso de string.
