### ISSUE TITLE
Duda Entrega 1 Pregunta 5 Impares

### ISSUE THREAD

**Issue by juanpacl111** [IIC2413/Syllabus-2020-1#30]
El enunciado pide que identifique aquellas reservas de hotel que comienzan y terminan en marzo. Mi pregunta es ¿Qué tipo de objeto debería ser la fecha de llegada/salida? (Algo así como datetime en python o solo string). Y a partir de eso, ¿cómo identifico el mes de esa fecha?

**Comment by ridiazcampos** [comment]
¡Holaaa!
Las fechas de llegada y salida pueden interpretarlas como un dato del tipo _date_, que sigue el formato YYYY-MM-DD, y admite operaciones de desigualdad entre estas.

De esta forma, si por ejemplo tienen una tabla Pedidos (id, fecha), y quieren obtener aquellas que ocurren antes del 2020, una forma de generar la consulta en algebra relacional sería:

`σ fecha <= 2019-12-31 (Pedidos)`

No sé si eso responde la duda! Nos comentas cualquier cosa (: 

Saludos!

**Comment by nivek0o0** [comment]
Pensando ya en la implementación, si bien existen funciones de Postgres que te obtienen toda la información (día, mes, año, día de la semana, etc) a partir de un `Date`, a veces no es necesario utilizarlas, porque basta con comparadores de desigualdad.
