### ISSUE TITLE
Procedimiento almacenado 

### ISSUE THREAD

**Issue by jperalta2202** [IIC2413/Syllabus-2020-1#300]
Hola, estoy teniendo un erro al hacer una consulta SQL dentro del comando dblink

yo se que esta consulta si funciona, ya que la puedo correr en la base de datos del grupo par,
SELECT aid FROM artistas WHERE anombre = 'caravaggio' 

pero al intentar hacer la misma consulta desde la base de datos del grupo impar usando el dblink de la forma

SELECT * FROM dblink('dbname=grupoXX user=grupoXX password=grupoXX', 'SELECT aid FROM artistas WHERE anombre = 'caravaggio' ') as T1(artista int);

tira el error syntax error at or near "caravaggio"

Creo que debe ser por el uso de las comillas, pero no se como arreglar este problema

**Comment by nivek0o0** [comment]
Hola, las comillas simples deben ser "escapadas" dentro de otro string de comillas simples, de lo contrario lo que hacen es terminar anticipadamente tu string.

Los caracteres especiales se escapan anteponiendo un comilla simple, así que algo como `'SELECT aid FROM artistas WHERE anombre = ''caravaggio'' '` debería funcionar.

**Comment by jperalta2202** [comment]
Gracias!
