### ISSUE TITLE
No puedo ingresar al servidor

### ISSUE THREAD

**Issue by sgutgar** [IIC2413/Syllabus-2020-1#301]
Supongo que le pasa a todos, si pudieran dar información de cuando se va a arreglar por acá sería de gran ayuda.

**Comment by bmurtagh01** [comment]
Gracias por tu issue @sgutgar me está pasando lo mismo

**Comment by nivek0o0** [comment]
Hola, pasó que un grupo se comió la RAM del servidor, probablemente con un procedimiento recursivo mal diseñado.

Ahora deberían poder ingresar sin problemas. Me confirman plz.

**Comment by Cfvalenzuelar** [comment]
Ahí volvió! Gracias
