### ISSUE TITLE
dblink

### ISSUE THREAD

**Issue by sgutgar** [IIC2413/Syllabus-2020-1#302]
Hola estoy intentando hacer esto dblink(('dbname=grupoxxe3 user=grupoxx password=xxxxx','**select nombres from art(artists)**') donde art es un procedimiento almacenado creado en mi otra base de datos, y artists lo recibe la función en la base de datos actual por ejemplo trip(artists text, .....) lo que pasa es que me esta devolviendo el error dblink que no reconoce a la columna artists, como si no usara los valores ingresados en la función y tomara a artists como una columna de el procedimiento art. Que puedo hacer?

**Comment by nivek0o0** [comment]
Hola, esa consulta no va a reemplazar automáticamente los valores de `artists`, porque no le estás diciendo que lo haga. Solamente estás escribiendo y mandando la palabra o string "artists".

Te sugiero buscar formas de formatear el valor de una variable dentro de un string. Para consultas se usa `EXECUTE 'algún string para ser formateado' USING var1,var2;`. Para strings está la funcion format.
