### ISSUE TITLE
Itinerarios Condiciones a Cumplir

### ISSUE THREAD

**Issue by Tomas-Ira** [IIC2413/Syllabus-2020-1#303]
A la hora de desarrollar el itinerario, tengo un par de dudas, no entiendo bien a que se refiere cuando habla de 2 escalas.

1)Todas las ciudades visitadas (a excepción del origen) deben tener obras de algún artista seleccionado? 

2) El largo del viaje creado debe ser no mayor a 3 tickets? (esto considera 2 escalas y un destino final) o debe visitar todas las ciudades que cumplen algunas de las condiciones descritas abajo.

3) se deben visitar ciudades con obras de todos los artistas? (al menos una ciudad con una obra para cada artista seleccionado)?

4) Para cada artista, se tienen que visitar todos los países que tienen obras de estos artistas? 

5) Supongo que el viaje no debe considerar volver al origen, si lo quisiera hacer, se puede?

**Comment by nivek0o0** [comment]
0. dos escalas son 2 ciudades intermedias entre el origen y el final.

1. Sí, **alguna** obra de **algún** artista seleccionado. No es necesario ver todas las obras de un artista ni cubrir todos los artistas.

2. Correcto, máximo 3 tickets, es decir, máximo 4 ciudades incluyendo origen y final. 

3. No. Ver punto 1.

4. No, nunca se habla de países. Ver punto 1.

5. No es necesario volver al origen. Es válido repetir ciudades.

**Comment by Tomas-Ira** [comment]
Muchas gracias! Me queda solo una duda entonces.

Siempre la mejor opción va a ser visitar solo 1 ciudad (además del origen) ya que obviamente esto es siempre más barato que visitar otra ciudad después. 

La solución que me entregaría esto es visitar la ciudad más barata que conecta con el origen que tiene la obra de algún artista.

**Comment by nivek0o0** [comment]
No estamos frente a un problema de optimización, por lo que no buscamos la mejor solución.

Solo les pedimos algunos itinerarios que cumplan las condiciones.
