### ISSUE TITLE
Problema funcion make_time

### ISSUE THREAD

**Issue by ngermani** [IIC2413/Syllabus-2020-1#304]
Hola,

Quiero hacer una adicion con valores de tipo time pero me retorna el error siguiente que no entiendo:

![image](https://user-images.githubusercontent.com/62521654/83362852-8d3e1500-a362-11ea-9092-46e66fccbee3.png)

Igual traté al precisar que los valores son de tipo TIME ( time 't1.horario_1' + make_time(t1.duracion_1,0,0.00) < time 't2.horario_2') pero todavia no funciona.
Sabe cual es el problema?

Gracias

**Comment by nbnavarro** [comment]
Hola @ngermani!

Podrías probar lo siguiente (cambiar `time` por `interval`):
- `(interval 't1.horario_1' + make_time(t1.duracion_1,0,0.00) < interval 't2.horario_2')`
