### ISSUE TITLE
Problemas pasar array a funcion

### ISSUE THREAD

**Issue by danustilovsky** [IIC2413/Syllabus-2020-1#305]
Hola, estoy tratando de mostrar los resultados del procedimiento almacenado y use un multiple select para los artistas, lo que me entrega un array. Pero cuando trato de pasarle el array a la consulta me aparece el siguiente error:
 **ERROR: malformed array literal: "Array" DETAIL: Array value must start with "{" or dimension information.**
He buscado bastante pero no he podido encontrar como hacer para transformar el array de php a psql.
El array se ve asi: Array ( [0] => 1 [1] => 2 [2] => 3 )
Gracias!

**Comment by juanreutter** [comment]
No lo puedes ir navegando uno por uno? Total eso es solo para desplegar información, ¿o no?

**Comment by nivek0o0** [comment]
Probaste pasarlo como `'{ id1, id2, id3}'` ?
