### ISSUE TITLE
utilizar procedimiento almacenado desde php

### ISSUE THREAD

**Issue by tsgonzalez** [IIC2413/Syllabus-2020-1#306]
Hola! 

Desde php tengo que ejecutar las lineas: 

"\i procedimiento_almacenado.sql
  select procedimiento_almacenado(atributos)"

o solamente  hacer el "\i procedimiento_almacenado.sql" una vez  directamente en la base de datos y dejar la función creada para llegar y usarla desde php haciendo :

"select procedimiento_almacenado(atributos)" ?

**Comment by juanreutter** [comment]
Cada vez que usas \i es por que cargas el procedimiento almacenado en la base de datos. Por lo tanto, no es necesario usar \i más de una vez (y claro, si lo cambias un poco, tienes que volver a usarlo).

**Comment by nivek0o0** [comment]
Como dice Juan, se importa una única vez en la base de datos y queda creado para siempre. Por lo tanto no hay que hacerlo desde PHP.
