### ISSUE TITLE
[Entrega 3 - Problema con Dropear una tabla]

### ISSUE THREAD

**Issue by HenryBlairG** [IIC2413/Syllabus-2020-1#308]
Tuvimos un problema con la base de datos, queríamos incluir la clave para el login y al hacer `DROP TABLE ` en __grupo107e2__ el servidor se quedó pegado ahí. ¿Que podemos hacer? Aiiuuudaaa :sob:

**Comment by nivek0o0** [comment]
Hola, ¿por qué quieres hacer DROP TABLE? Hay comandos para añadir una columna a una tabla.

Por otra parte, ¿no deberían haber agregado la contraseña durante el desarrollo del proyecto y no ahora fuera de plazo?

**Comment by HenryBlairG** [comment]
El drop table lo decidimos usar por simpleza personal y caprichosa, por otra parte, esto ocurrio como a las 18.30, tal vez antes y desde entonces que estamos tratando de arreglarlo :sob: 
Piedaaaad :crying_cat_face:

**Comment by martucoss** [comment]
Y no es solo DROP TABLE, no nos deja hacer nada sobre la tabla, ni SELECT * FROM table; . Es como si estuviese rota la tabla en la base de datos y no podemos hacer nada para que funcione, intentamos DELETE FROM table y otras cosas, pero no podemos manejar nada referido a esa tabla. El problema empezó cerca de las 18:30, que quisimos resubir los datos a la db con el grupo.

**Comment by nivek0o0** [comment]
Es verdad que como a las 18:00 la BD no aceptó conexiones durante 20 minutos. Pero desde ahí siguió funcionando normalmente. 

Revisé y la base de datos que me dicen está completamente vacía. La única solución que puedo darles es que reconstruyan la BD hasta la medianoche.

**Comment by martucoss** [comment]
Listo solucionado ¿tu no hiciste nada en la base de datos?
O se arreglo solo?
¿Puede ser que si estabamos repoblando la base de datos cuando estaba caido se haya buggeado la tabla o algo así?
