### ISSUE TITLE
Guía álgebra relacional 3.4

### ISSUE THREAD

**Issue by ChayoPerez** [IIC2413/Syllabus-2020-1#31]
Hola! Es una duda bien noob D: En serio no entiendo como funciona lo de hacer producto cruz de la tabla consigo misma para sacar el resultado, y además me sale el error:
join would result in non unique column names; the following columns appear in both relations: Actores.anombre, Actuo_en.id_pelicula

Agradecería mucho una explicación :(

**Comment by bahidalgo** [comment]
Tenía el mismo error. Es porque ambas tablas tienen el mismo nombre, entonces sus columnas son iguales y no se pueden cruzar. Si usas la función rho para cambiar el nombre, puedes tener dos tablas (A y B) con distintos nombres y tendrás columnas diferentes del tipo A.anombre, A.id_pelicula, B.anombre, B.id_pelicula. 
Así pude cruzarlas después AxB

**Comment by ChayoPerez** [comment]
Y qué se hace después? T_T

**Comment by fjlopez7** [comment]
Si lo que quieres hacer es ejecutar la consulta en Relax, puedes ocupar el siguiente [Relax](https://dbis-uibk.github.io/relax/calc.htm?data=gist:6de6266bb2fea2b082a58c884d0069c6): La diferencia es que agregue la copia de Actuo_en como Actuo_en1, dado que en Relax hay problemas para ocupar tablas renombradas. 


En el caso que quieras agregar otra tabla anda a [gist.github.com](https://gist.github.com/), copias la información del [original](https://gist.github.com/jerrymendoza/6de6266bb2fea2b082a58c884d0069c6) y agrega la tabla que quieras duplicar siguiendo el formato del archivo. Guardas el archivo como un .txt y colocas el link del archivo en Relax.

**Comment by ChayoPerez** [comment]
Nono, lo que me preguntaba es qué hacer con el producto de las dos tablas para contestar el ejercicio ((4) Entrega el nombre de los actores que han actuado en mas de dos películas). Lo dijeron en la ayudantía creo pero fue después de que terminó la hora y no me pude quedar.

**Comment by nivek0o0** [comment]
Si cruzas la tabla Actuo_en consigo misma,  al tener una fila en cada mano ¿qué atributos deberías comparar para determinar que un mismo actor actuó en distintas peliculas?

**Comment by Crespy98** [comment]
debo comparar que el nombre del personaje sea el mismo pero tambien que la pelicula sea distinta?

**Comment by nivek0o0** [comment]
Exacto! Que el actor (aid) sea el mismo pero la película (pid) distinta.

Luego, ¿qué actores van a sobrevivir a ese Join? ¿Los que tienen 0, 1 o 2+ películas? (Intenta hacer un ejemplo a mano.

**Comment by Crespy98** [comment]
2 o  mas

**Comment by nivek0o0** [comment]
Y listo! Queda resuelta la 3.4.

Se debe pensar en cosas como ésta para responder este tipo de preguntas. Algo similar pasa cuando se desea encontrar un valor máximo o mínimo. 

A veces hay que encontrar el conjunto complemento de lo que me están pidiendo y restarlo al Universo.
