### ISSUE TITLE
Problema instalando mongo con consola

### ISSUE THREAD

**Issue by lucastack** [IIC2413/Syllabus-2020-1#312]
Hola!

Siguiendo la instalación de Mongo para uso de consola de aquí: [https://docs.mongodb.com/manual/tutorial/install-mongodb-on-windows/#run-mongodb-community-edition-from-the-command-interpreter](url), al llegar a ejecutar "C:\Program Files\MongoDB\Server\4.2\bin\mongod.exe" --dbpath="c:\data\db" ocurre esto

![image](https://user-images.githubusercontent.com/53802157/83701555-fda19c00-a5d7-11ea-9887-7713ce417240.png)

Y el proceso nunca termina. Llevo un rato viendo que puede ser pero no me anda 🤔

**Comment by juanreutter** [comment]
esta bien! Eso significa que el servidor va andando. Ahora tienes que abrir otra consola y correr mongo

**Comment by fcartoni** [comment]
Hola! Tengo una pregunta en la misma línea de esta issue. Instalé mongo, corrí el código "C:\Program Files\MongoDB\Server\4.2\bin\mongod.exe" --dbpath="c:\data\db" y funcionó igual que la foto de arriba. El problema es que cuando abro otra consola y corro lo que indica el tutorial de la wiki:
mongo -u grupoXX -p grupoXX gray.ing.puc.cl/grupoXX
me dice: bash: mongo: command not found
Probé abriendo la consola en distintas ubicaciones de mi computador (donde está instalado el ejecutador de mongo, y mil partes más) y me decía lo mismo.
¿Qué puede ser??
Gracias :)

**Comment by juanreutter** [comment]
Prueba con "C:\Program Files\MongoDB\Server\4.2\bin\mongo.exe" en vez de mongo

**Comment by juakoke** [comment]
Profe una duda, cuando ingrese al servidor de mongo con el mismo path que dio arriba, no me deja porque dice "shell and server versions do not match" y efecivamente mas arriba me dice que MongoDB shell version v4.2.7 y Mongo server version 4.0.18, que debo hacer ante esto?

**Comment by nivek0o0** [comment]
Hola @juakoke 

Eso solo es un warning, no debería darte problemas.
