### ISSUE TITLE
Duda entrega 1 hoteles (impares)

### ISSUE THREAD

**Issue by vicerc** [IIC2413/Syllabus-2020-1#32]
Se puede asumir que los hoteles tienen capacidad infinita?

**Comment by fjlopez7** [comment]
Da lo mismo la capacidad del hotel, ya que como dice el enunciado, no es necesario guardar cosas internas del hotel.

![image](https://user-images.githubusercontent.com/42160988/77273899-6e9d0d00-6c93-11ea-8df6-12f38438396f.png)

**Comment by vicerc** [comment]
ok, graciaas

**Comment by Fernan-tess** [comment]
Respecto a los hoteles. Si una persona compra un ticket para transportarse entre las ciudades, necesariamente reserva un hotel con nuestra empresa? O puede solamente comprar el ticket para transportarse?

**Comment by nivek0o0** [comment]
Puede o no comprar tickets con nuestra agencia así como puede o no reserver hoteles con nosotros en las ciudades que visita.

No pueden asumir nada sobre la relación entre tickets y reservas.
