### ISSUE TITLE
Duda text search

### ISSUE THREAD

**Issue by lucastack** [IIC2413/Syllabus-2020-1#327]
Hola!

En la entrega 4 se nos pide que los 4 criterios deben aplicarse en forma simultánea usando la funcionalidad _text search_ . Con esto se refieren a que

1. Sólo se puede hacer **una** consulta a la base de datos para satisfacer los 4 criterios
o 
2. Simplemente que los mensajes que se retornen en la ruta satisfagan los 4 criterios de forma simultánea

Saludos👋

**Comment by nivek0o0** [comment]
Hola, nos referimos al punto 2.
