### ISSUE TITLE
Preguntas entrega 1 proyecto

### ISSUE THREAD

**Issue by fcartoni** [IIC2413/Syllabus-2020-1#33]
Hola! Tengo algunas preguntas sobre la entrega:
1. El pdf que hay que subir puede ser hecho en Word? O piden algo específico?
2. Sale que en el pdf hay que incluir las tres primeras consultas en álgebra relacional. Las otras tres hay que ponerlas explicadas con palabras o es solo para guiarnos para hacer las tablas con los atributos correctos?
3. La tabla que hay que crear en psql, solo la creamos y con ella una tupla,  y ustedes la corrigen desde ahí mismo o tenemos que subirla de alguna forma?
Gracias!

**Comment by nivek0o0** [comment]
Hola!

1. Sí, puedes hacerlo en Word, Latex, lo que sea. Lo importante es que esté ordenado.

2. Sí, solo debes entregar las 3 primeras y la idea es poder guiarlos.

3. Nosotros la corregimos en postgres, así que no es necesario que hagan nada más :smiley:
