### ISSUE TITLE
Entrega 1 relacion tabla artistas y obras

### ISSUE THREAD

**Issue by rociomartineza** [IIC2413/Syllabus-2020-1#34]
como la relación artistas es n:n creamos una tabla que relacionara cada id de la obra con los respectivos id de los artistas de cada una. Sin embargo no pusimos una llave primaria para cada relacion. Es necesario que esta tabla tenga una llave primaria aunque no la vayamos a usar??

**Comment by nivek0o0** [comment]
Hola, en general la llave primaria de una tabla intermedia como la que mencionas se compone de los IDs de las entidades que están relacionándose.
