### ISSUE TITLE
Consultas en algebra relacional - Entrega 1 grupo Par

### ISSUE THREAD

**Issue by danustilovsky** [IIC2413/Syllabus-2020-1#36]
Hola,

Estabamos haciendo las consultas 2 y 3 en logica relacional, y nos surgieron un par de dudas:
1. Cuando no se especifica un atributo a proyectar se debe proyectar la entidad completa, pero claramente depende de como se haya estructurado esta, por lo tanto que es lo minimo que se debe retornar en la consuta 2? Basta con Id, tipo, nombre o debemos agregar los horarios, precios, etc.
2. Dado que tampoco especifica la entidad a retornar en la consulta 3. Nos confunde que se deban entregar la entidad entera dado que se habla de Iglesias y Plazas las cuales tienen atributos diferentes, por lo tanto basta con entregar aquellos que tienen en comun, dado que lo que entendemos es que para hacer una Union (U) es necesario que las tablas tengas los mismos atributos.

O si podemos enviarle a alguien la estructura de estas tablas, para que entienda donde nos entra la duda.

Gracias!!

**Comment by nivek0o0** [comment]
Hola,

1. Cuando se pide "entregar una entidad" basta con el **id y el nombre** en álgebra relacional. En otras palabras, los atributos básicos para distinguir esas filas de otras.
Esto cambiará en el futuro cuando implementen la consulta en su aplicación web, porque allí deberán mostrar todas las columnas de la entidad.

2. Para hacer una Unión, los atributos de cada tabla pueden llamarse distinto, pero deben ser del mismo tipo en el mismo orden. Además tener la misma cantidad de atributos en cada tablas.
Dicho lo anterior, puedes responder la C3 si unes solamente ID y nombre de plazas y museos.
En la aplicación web, lo que puedes hacer para mostrar todos los atributos es evadir la Unión, pidiéndolos por separado y mostrando el resultado en tablas distintas.
