### ISSUE TITLE
Problema con el servidor

### ISSUE THREAD

**Issue by lucastack** [IIC2413/Syllabus-2020-1#363]
Hola!

Hace unos días todo funcionaba bien con nuestra entrega, sin embargo, al entrar hoy para volver a trabajar me percato que nuestra colección de mensajes simplemente no funciona. Esto lo digo porque al entrar al servidor por consola y hacer `db.messages.find({}, {});` no entrega nada y se queda pegado. Obviamente hacer las consultas por Postman tampoco funciona por esto mismo. Además, con la colección de usuarios todo anda bien.

Me parece muy raro porque es la segunda vez que nos pasa con esta entrega y de verdad no hemos hecho modificaciones. Simplemente deja de funcionar de un día para otro.

**Comment by nivek0o0** [comment]
Hola, necesito ver tu aplicación para poder debuggear el origen el error. Si está subida puedes decirme el numero de grupo, sino enviármela por coreo.

**Comment by lucastack** [comment]
Al final me di cuenta de que no se quedaba pegado, si no que tardaba demasiado (más de 5 minutos) en hacer las request de los mensajes.  Las rutas funcionan bien, entregan lo que deberían con los _tests_ que subieron, sin embargo pasa lo que acabo de describir.

Somos el grupo 52! ya subí la API al servidor

**EDIT**: Hay ocasiones en que las request andan bien y se demoraban prácticamente nada. Así que si no es porque el servidor está colapsado con gente, no se me ocurre que puede ser.
