### ISSUE TITLE
Entrega control Álgebra Relacional

### ISSUE THREAD

**Issue by IriSalazar** [IIC2413/Syllabus-2020-1#37]
Hola! :D 
El control puede ser escrito a mano y luego escaneado a pdf? O prefieren otra forma?

**Comment by nivek0o0** [comment]
Hola, 
sí se puede, pero la letra debe estar super clara, porque las respuesta que no se entiendan no serán corregidas. :skull: 

Si no tienen escáner en casa pueden usar la aplicación :iphone: CamScanner que saca fotos y te las entrega en un PDF.
