### ISSUE TITLE
Pregunta Entrega 1 Proyecto (Impar)

### ISSUE THREAD

**Issue by FabsHazard** [IIC2413/Syllabus-2020-1#39]
En la consulta 3.
Se consideran las ciudades a las que viajo o también las ciudades desde la que se viajó?

**Comment by nivek0o0** [comment]
Hola!
Ambas. Por ejemplo, si en el sistema aparece que Juan viajó de **Nápoles** a **Madrid**, ¿en qué países ha estado?
