### ISSUE TITLE
Duda sobre keys.

### ISSUE THREAD

**Issue by nhorellana** [IIC2413/Syllabus-2020-1#4]
Hola! En la parte del esquema, si una relación tiene más de una key posible (por ej, id y rut) al escribirlo tenemos que subrayar ambas o escogemos una arbitraria como principal?

**Comment by arpincheira** [comment]
Hola, con respecto a tu pregunta, si tu consideras que hay dos _Primary Keys_, debes subrayar ambas.

Pero si ambas cumplen el objetivo de una _primary key_, entonces basta con escoger aquella que sea más fácil de implementar (por ejemplo ints sobre strings), ya que tener ambas es redundante.

Saludos

**Comment by nhorellana** [comment]
Gracias!
