### ISSUE TITLE
Entrega 1 - Consulta 2 impares

### ISSUE THREAD

**Issue by furzuadr** [IIC2413/Syllabus-2020-1#40]
Hola! Cuando me piden las ciudades del país con nombre 'p' en donde la agencia tiene presencia, debo entregar la id de la ciudad y el nombre solamente?
Gracias!

**Comment by nivek0o0** [comment]
Sí, es suficiente con esos atributos para cualquier consulta que "pida una entidad", pero si los entregas todos no habrá problema.
