### ISSUE TITLE
Duda de Enunciado Control 1

### ISSUE THREAD

**Issue by lucastack** [IIC2413/Syllabus-2020-1#41]
Hola!

En la consulta 4 se nombra a aquellos que hagan varias compras y en total tengan al menos dos productos distintos, o se refiere a que en un sólo pedido compren más de una unidad?

**Comment by itplanella** [comment]
Hola! en la isse #20 respondieron esto, te copio la respuesta:

"Hola,
son los clientes que han pedido al menos dos productos distintos, sin importar la cantidad que haya pedido de cada uno."

**Comment by lucastack** [comment]
No la había visto! Gracias!
