### ISSUE TITLE
Duda join

### ISSUE THREAD

**Issue by itplanella** [IIC2413/Syllabus-2020-1#42]
Hola! si tengo tres tablas distintas "a", "b", "c", donde "a" tiene una columna "tipo" y luego hago los siguientes join y renombrar:

ab = a join b
abc= ab join c

para seleccionar algo de la columna "tipo" de la tabla "abc" debería ser de la forma "ab.a.tipo = ..." o simplemente "a.tipo = ..."=

**Comment by nivek0o0** [comment]
La forma ultra super correcta sería renombrar cada atributo luego de hacer el JOIN.

Por ejemplo, si en la tabla resultante "AB" te quedaran las columnas `A.tipo` y `B.tipo`, podrías renombrarlas como `tipo_pelicula` y `tipo_actor`. Luego mi tabla AB tendría `AB.tipo_pelicula` y `AB.tipo_actor` y ya no ocurriría el problema de `AB.A.tipo`

**Pero**, en este curso no somos tan puristas y consideraremos correcto hacer `AB.A.tipo`, ya que se puede pensar que lo que hay después del primer punto es un string con el nombre de la columna, y cada vez que se hace un join, a ese string se le antecede el nombre de la tabla. Incluso esta forma es más rápida de entender.

Aún así, si es posible te recomiendo hacer el triple join y renombrar el resultado. Es más directo.

**Comment by itplanella** [comment]
Muchas gracias!
