### ISSUE TITLE
Ubicación readme E5

### ISSUE THREAD

**Issue by JuaniAndres** [IIC2413/Syllabus-2020-1#432]
Hola una duda en que ubicación ponemos el readme de esta entrega?
gracias de antemano

**Comment by nivek0o0** [comment]
Hola, el README va en la carpeta `Entrega5` del servidor `codd.ing.puc.cl`, mientras que la aplicación va en la carpeta `Sites`

**Comment by jitorcas** [comment]
@nivek0o0 

Para tenerlo más claro:

***Entrega 5***
- api.zip actualizada
- README

***Sites***
- app PHP actualizada 

¿Está bien así?

**Comment by nivek0o0** [comment]
**Entrega5**

- Readme.md

**Sites**

- app PHP actualizada

**Comment by nivek0o0** [comment]
Por favor ser rigurosos con el nombre de las carpetas

**Comment by jitorcas** [comment]
Ok, entonces solo enunciamos los cambios que le hicimos a la api en el README
