### ISSUE TITLE
Entrega 1(Proyecto) - Consulta 2 impares

### ISSUE THREAD

**Issue by FabsHazard** [IIC2413/Syllabus-2020-1#44]
Al mencionar "Muestre todas las ciudades del pais con nombre `p' en donde la agencia tiene presencia." Se refiere a que en los datos puede haber un pais con nombre p? o hay que buscar los paises que contengan la p adentro o los paises que empiezan con p?

**Comment by fjlopez7** [comment]
La pregunta esta respondida en la issue #5 y #35.
