### ISSUE TITLE
Duda Pregunta 6 Control 1

### ISSUE THREAD

**Issue by VicenteEspinosa** [IIC2413/Syllabus-2020-1#45]
Hola, quería saber si puedo asumir que el producto mas caro es "Tierra de hojas 4", o debo pensar que se puede agregar un nuevo producto de mayor valor.

**Comment by arpincheira** [comment]
Hola,
puede que tu pregunta haya sido contestada en la issue #27 de todos modos recomiendo siempre pensar en el caso de que a la base de datos se le puede añadir un dato adicional, por ende no pueden basarse solo en el ejemplo propuesto para responder el control.

Saludos
