### ISSUE TITLE
Entrega 1(Proyecto) - Consulta 3 impares

### ISSUE THREAD

**Issue by FabsHazard** [IIC2413/Syllabus-2020-1#46]
En la consulta 3, si el usuario con nombre 'u' viajo varias veces y por ejemplo paso por el mismo país dos veces, tengo que mostrar solo una vez el país que visito o se pueden mostrar duplicados?

**Comment by arpincheira** [comment]
Hola,
dentro de lo que vienen siendo las consultas a una base de datos, si tu consulta busca solamente los nombres de los países donde viajó el usuario con nombre 'u', la respuesta de esta siempre va a evitar las repeticiones dentro de lo que vienen siendo tus resultados(en este caso el nombre del país a visitar). 
De todos modos, hay que destacar que en el caso de que tu consulta busque datos adicionales, la respuesta añadirá aquellos viajes que tengan el mismo destino pero difieran en un dato, al final de cuentas sigue siendo un viaje diferente.

Recuerda que en álgebra relacional no existen los duplicados, así que no tendrás que preocuparte allí. Al implementarla en SQL tendrás que usar un comando especial para removerlos.

Espero haberte ayudado con mi respuesta
