### ISSUE TITLE
Tipo de dato 'contacto telefónico' en tabla Ciudades

### ISSUE THREAD

**Issue by MGome** [IIC2413/Syllabus-2020-1#47]
Hola buenas! Tengo una duda sobre el tipo de dato que será el contacto en la tabla ciudades. Ya que si fuera de la forma "2222222" se podría considerar como un int, sin embargo si es de la forma "+2222222" se le debe considerar como un varchar. De qué manera lo debo expresar? o es irrelevante para esta entrega?

**Comment by fjlopez7** [comment]
Revisa la issue #3.
