### ISSUE TITLE
[Duda Proyecto] creación tabla

### ISSUE THREAD

**Issue by amaiajuanchuto** [IIC2413/Syllabus-2020-1#48]
Cuando nos piden ingresar a la base de datos en el servidor y crear una tabla. Tengo que distinguir cual es mi PRIMARY KEY o simplemente la dejo como un INT y le pongo un nombre como "algo_id"?

**Comment by nivek0o0** [comment]
La idea de eso es que se familiaricen con la BD, por lo tanto para cumplir puedes crear cualquier cosa con cualquier atributo. 

Pero, yo te recomiendo que empieces a crear las tablas de tu esquema y así adelantas trabajo :smile:
