### ISSUE TITLE
Especificacion de la condicion para un 'natural join' en Control1

### ISSUE THREAD

**Issue by jnvillarroel** [IIC2413/Syllabus-2020-1#49]
Queria saber si es necesario especificar la condicion de filtro cuando uso u natural join, en otros casos entiendo que es importante especificarlo, pero si comparo dos tablas que tienen en común solo, por ejemplo: clienteid, es necesario especificarlo? Quedan soluciones gigantes

**Comment by nivek0o0** [comment]
No es necesario. Esa es la gracia de los EquiJoins, no tener que especificar la condición de igualdad porque se asume que se comparan los atributos con el mismo nombre.

El Natural Join es un tipo de EquiJoin en donde las columnas del mismo nombre no quedan duplicadas en el output.
