### ISSUE TITLE
Consultas del Esquema (1.2) 

### ISSUE THREAD

**Issue by maribeiro97** [IIC2413/Syllabus-2020-1#5]
En la consulta 2 de la sección 1.2 del enunciado dice que debemos encontrar "las ciudades del país con nombre 'p' ", esto es correcto o se refiere a ciudades que contengan 'p' o empiecen con 'p'?

**Comment by fjlopez7** [comment]
La primera forma que dices es la correcta. Piensa que "p" es una variable que puede contener cualquier cosa.
