### ISSUE TITLE
Duda en conectar el repositorio con el servidor

### ISSUE THREAD

**Issue by sebacarrasco** [IIC2413/Syllabus-2020-1#52]
Al tratar de conectar el repositorio con el servidor estaba saliendo todo bien hasta que quise hacer el primer pull. Luego de ingresar `<git branch --set-upstream-to=origin/master master>`, me aparece el siguiente error: `<fatal: branch 'master' does not exist>`, siendo que sí existe esa rama (de hecho, es la única del repositorio)

**Comment by nivek0o0** [comment]
Hasta donde tengo entendido, cuando inicias un repositorio local por primera vez no existe ninguna rama.
Intenta hacer primero ` git pull origin master` y luego el setupstream.

**Comment by sebacarrasco** [comment]
Ahí me funcionó. Muchas gracias!
