### ISSUE TITLE
Duda respecto a característica de los frescos 🤔 🎨 👨‍🎨 

### ISSUE THREAD

**Issue by moquezada** [IIC2413/Syllabus-2020-1#53]
En la sección 2.1 del enunciado para los grupos pares, se indica que las pinturas tienen una técnica en particular y que las esculturas están hechas de cierto material, pero no se indica nada respecto a los frescos. ¿Cuál sería la característica de los frescos en este caso? Además, considerando que los frescos son un tipo de pintura que se realizó de cierta forma, ¿deberíamos incluirlos en la categoría de pinturas?

**Comment by nivek0o0** [comment]
Hola,
para este proyecto vamos a considerar las Pinturas, Frescos y Esculturas como 3 entidades distintas e independientes. Así que los Frescos NO están incluidos dentro de las Pinturas.

Los Frescos no tienen atributos adicionales a los que son comunes a todas las Obras de Arte, vale decir nombre, ambas fechas, periodo y lugar donde están.

**Comment by moquezada** [comment]
Buena, muchas gracias!
