### ISSUE TITLE
Duda Lugares entrega 1 pares

### ISSUE THREAD

**Issue by pureyesz** [IIC2413/Syllabus-2020-1#55]
En el caso de los lugares se debe trabajar iglesias, museos o plazas como tres entidades independientes? (¿una tabla para cada tipo de lugar?)

**Comment by nivek0o0** [comment]
Iglesias, Museos y Plazas son 3 entidades independientes.

La manera en que vayas a almacenarlos es tu decisión. Aún no han visto materia sobre diseño de BDs pero existe una forma de implementar entidades que son _del mismo tipo_
