### ISSUE TITLE
Duda consultas entrega 1

### ISSUE THREAD

**Issue by elisafdz** [IIC2413/Syllabus-2020-1#57]
Hola!

Para escribir las consultas en álgebra relacional se pueden usar funciones que no esten en la guía?

Muchas gracias!

**Comment by elisafdz** [comment]
y otra duda! si un usuario compra un ticket para ir de c a d puedo asumir que ese usuario visito c y d?

Gracias!

**Comment by nivek0o0** [comment]
Hola!

Estas preguntas fueron respondidas en las issues #21 y en la #39
