### ISSUE TITLE
Creación de tabla en BD

### ISSUE THREAD

**Issue by FeBalla** [IIC2413/Syllabus-2020-1#58]
Hola, quería saber si es necesario crear la tabla en la base de datos con la importación de un .csv o podemos directamente crearla desde la terminal con los comandos de PSQL (CREATE TABLE).
¡Gracias!

**Comment by nivek0o0** [comment]
Ambas opciones son válidas. Yo recomiendo la 1ra que mencionas para que aprendan cómo importar los .csv
