### ISSUE TITLE
Duda Sqlite3

### ISSUE THREAD

**Issue by danustilovsky** [IIC2413/Syllabus-2020-1#59]
Hola, 

Si ya tengo instalado Postgresql, me conviene instalar sqlite3? O se utilizan los mismos comandos y puedo quedarme con Postgresql?

Gracias,

**Comment by MarceloSaldias** [comment]
Hola!

PostgreSQL y SQLite3 usan comandos diferentes para escoger una base de datos y cambiar algunas configuraciones del sistema de bases de datos.

Sin embargo, ambas usan el mismo lenguaje de consultas SQL.

Si ya estas familiarizado con el uso de Postgres, no hay problema en que lo uses. Recomendamos SQLite3 por su facilidad de instalación y uso solamente.
