### ISSUE TITLE
Duda condición Join

### ISSUE THREAD

**Issue by vchadwick** [IIC2413/Syllabus-2020-1#60]
Hola, en el álgebra relacional, ¿se puede crear un Join con doble condición y que estas no sean necesariamente de igualdad?, es decir, sean:

u, v condiciones.
**A, B** tablas

**A** Join_{u y v} **B**

¿Se puede para más de 2 condiciones?

**Comment by nivek0o0** [comment]
Sí, puedes poner la cantidad de condiciones que desees en un Join.
