### ISSUE TITLE
duda pedidos control 1

### ISSUE THREAD

**Issue by javieranavarrete** [IIC2413/Syllabus-2020-1#61]
hola, en el ejemplo se ve que cada pedido incluye solo un id de producto, esto siempre será así o puede ser que un pedido incluya mas de un id de producto. Es decir, es posible que la tabla tuviese dos o más tuplas con el mismo oid, pero con distintos pid? ejemplo:

pedidos
oid | cid | pid | cantidad | ... |
1    |   3 |  4   |  2           | ....|
1    |   3 |  2   |  7           | ....|

**Comment by nivek0o0** [comment]
Hola!
**siempre** un pedido tendrá un **único** producto

**Comment by javieranavarrete** [comment]
muchas gracias!

**Comment by juanreutter** [comment]
Hola, solo agregar: ¡el enunciado deja esto claro! 

Lo que pasa es que oid es **llave** de la tabla de pedidos. Ser llave significa exactamente lo que tu dices: no pueden existir dos tuplas distintas con el mismo oid.
