### ISSUE TITLE
Problema con la librería ipython-sql

### ISSUE THREAD

**Issue by Jprampad** [IIC2413/Syllabus-2020-1#62]
Hola!
Adjunto fotos del troubleshoot
<img width="1081" alt="Captura de Pantalla 2020-03-25 a la(s) 16 59 01" src="https://user-images.githubusercontent.com/49689744/77580251-72f73f00-6eba-11ea-9a8c-e0b45cd006c7.png">
<img width="1014" alt="Captura de Pantalla 2020-03-25 a la(s) 16 59 13" src="https://user-images.githubusercontent.com/49689744/77580266-78ed2000-6eba-11ea-8472-d839cffe854b.png">

**Comment by MarceloSaldias** [comment]
Algunas preguntas para ir descartando

- Cual es tu sistema operativo?
- Que comando utilizaste para instalar ipython-sql? (`pip` o `pip3`)

**Comment by Jprampad** [comment]
MacOs Catalina version 10.15.3
pip3

**Comment by MarceloSaldias** [comment]
Prueba instalando con pip, el comando sería `pip install ipython-sql`
Si no te funciona con eso, deberias probar con `sudo pip3 install ipython-sql`

**Comment by Jprampad** [comment]
ninguno de los dos funcionó  :(

**Comment by MarceloSaldias** [comment]
De lo que pude encontrar, podrias probar ejecutando el siguiente comando:

    sudo python3 -m pip install python-sql

Ojo que es `python-sql`, que es distinto a lo que siempre has usado que es `ipython-sql`. 
Si ya esto no te funciona, te recomiendo fuertemente que uses Google Colab para abrir los notebooks

**Comment by Jprampad** [comment]
no funcionó, muchas gracias de todas formas!
Google Colab apañará
