### ISSUE TITLE
Respecto a la entrega 1, es necesario que todos los esquemas tengan una key?

### ISSUE THREAD

**Issue by DonJavi-538** [IIC2413/Syllabus-2020-1#63]
Al igual que en el título. Mientras hacia la entrega 1 me surgió esta duda, todos los esquemas tienen que tener una key? o pueden haber algunos sin key?

**Comment by MarceloSaldias** [comment]
Hola!
Depende netamente de tu modelación. Perfectamente pueden existir esquemas que no tengan una primary key, mientras expliques el razonamiento que hay detras en el PDF debería estar todo bien!
