### ISSUE TITLE
Problema al actualizar Syllabus

### ISSUE THREAD

**Issue by pelao97** [IIC2413/Syllabus-2020-1#64]
Hola al actualizar el Syllabus, para un futuro. Me aparece este problema.

![image](https://user-images.githubusercontent.com/42186906/77582742-a2a84600-6ebe-11ea-9f27-d6726098e9d6.png)

Queria saber que puedo hacer para solucionarlo.

Gracias!

**Comment by fjlopez7** [comment]
Intenta con git fetch origin.

**Comment by pelao97** [comment]
No me funcionó :(.
Hice git fetch origin, y luego git pull pero me tira el mismo error

**Comment by fjlopez7** [comment]
No puedes ocupar git pull y mantener los archivos que modificaste.
Por eso te recomendé usar git fetch origin que descarga los archivos nuevos del repo y no modifica tus cambios.

**Comment by pelao97** [comment]
Perfecto, osea es un equivalente al git pull sin tocar los cambios que yo realice??
