### ISSUE TITLE
Doble producto cruz

### ISSUE THREAD

**Issue by bgfeuereisen** [IIC2413/Syllabus-2020-1#66]
Hola buenas,
Cómo hago para realizar un doble producto cruz en SQL y para renombrar una tabla?
gracias

**Comment by TamaraCucumides** [comment]
Hola, para renombrar puedes hacer

```
SELECT *
FROM Productos AS P1. Productos AS P2
WHERE ...
```

con doble producto cruz te refieres a un producto cruz de una tabla consigo misma??

**Comment by bgfeuereisen** [comment]
Con doble producto cruz me refiero a que hago tabla1 cruz tabla 2 y después el resultado de ese producto cruz hacer producto cruz con tabla 3

**Comment by TamaraCucumides** [comment]
Para hacer producto cruz entre varias tablas basta con especificarlas en el FROM, es decir

```
SELECT *
FROM Tabla1 AS T1. Tabla2 AS T2, Tabla3 AS T3
WHERE <condition_1> AND <condition_2>
```
