### ISSUE TITLE
Notebook SQL

### ISSUE THREAD

**Issue by danustilovsky** [IIC2413/Syllabus-2020-1#69]
Hola, 

Seria posible que suban el notebook resuelto? o al menos el resultado de las consultas para poder revizar lo que vamos haciendo?

Gracias!!

**Comment by mihenriquez** [comment]
Hola! No se subirá ni el notebook resuelto ni el resultado de las consultas. Parte de su trabajo es saber y entender qué está haciendo tu consulta, te servirá como ejercicio, pero si tienes alguna pregunta sobre el notebook no dudes en abrir una issue!
