### ISSUE TITLE
Duda RelaX

### ISSUE THREAD

**Issue by oscars810** [IIC2413/Syllabus-2020-1#7]
Hola, quisiera saber como se escribiría la siguiente consulta en RelaX.

_Rho_ (A1, Actuo_en)
_Rho_ (A2, Actuo_en)
_Pi_ anombre (A1 _join_ Actores _join_ A2)

**Comment by jerrymendoza** [comment]
Hola @oscars810,
El Self Join se utiliza cuando una tabla referencia a otra **más de una vez**, en el caso que planteas, hacer un Self Join se vuelve innecesario*.

De todas formas te dejo como seria en RelaX:
(1) π Actores.anombre ( (ρ A1 (Actuo_en)) ⨝ Actores ⨝ (ρ A2 (Actuo_en)))
(2) π Actores.anombre ( (ρ A1 (Actuo_en)) ⨝ Actores )
*(1) y (2) son la misma consulta

RelaX lamentablemente no guarda en memoria los renombre, hay que hacerlo en una sola consulta.
Para que puedas probar el Self Join, agregue un dataset de Usuarios y Sigue_A.

**Comment by jmndoza** [comment]
Hola @oscars810,
El Self Join se utiliza cuando una tabla referencia a otra **más de una vez**, en el caso que planteas, hacer un Self Join se vuelve innecesario*.

De todas formas te dejo como seria en RelaX:
(1) π Actores.anombre ( (ρ A1 (Actuo_en)) ⨝ Actores ⨝ (ρ A2 (Actuo_en)))
(2) π Actores.anombre ( (ρ A1 (Actuo_en)) ⨝ Actores )
*(1) y (2) son la misma consulta.

También notaras que el renombre no ayuda en nada, en general, se utiliza para diferenciar un atributo con mismo nombre, pero de distinta tabla ej.: Animal.nombre y Humano.nombre, si hago un Join de Hombre y Animal, me quedarían dos campos **nombre**. Agregue un dataset de **Usuarios** y **Sigue_A** para que puedas probar esto y el Self Join.
[-> RelaX](https://dbis-uibk.github.io/relax/calc.htm?data=gist:6de6266bb2fea2b082a58c884d0069c6)

(RelaX lamentablemente no guarda en memoria los renombre, hay que hacerlo en una sola consulta)
EDIT:  Olvide el caso que te pueda servir para la 3.4, dado que solo proyectabas el nombre.

**Comment by cchauriye** [comment]
Hola! Qué puedo hacer para que no me queden atributos con el mismo nombre al hacer el join? (como en el ejemplo que das). Gracias!

**Comment by jmndoza** [comment]
Hola, @cchauriye 
Puedes utilizar el renombre(ρ) en la misma linea, si te fijas en el ejemplo (1) que escribí, utilice Actuo_en como A1 y también como A2. Luego lo utilizas como A1.nombre A2.nombre

**Comment by cchauriye** [comment]
Claro, pero hago:
Pedidos1 = ρ Pedidos1 (Pedidos)
Pedidos2 = ρ Pedidos2 (Pedidos)
Pedidos3 = ρ Pedidos3 (Pedidos1 ⨯ Pedidos2)
y me tira un error por ambiguedad. Sabes que puede ser?

Gracias!

**Comment by jmndoza** [comment]
Ah! El problema es que Relax solo permite el renombre dentro de la misma declaración, luego de eso "se olvida" : ` (ρ Pedidos1 (Pedidos) ⨯ ρ Pedidos2 (Pedidos))`
Y ojo, el `=` en sql es para comparación, no para asignación.

**Comment by jmndoza** [comment]
@cchauriye , un ejemplo mas completo:
Supongamos que (por alguna razón) quieres comparar las cantidades entre la misma tabla:
`π Pedidos1.cantidad > Pedidos2.cantidad (ρ Pedidos1 (Pedidos) ⨯ ρ Pedidos2 (Pedidos))`
