### ISSUE TITLE
Primary Key entre entidades [Entrega1]

### ISSUE THREAD

**Issue by carajila** [IIC2413/Syllabus-2020-1#70]
Tengo una duda si existirían duplicados de lid (id del lugar) o problemas en consultas futuras al presentar las entidades de esta forma:

Lugares(**lid**, ....)

Museos(**lid**, ....)
Iglesias(**lid**, ....)
Plazas(**lid**, ....)

¿O como yo seré quien ingrese los datos, no se producirían problemas o duplicados con las primary keys de estas tablas?

**Comment by nivek0o0** [comment]
Suponiendo que Museos, Iglesias y Plazas estarán también en la tabla Lugares, no vas a poder repetir los IDs entre ellos. Por ejemplo, no podrías tener museos 1,2,3 e iglesias 1,2,3. El requisito es que cada tabla tenga una PRIMARY KEY.

Al principio, tendrás que pre-procesar los datos que les pasemos para importarlos a tu esquema. Nuestros datos **vienen sin ID**, así que tendrás que asignarles IDs a las entidades para que respeten tu esquema, por lo que dependerá solo de ti el tener problemas con IDs duplicados o no.

Luego, será la aplicación la encargada de manipular la BD, y como tú la programarás, también dependerá de ti si habrán problemas futuros o no. Es la aplicación la que debe elegir que ID ponerle a la nueva entidad, a menos que los IDs estén implementados como tipo SERIAL, en cuyo caso se encarga la BD.
