### ISSUE TITLE
Instalación de programas

### ISSUE THREAD

**Issue by assilva2** [IIC2413/Syllabus-2020-1#71]
Aún no puedo instalar los programas del curso. Me pide actualizaciones del computador que no se pueden hacer, porque según el sistema tiene las mejores versiones para el computador.

**Comment by MarceloSaldias** [comment]
Hola!

Asumo que con programas del curso te refieres a Jupyter Notebooks, SQLite3, Python, ipython-sql.

Cómo se menciona en [esta entrada de la wiki](https://github.com/IIC2413/Syllabus-2020-1/wiki/Preparaci%C3%B3n-Jupyter-Notebooks) no es necesario instalar nada en sus ordenadores, pueden utilizar Google colab para esto.

Si o si necesitan un cliente SSH para conectarse a su servidor de proyecto, pero no deberían tener problemas para instalar esos programas.

**Comment by Fernan-tess** [comment]
Yo no puedo instalar el###  pip3 install ipython-sql, me aparece ese error 


![error 2](https://user-images.githubusercontent.com/53883016/77730557-c9aa6900-6fdf-11ea-9c4b-6ec8547099c7.PNG)
![error 1](https://user-images.githubusercontent.com/53883016/77730565-cb742c80-6fdf-11ea-9df0-19632a7e6247.PNG)

**Comment by MarceloSaldias** [comment]
Prueba con alguno de estos comandos, hacen esencialmente lo mismo:

    pip3 install wheel
    python3 -m pip install wheel

y luego vuelve a intentar con la instalación de ipython-sql
