### ISSUE TITLE
Exigencia paises visitados

### ISSUE THREAD

**Issue by jfernandez7** [IIC2413/Syllabus-2020-1#72]
Hola! En la consulta 3 de los grupos impares hay que incluir el caso en que el viaje esté en curso y no se haya llegado al destino? Habría que "sumar" la duración a la fecha del viaje y restrinjir eso? En caso de que si, podemos asumir formatos compatibles entre estos datos?

**Comment by nivek0o0** [comment]
Hola,
si al momento de ejecutar la consulta el viaje está en curso, técnicamente la persona aún no visita el país de destino, por lo que no debería aparecer en la respuesta. El de origen sí debería. Consideraremos que un usuario ha visitado el país inmediatamente después de llegar a él en su viaje.

Sí, tendrías que hacer operaciones entre fechas, horas y duraciones para determinar si el viaje ya llegó o no.

Sí, puedes asumir en **álgebra relacional** que el formato de estos atributos es totalmente compatible entre ellos y puedes restarlos, sumarlos, etc.

**Comment by jfernandez7** [comment]
Muchas gracias!

**Comment by Tomas-Ira** [comment]
Como llamo a la hora de la consulta? Now(Timestamp)??

**Comment by Pdesolmi** [comment]
Me uno a la pregunta de Tomás

**Comment by nivek0o0** [comment]
En álgebra relacional da lo mismo, mientras se entienda lo que quieres hacer.

Algunas opciones son:
* time.now()
* date.now()
* timestamp.now()
