### ISSUE TITLE
Dudas Entrega 1 Proyecto

### ISSUE THREAD

**Issue by mariajesusbraun** [IIC2413/Syllabus-2020-1#73]
Hola!! Tengo un par de preguntas respecto a la Entrega 1:

1. ¿Importa haber creado más de una tabla en el servidor? Las creé y después me fijé que sólo había que crear una. ¿Es necesario borrarlas? No tienen ninguna tupla.
2. Para ingresar una tupla a una de esas tablas, ¿se usan datos inventados o están en alguna parte?

Gracias!

**Comment by nivek0o0** [comment]
Hola!

1. Se pide **al menos** 1 tabla con **al menos** 1 tupla. Entonces no necesitas borrarlas, pero si insertarle tuplas.
2. Por ahora se usan datos inventados. Si pudieses aprender a subir un CSV sería lo ideal. La idea de esta entrega es que se familiaricen. En la Entrega 2 les pasaremos datos reales.

**Comment by mariajesusbraun** [comment]
Ya perfecto.
¿Se puede insertar la tupla como se mostró en la ayudantía, es decir, directo en el servidor, sin usar CSV?

**Comment by jmndoza** [comment]
Hola! @mariajesusbraun,
Sí, puedes.

**Comment by mariajesusbraun** [comment]
Gracias!!
