### ISSUE TITLE
Proyecto(Grupo Impar), Duda con los datos.

### ISSUE THREAD

**Issue by csantiagopaz** [IIC2413/Syllabus-2020-1#74]
Hola, Tengo una duda en relación al nombre del Usuario, ese nombre NO es único, verdad?
lo que es único es el username?
Esa información es importante para realizar la consulta 3.

**Comment by SarahEverke** [comment]
Hola,
el nombre de un usuario no es único. El username sí lo es. 
Saludos!

**Comment by jitorcas** [comment]
Hola! En caso que dos personas tengan el mismo nombre "u" , debemos entregar una diferenciación mediante algún otro dato?

**Comment by nivek0o0** [comment]
No se preocupen por que hayan dos personas con nombre "u", no es lo que busca evaluar esa consulta. 

Pueden asumir que ese caso no pasará.

**Comment by jitorcas** [comment]
Gracias! @nivek0o0 
Entonces en la tarea tampoco estaban evaluando personas con nombres iguales?

**Comment by nivek0o0** [comment]
Para el control eso daba lo mismo. Cuando te piden los clientes que hayan hecho tal cosa, tu haces las operaciones a través de los IDs de los usuarios y si al entregar los nombres hay duplicados, da igual.
