### ISSUE TITLE
Consulta sobre tablas en entrega 1

### ISSUE THREAD

**Issue by etoteiza** [IIC2413/Syllabus-2020-1#75]
Hola! 
esperando que estén bien, quería preguntar si al momento de crear las tablas con psql en el servidor, debo ubicarme en el path \grupoxx\Entrega1 ? 
gracias de antemano

**Comment by nivek0o0** [comment]
Hola,
las tablas se crean en la aplicación Postgres, a la que puedes acceder ejecutando el comando `psql` en cualquier parte del servidor, osea, no importa el path.

Lo que debe estar en  `\grupoxx\Entrega1` es un reporte PDF con la entrega 1.
