### ISSUE TITLE
Push Entrega 1

### ISSUE THREAD

**Issue by ticastro** [IIC2413/Syllabus-2020-1#78]
Hola buenas! 
Con mi compañero no entendemos donde debemos subir el pdf con nuestra entrega 1. Entramos al servidor y no hay una carpeta de la Entrega 1, por lo que no sabemos si debemos crearla nosotros o hacerla desde otro lado. No entendemos bien si debemos subirlo a nuestro repositorio de Github y luego subirlo al servidor o si debemos hacerlo de alguna otra manera. 
Gracias de antemano.

**Comment by nbnavarro** [comment]
Hola! 

Tienen varias opciones para subir el archivo (las cuales están en este [link](https://github.com/IIC2413/Syllabus-2020-1/wiki/Tutorial-Servidor-y-Base-de-Datos-Postgresql#introducción) del curso). 

Efectivamente puede que no esté creada la carpeta, si ese es el caso, pueden crearla ustedes y luego subir directamente el archivo al servidor usando SCP (_[opción 2.2](https://github.com/IIC2413/Syllabus-2020-1/wiki/Tutorial-Servidor-y-Base-de-Datos-Postgresql#opción-2-no-utilizar-un-repositorio) en la wiki_) en aquella carpeta que crearon. 

Por otro lado, si están usando github, pueden clonar su repositorio, luego crear la carpeta + informe (trabajando desde su computador), luego hacen git push a su repositorio y por último hacen git pull en el server (_[opción 1](https://github.com/IIC2413/Syllabus-2020-1/wiki/Tutorial-Servidor-y-Base-de-Datos-Postgresql#opción-1-utilizar-un-repositorio-de-git) en la wiki_).
