### ISSUE TITLE
Duda consulta 6 control

### ISSUE THREAD

**Issue by crow-rojas** [IIC2413/Syllabus-2020-1#79]
¡Hola!

Llevo un buen rato pensando la última consulta del control pero aún no se me ocurre como hacerla :/ ¿Cómo expreso un max() en álgebra relacional? ¿Se puede? O, ¿hay alguna otra estrategia para hacerlo? He leído otras issues sobre la misma pregunta pero no me ha quedado claro, ¿me podrían ayudar?

¡Gracias!

**Comment by nivek0o0** [comment]
El primer hint que puedo darte es que tienes que hacer un Self Join de la tabla consigo misma.
Ahora, imagina que tienes dos filas, una en cada mano. ¿Qué condiciones deberías ponerle a ese join para determinar que las filas que tienes en cada mano son distintas y una es menor que la otra?

**Comment by shantifabri** [comment]
Hola, tengo una pregunta respecto a la consulta. En el caso de la instancia dada el producto mas caro es el pid=1. En este caso Tamara compro el producto y seria la respuesta a la consulta. 
En el caso que nadie hubiese comprado el producto pid = 1, ¿la respuesta es una tabla vacía? ¿o debo buscar quien compró el siguiente producto más caro?

**Comment by jmndoza** [comment]
Hola @shantifabri,
Si nadie compro el producto mas caro se retorna una tabla vacía, pero **no puedes**  utilizar que el mas caro es pid = 1, la idea es que tu consulta funcione para estos datos y los futuros que se puedan agregar (algo de 12.458, 20.001.. y cualquier nuevo pid )

**Comment by shantifabri** [comment]
Si el pid=1 era de ejemplo nomas para que se entendiera mi pregunta. Gracias!
