### ISSUE TITLE
Ejercicio propuesto 3.4 Materia Complementaria

### ISSUE THREAD

**Issue by jhfh98** [IIC2413/Syllabus-2020-1#8]
En el ejercicio 3.4 de la guía de material complementario piden los nombres de los actores que aparecen en más de dos películas, ¿No será dos o más películas?
![Captura](https://user-images.githubusercontent.com/53535400/77177533-6fbc1780-6aa4-11ea-94be-6587f56849d5.JPG)

**Comment by alanezz** [comment]
Hola,

Tienes razón, lo que quería preguntar es lo que señalas tú. Ya subí una versión arreglada de la guía. Sin embargo, la consulta que sale ahí, también es posible realizarla siguiendo la misma técnica.

Saludos!
