### ISSUE TITLE
Problema con PowerShell y ssh

### ISSUE THREAD

**Issue by MatiAedo** [IIC2413/Syllabus-2020-1#80]
Hola,  cuando quiero entrar al servidor desde PowerShell no me deja, me arroja el siguiente error:
 Permission denied (publickey,password)
Me pasa lo mismo desde cmd pero puedo acceder desde Git bash, Putty, FileZilla sin problema. Encontré solución al problema pero para Linux y no sé como aplicarlo en Windows.

**Comment by jmndoza** [comment]
Hola @MatiAedo,
No ocupo windows, pero al parecer tienes problemas son ssh-agent.
Prueba `ssh -vvv grupo<numero>@codd.ing.uc.cl`, ahí sale el detalle de la conexión y encontraras el error.

**Comment by nivek0o0** [comment]
Lo que menciona Jerry es útil para saber el origen del error. Hazlo igual.

Hice algunos cambios en el servidor. ¿Puedes probar ahora?

**Comment by MatiAedo** [comment]
Sigo con el mismo error @nivek0o0 . Probé lo que dijo @jerrymendoza y me arroja el siguiente error (Al compararlo con un bash que sí conecta):
debug3: failed to open file:C:/dev/tty error:3
debug1: read_passphrase: can't open /dev/tty: No such file or directory

**Comment by jmndoza** [comment]
Prueba `ssh -o StrictHostKeyChecking=no grupo<x>@codd.ing.puc.cl`

**Comment by nivek0o0** [comment]
Al parecer es un problema con tu versión de SSH, como se discute en este [link](https://serverfault.com/questions/913304/ssh-on-cygwin-win10-read-passphrase-cant-open-dev-tty)

¿Puedes tratar de averiguar cuál tienes, con lo que mencionan allí?
