### ISSUE TITLE
Id sin repetir en tablas diferentes

### ISSUE THREAD

**Issue by bahidalgo** [IIC2413/Syllabus-2020-1#81]
Hola,

Me gustaría saber si es mala práctica tener dos tablas de la forma:

**Tabla 1** 
id_tabla1
1
2
4

**Tabla2**
id_tabla2
3
5

Es decir, ¿puede tenerse dos tablas cuyos id's **no** se repitan?

**Comment by nivek0o0** [comment]
Esas tablas son dos entidades distintas pero que son _del mismo tipo_?

**Comment by bahidalgo** [comment]
Claro, pero poseen diferentes atributos, como el caso de Iglesias, Museos.

**Comment by nivek0o0** [comment]
En ese caso está bien, porque estás evitando guardarlos juntos y generar valores Nulos.

Ahora, esas entidades comparten algunos atributos, como el nombre. Podrías pensar en una forma de agrupar esa información común en una tabla para acceder de forma más fácil a ella y no tener que estar consultando a las otras 3.

Hint: debes hacer **especialización**.
