### ISSUE TITLE
Dudas tipo Horas/Fechas

### ISSUE THREAD

**Issue by Tomas-Ira** [IIC2413/Syllabus-2020-1#82]
Proyecto, grupos impares, tipos de datos.

El manejo de las horas de salida de los viajes y el manejo de las fechas de compra y llegada se hacen en que "tipo", string o int? o existe algo especifico para este tipo de datos que pueda usar? Nose si existe date o time. El problema sería que para los viajes, como salen todos los dias les tengo que asignar una hora y no una fecha exacta.

**Comment by nivek0o0** [comment]
Los tipos de datos que escojas deben ser los adecuados para representar el atributo. Debes decidir si el atributo es solo una fecha, solo una hora o ambas juntas. 

https://www.postgresql.org/docs/10/datatype-datetime.html

**Comment by Tomas-Ira** [comment]
No encuentro los nombres de cada uno de esos. Son date, time y timestamp? Debería considerar los cambios de hora?

**Comment by nivek0o0** [comment]
Si, esos datatypes son los que hay que usar.
No te preocupes por el timezone.
