### ISSUE TITLE
problema repositorio-servidor

### ISSUE THREAD

**Issue by camaruri** [IIC2413/Syllabus-2020-1#83]
segui los pasos del wiki para hacer el repositorio:
quedo todo bien de hecho probe git remote -v y salio lo que tenia que salir.
Pero despues para hacer el primer git pull no me funciona.
Puse: git pull origin master
y me tiro como error:
fatal: Couldn't find remote ref master

**Comment by lucastack** [comment]
Hola! creo que tienes que hacer git pull "tu repo de github privado" master, a mi se me solucionó así
