### ISSUE TITLE
Esquema Proyecto 1

### ISSUE THREAD

**Issue by veneguitas** [IIC2413/Syllabus-2020-1#84]
Hola! Tenía la duda de si había que agregar al esquema las relaciones entre tablas, por ejemplo tengo la tabla Paises y Ciudad, y creé una tabla relacional que relaciona sus primary key para poder saber a que país pertenece cada ciudad.

**Comment by pbyoma** [comment]
Hola, 
Un esquema contiene la definición de una estructura, por lo tanto, tu esquema debe tener todas las tablas necesarias para que soporte los requerimientos del enunciado.
