### ISSUE TITLE
Duda Entrega 1 proyecto (Grupo impar)

### ISSUE THREAD

**Issue by Pdesolmi** [IIC2413/Syllabus-2020-1#85]
Como hago para cuando se hace la consulta ver la fecha o hora actual?
para ver si esque se está realizando un viaje o si fue realizado

**Comment by SarahEverke** [comment]
Hola, revisa la issue #24

**Comment by Pdesolmi** [comment]
gracias!

**Comment by nivek0o0** [comment]
Y la #72 al final
