### ISSUE TITLE
Subrayado de keys

### ISSUE THREAD

**Issue by bahidalgo** [IIC2413/Syllabus-2020-1#87]
Disculpen, tengo una consulta con respecto al subrayado. Si tengo 4 tablas de la forma:

**Tabla 1**(id_persona, nombre_persona, id_comuna)  #Tabla con información de personas
**Tabla 2**(id_persona, id_mascota)   #Relaciona la persona con su mascota
**Tabla 3**(id_mascota, nombre_mascota)  #Tabla con información de mascotas
**Tabla 4**(id_comuna, nombre_ciudad)  #Tabla con información de comunas

¿Debiese subrayar **solo** id_persona en **tabla 1**, id_mascota en **tabla 3** e id_comuna en **tabla 4**? Dado que **tabla 2** solo relaciona los id's de otras tablas.

Auxilio.

**Comment by nivek0o0** [comment]
La tabla2 igual debe tener un conjunto de atributos como PRIMARY KEY para evitar filas duplicadas.

Ese conjunto dependerá de la lógica que quieras modelar. 

* Por ejemplo, si una persona puede tener máximo 1 mascota, entonces debería aparecer a lo más 1 vez en la tabla 2 e id_persona sería PK.
* Si la mascota puede tener máximo un dueño, pasa el caso anterior pero con id_mascota.
* Si la relación es 1:1 entonces tal vez no necesitas tabla intermedia.

Se entiende?

**Comment by bahidalgo** [comment]
Se entiende, pero si una mascota tiene varios dueños y un dueño puede tener varias mascotas, sería entonces recomendable crear una Primary Key para la tabla 2 de la forma:

Tabla 2(id_relacion, id_persona, id_mascota)

¿Y de esa forma agregar una id a cada relación posible?

**Comment by bahidalgo** [comment]
Lo pregunto, porque en las Slides de clases, en la unidad de Modelo Relacional, existe una tabla que se llama "actuo_en" donde no hay una Primary Key y mi objetivo era representar todas las combinaciones posibles de la misma forma.

**Comment by nivek0o0** [comment]
> Tabla 2(**id_relación**, id_persona, id_mascota) ¿Y de esa forma agregar una id a cada relación posible?

Esa es una posible solución, pero si lo piensas, ese ID no lo ocuparás nunca en ningún otro lado, por lo que no sirve de mucho y podemos prescindir de él. 

El caso que mencionas de personas y mascotas sería una asociación de cardinalidad N:M y allí es necesaria una tabla intermedia que junte sus IDs. ¿Qué llave primaria se suele ocupar en estos casos? Pues ambos IDs, porque lo que buscamos es que esa tupla no aparezca repetida en la tabla.  Además, esto permite que haya una persona con muchas mascotas diferentes y una mascota con muchas personas diferentes.

¿Se entiende?

**Comment by nivek0o0** [comment]
A veces se suele omitir la llave primaria en estas tablas intermedias, pero lo más correcto es definirla para evitar que la misma asociación entre, por ejemplo una PersonaX y MascotaY, no se inserte de nuevo generando duplicados y echando a perder algunas consultas.

**Comment by bahidalgo** [comment]
Perfecto, ¿entonces debiese subrayar ambos id's en la tabla 2 para modelar el esquema?

**Comment by ridiazcampos** [comment]
¡Hola! Síiii, si tu tabla tiene dos columnas como llave, entonces puedes subrayar ambas! De esta forma se entiende que en conjunto forman la key 😄

**Comment by bahidalgo** [comment]
Mil gracias
