### ISSUE TITLE
Proyecto entrega 1 par, pregunta 6

### ISSUE THREAD

**Issue by ChayoPerez** [IIC2413/Syllabus-2020-1#88]
Hola!
Ahora que ya pasó la fecha límite para enviarla, sería posible que me dieran una respuesta para la pregunta 6? No la logramos hacer y me gustaría aprender cómo hacerla.

Gracias

**Comment by alanezz** [comment]
Hola,

Esta consulta se hace con agregación, que son cosas que están fuera del álgebra relacional del curso. Por eso en la entrega les pedimos que **hicieran las 3 primeras consultas**. Las otras no tenían que hacerlas, la idea era que pensaran si en el futuro con su esquema creen que las podrían contestar.

Saludos!
