### ISSUE TITLE
Duda notación consultas.

### ISSUE THREAD

**Issue by nhorellana** [IIC2413/Syllabus-2020-1#9]
Hola! He visto que escriben las consultas como por ej "π Actores.anombre (Actores)", se podrá escribir también como  π anombre (Actores)? O es necesario siempre poner la relación.atributo?

**Comment by jmndoza** [comment]
Hola @nhorellana,
Es opcional si no hay conflicto con otro atributo (ej: Actores.**nombre**,  Camarografos.**nombre**).
