### ISSUE TITLE
IDs en los csv

### ISSUE THREAD

**Issue by perezpefaur** [IIC2413/Syllabus-2020-1#91]
Si por ejemplo en la entrega 1 pusimos que existía el atributo id pais (pid) pero en la base de dato no nos dan esa información. ¿Ocupamos como PK el nombre del país?

**Comment by fjlopez7** [comment]
El pid lo pueden crear ustedes. Es solamente un número con el que ustedes saben que corresponde a cierto a país y lo pueden utilizar en otras tablas para referenciarlo.

Lo único que deben respetar es el ID de usuarios, ya que los usaremos para hacer casos de prueba.

**Comment by perezpefaur** [comment]
Pero tambien puedo dejar el nombre de la ciudad como primary key? O el del pais?

**Comment by fjlopez7** [comment]
Lo mejor es que las primary keys sean int, en especial por cosas de eficiencias a nivel computacional.
Si dada una primary key de la tabla y quieres obtener la tupla que va con esa llave, debes recorrer toda la tabla comparando las llaves. Con esto si se tiene un string se deben comparar carácter por carácter, en cambio para un int seria una comparación.  Esto implica en que los joins sean más eficientes si la primary es un int.

**Comment by perezpefaur** [comment]
Pero puedo dejarlo como string? Es que en los datos que me dan no tengo un id de ciudad, por lo que cuando se habla de la entidad **destinos** la ciudad de origen y la ciudad de destino se dan como strings, por lo que tendría que cambiar, estos dos a un int con un código python que compare el nombre con el id que le asigne a cada ciudad, para importar los datos de la mejor manera. Entonces eso me da a entender y por eso pregunto, que la idea del ejercicio es que ocupemos los nombres como primary keys.  Además, estos programas por lo que tengo entendido comparan caracter a caracter, entonces la probabilidad que tenga el primer carácter como número igual a otro es de 1/10, pero en el abecedario es 1/26, asumiendo que estos son completamente alazar (lo cual no son, pero seria una probabilidad mayor para el caso del int porque se repite mas veces ej. 101 102 103 etc..). Gracias!

**Comment by fjlopez7** [comment]
Lo mejor seria no dejarlos como strings. Podrías ocupar un diccionarios en python de la forma ciudad:cid, de tal forma que al leer un archivo con el atributo de ciudad puedas cambiar el nombre por id de la ciudad.  Respecto a lo segundo no es así, se comparan en formato de bits, en general un int seria de 32 bits , siendo su comparación inmediata, pero para char(carácter) se asocia a un respectivo número, de tal forma que un solo carácter sean 8bits, pero en este caso seria un varchar de alrededor de 10 o más, en el que se tiene que ir comparando carácter a carácter la igualdad  por lo que seria mejor seguir con una primary key de int.

**Comment by furzuadr** [comment]
Puedo cambiar los nombres? Por ejemplo que en vez de `uid` se llame `id_usuario`? Gracias!

**Comment by nivek0o0** [comment]
Sí, pueden ponerle los atributos que quieran a sus columnas. 

De hecho, cuando importan un csv a Postgres pueden elegir ignorar el header y el sistema importa las columnas en orden, por lo que su tabla quedará poblada con los atributos que ustedes escogieron.
