### ISSUE TITLE
Archivos CSV y Software a utilizar

### ISSUE THREAD

**Issue by bahidalgo** [IIC2413/Syllabus-2020-1#92]
Hola, 

Soy parte de un grupo par y al descargar los archivos .csv para trabajar en el proyecto, me he dado cuenta que uno de ellos (artistas-obras-lugares) no es un archivo separado por comas. Por otra parte, me di cuenta que en los grupos impares **todos** eran archivos separados por comas, lo que me parece raro. ¿Es un error o debo solucionarlo por mi cuenta?
Por último, si deseo utilizar _R_ como software para importar los datos, ¿debo indicar en algún lugar los pasos que realicé?

Gracias.

**Comment by nivek0o0** [comment]
Hola!

Respecto a los archivos CSV, la separación de los datos no siempre es mediante **comas**(,), también pueden separarse con **punto y coma**(;), **tab**(   ), **barra vertical** (|), etc. La forma de manejar esto es especificar el caracter separador en el programa que vaya a leer ese archivo.

Respecto al programa para manipular los datos, no hay restricciones y no deben explicar nada. Pueden utilizar Python, R, Excel, lo que quieran. Lo **importante** es que no se pierda información en el proceso.
