### ISSUE TITLE
Error con el comando jupyter notebook

### ISSUE THREAD

**Issue by VicenteElCyrano** [IIC2413/Syllabus-2020-1#93]
ayuda, logro descargar todo como se debe pero al escribir el codigo "jupyter notebook" me sale el siguiente error.
Help
![Screenshot_1](https://user-images.githubusercontent.com/48532824/78171562-0258a100-742b-11ea-828b-559ce7c25b6a.png)

**Comment by fjlopez7** [comment]
Intentaste correr el comando en powershell?

**Comment by nivek0o0** [comment]
Apostaría a que la ruta donde está el ejecutable de jupyter no está en la variable de entorno PATH y por eso no encuentra el comando.

**Comment by VicenteElCyrano** [comment]
> Intentaste correr el comando en powershell?

lo intenté y tmb falló.

**Comment by VicenteElCyrano** [comment]
> Apostaría a que la ruta donde está el ejecutable de jupyter no está en la variable de entorno PATH y por eso no encuentra el comando.

si es eso de agregar el PATH manualmente como lo decia la wiki tmb lo hice, sino no sé a que te refieres.

**Comment by nivek0o0** [comment]
Agotaste todas las soluciones que mencionan [aquí](https://stackoverflow.com/questions/41034866/running-jupyter-via-command-line-on-windows)?

**Comment by VicenteElCyrano** [comment]
> Agotaste todas las soluciones que mencionan [aquí](https://stackoverflow.com/questions/41034866/running-jupyter-via-command-line-on-windows)?

Intenté y aparece esto:
![image](https://user-images.githubusercontent.com/48532824/78173193-b4916800-742d-11ea-94f0-0f436bfc0b96.png)

el último me abre una pestaña en el navegador y aparece esto:
![image](https://user-images.githubusercontent.com/48532824/78173272-d2f76380-742d-11ea-8ab9-44a77792e0ce.png)

**Comment by nivek0o0** [comment]
Intenta ejecutar el comando en la carpeta donde está el archivo `.ipynb`

**Comment by VicenteElCyrano** [comment]
buscando acabo de cachar que en AppData/Roaming/  no está la carpeta jupyter -_-
De hecho no la pillo en el pc.
