### ISSUE TITLE
Puntajes en la correción 

### ISSUE THREAD

**Issue by crow-rojas** [IIC2413/Syllabus-2020-1#94]
¡Hola!

Estaba revisando la planilla de notas que tiene la entrega 1, y salen puntos asociados al Esquema y a las Primary Keys, pero en el enunciado de la entrega 1 salía que el Esquema no se iba a evaluar y sería algo preliminar, entonces, ¿qué significan esos puntos?

Además, en el comentario de nuestra entrega el corrector nos puso: "...caer en un error de Forma Normal asociado a redundancia...", ¿cómo sabemos que significa eso si no lo pasaron en clases? ¿cómo podríamos haberlo evitado por lo mismo? Por esto mismo sacamos 1 punto en vez de 2 (que tampoco entiendo porque no era evaluado el esquema).

Espero me puedan aclarar todo, ¡gracias!

**Comment by alanezz** [comment]
Hola,

La distribución de puntaje se publica junto con el enunciado y la puedes encontrar [en el readme](https://github.com/IIC2413/Syllabus-2020-1/tree/master/Proyecto/Entrega1) asociado al enunciado. No evaluamos que el esquema esté bueno en términos de modelación, pero si exigíamos que señalaras las llaves primarias.
Respecto a lo segundo, es un feedback que te puede ser útil para arreglar tu modelación en el transcurso de esta semana y la próxima, donde aprenderemos a "modelar bien".
De todas formas, tu descuento no es por esta falla (de hecho es solo un comentario), sino por el primer comentario: todo lo que se detalla en el enunciado debería verse reflejado en tu modelo. En el caso de tu grupo, faltan las entidades Frescos y Plazas, ya que esto no se ve en ninguna parte de la solución que propusieron. 

Finalmente, si no estás de acuerdo con tu corrección, siempre puedes mandar a recorregir.

**Comment by crow-rojas** [comment]
Ahora me quedó todo más claro, ¡muchas gracias profe!
