### ISSUE TITLE
Uso de AVG en Ejemplo Actores/Actuó_en/Películas

### ISSUE THREAD

**Issue by ChayoPerez** [IIC2413/Syllabus-2020-1#95]
Hola!
Estaba haciendo los ejercicios de SQL y hubo una pregunta que no supe contestar. En el ejemplo de Actores/Actuo_en/Películas una de las preguntas es Promedio de personajes por actor. Puedo llegar a la tabla Actor - número de personajes, pero no logro sacar el promedio.

Pensaba en algo así, pero no funciona u_u
```sql
SELECT  AVG(COUNT(DISTINCT Actuo_en.nombre_personaje)) FROM Actores, Actuo_en WHERE Actores.aid=Actuo_en.aid
```

Gracias!

**Comment by fjlopez7** [comment]
Puede ser que te falte un GROUP BY aid.

**Comment by ChayoPerez** [comment]
```sql
SELECT AVG(COUNT(DISTINCT Actuo_en.nombre_personaje)) FROM Actores, Actuo_en WHERE Actores.aid=Actuo_en.aid GROUP BY aid ;
```
Error: misuse of aggregate function COUNT()

:(

**Comment by fjlopez7** [comment]
Proyecta el nombre el actor, junto con el promedio.

**Comment by ChayoPerez** [comment]
```sql
SELECT anombre, AVG(COUNT(DISTINCT Actuo_en.nombre_personaje)) FROM Actores, Actuo_en WHERE Actores.aid=Actuo_en.aid GROUP BY aid ;
```
Error: misuse of aggregate function COUNT()
Sigue sin funcionar

**Comment by fjlopez7** [comment]
Primero debes obtener la cantidad de Personajes por actor que seria:
```sql
SELECT COUNT(DISTINCT nombre_personaje ) AS Npersonajes FROM Actuo_en GROUP BY aid;
``` 
Luego debes sacar el promedio de esas cantidades:
```sql
SELECT AVG( Npersonajes ) AS PromedioPersonajes FROM (SELECT COUNT(DISTINCT nombre_personaje ) AS Npersonajes FROM Actuo_en GROUP BY aid);
```

**Comment by ChayoPerez** [comment]
Muchas gracias! Todo funciona :)
