### ISSUE TITLE
Conectar la base de datos del servidor a PgAdmin y/o a DataGrip

### ISSUE THREAD

**Issue by JuaniAndres** [IIC2413/Syllabus-2020-1#97]
Hola quería saber si es que se puede conectar uno a la base de datos del servidor usando alguna de las aplicaciones del titulo. En el caso que se pueda como puedo hacerlo?
Gracias de antemano

**Comment by nivek0o0** [comment]
Hola, la base de datos está expuesta para que puedan conectarse a ella de forma externa.
¿Has intentado conectarte con alguna de esas aplicaciones?

Las credenciales deberían ser la dirección del servidor (codd.ing.puc.cl), el puerto (5432), tu usuario y contraseña de Postgres y finalmente el nombre de la base de datos.

**Comment by JuaniAndres** [comment]
Hola estuve tratando pero no e podido ingresar probablemente porque ingrese algo mal en las configuraciones
En pgadmin el error es: Error: Could not establish session to SSH gateway
Asumo que el error esta en esta parte:
![pg admin](https://user-images.githubusercontent.com/48482216/78463507-e1ef4780-76b3-11ea-90cc-20a9b1a3d18f.PNG)


En caso de  DataGrip me da un error similar: Connection to postgres@localhost failed: SSH: Connection timed out: connect. SSH: Connection timed out: connect
Igual en este estoy más perdido con lo que hay que ingresar
![datagrip](https://user-images.githubusercontent.com/48482216/78463476-7ad19300-76b3-11ea-9d12-5d9baa2a250e.PNG)
![datagrip 2](https://user-images.githubusercontent.com/48482216/78463477-7c9b5680-76b3-11ea-96d7-4a3fdd8fca42.PNG)

**Comment by nivek0o0** [comment]
Ahora te debería funcionar, ya que antes el puerto estaba bloqueado

**Comment by JuaniAndres** [comment]
Hola Kevin probé recién con pgadmin y fallo de nuevo en la misma parte: 
Failed to create the SSH tunnel.
Error: Could not establish session to SSH gateway
No se si sera un problema por mi lado

**Comment by nivek0o0** [comment]
¿Y por qué tratas de usar un SSH tunel? La conexión normal funciona correctamente.

**Comment by JuaniAndres** [comment]
Tienes razón pensaba que se tenia que conectar con un tunel
Ahora lo hice sin esa parte y ya me funciono muchas gracias
