### ISSUE TITLE
Horario de salida de los Viajes

### ISSUE THREAD

**Issue by perezpefaur** [IIC2413/Syllabus-2020-1#99]
A que se refiere específicamente esto del enunciado:
_Dos ciudades pueden tener más de un horario de salida_

**Comment by nivek0o0** [comment]
Significa que entre dos ciudades A y B pueden existir viajes que salen a las 10:00, 10:30, 13:00, 14:45, 18:00, etc.
Además, esos horarios se repiten los 7 días de la semana, lo que te da un indicio de que basta con guardar solo un `TIME` y no un `TIMESTAMP`.

**Comment by perezpefaur** [comment]
Ya buenisimo y que atributos hacen que el destino sea unico. La combinación de hora, ciudad a y ciudad b? Puede haber dos destino que salgan de la ciudad a hacia la b a la misma hora con un medio de transporte distinto o capacidad distinta? O asumimos que todos los destinos en el archivo son distintos y le damos un id a cada uno? (Igual le voy a entregar un id, pero es para sortear los destinos que son repetidos)

**Comment by nivek0o0** [comment]
#103
